local _, GQ = ...
GQ.Data = GQ.Data or {}

-- GENERATED -- Warlock, ALLIANCE, HORDE, levels 1-9. Nothing else is in this file:
-- no Alliance rows and no level 10 or above, so it can sit next to the
-- hand-made Alliance 1-9 data without either overwriting the other.
--
-- The race filter is the class's own playable races for that faction, not the whole
-- faction: a Horde warrior can be Orc, Undead, Tauren or Troll but never a Blood Elf,
-- so Blood Elf starting quests are gated out. Quests are gated on quest_template.RequiredRaces, and
-- faction-exclusive zones are gated by name -- a vendor standing in Darnassus is
-- not race-restricted, the city is.
--
-- No spec column. Warlocks have no talents before level 10, so one list serves all
-- three specs across this range.
--
-- row = { itemId, slot, minLevel, maxLevel, rank, score }
--   optional: suffix, suffixChance  (random-enchantment items -- score assumes the
--   best roll, and suffixChance is the odds of getting any roll of that suffix)

GQ.Data.warlockEarly1to9Facts = {
    [79]={name="Dwarven Cloth Britches",sourceType="quest_reward",instructions="Reward from the quest “The Boar Hunter” — pick it over the other choices. In Coldridge Valley.",zone="Coldridge Valley",questName="The Boar Hunter",lore="Nothing like a day of boar hunting, eh? Though, here in Coldridge Valley, there are so many boars it almost takes the fun out of it. No need to get them charging."},
    [80]={name="Soft Fur-lined Shoes",sourceType="quest_reward",instructions="Reward from the quest “Wolves Across the Border” — pick it over the other choices. In Northshire Valley.",zone="Northshire Valley",questName="Wolves Across the Border",lore="I hate those nasty timber wolves! But I sure like eating wolf steaks... Bring me tough wolf meat and I will exchange it for something you'll find useful."},
    [193]={name="Tattered Cloth Vest",sourceType="vendor",instructions="Bought from Lauren Newcomb in Undercity.",zone="Undercity",npc="Lauren Newcomb"},
    [194]={name="Tattered Cloth Pants",sourceType="vendor",instructions="Bought from Lauren Newcomb in Undercity.",zone="Undercity",npc="Lauren Newcomb"},
    [195]={name="Tattered Cloth Boots",sourceType="vendor",instructions="Bought from Lauren Newcomb in Undercity.",zone="Undercity",npc="Lauren Newcomb"},
    [710]={name="Bracers of the People's Militia",sourceType="quest_reward",instructions="Reward from the quest “Patrolling Westfall” — pick it over the other choices. In Westfall.",zone="Westfall",questName="Patrolling Westfall",lore="Stormwind has abandoned us. A foul wind of depravity rustles through the plains of Westfall. This was my homeland and I will not turn my back on the citizens who choose to remain here."},
    [711]={name="Tattered Cloth Gloves",sourceType="vendor",instructions="Bought from Lauren Newcomb in Undercity.",zone="Undercity",npc="Lauren Newcomb"},
    [719]={name="Rabbit Handler Gloves",sourceType="quest_reward",instructions="Reward from the quest “Dwarven Outfitters” — pick it over the other choices. In Coldridge Valley.",zone="Coldridge Valley",questName="Dwarven Outfitters",lore="You look as though you might need something to keep your hands warm, hm? I'll tell you what would help: a pair of nice, warm gloves."},
    [792]={name="Knitted Sandals",sourceType="world_drop",instructions="Drops from Pyrewood Tailor in Pyrewood Village.",zone="Pyrewood Village",npc="Pyrewood Tailor"},
    [793]={name="Knitted Gloves",sourceType="world_drop",instructions="Drops from Pyrewood Tailor in Pyrewood Village.",zone="Pyrewood Village",npc="Pyrewood Tailor"},
    [794]={name="Knitted Pants",sourceType="world_drop",instructions="Drops from Pyrewood Tailor in Pyrewood Village.",zone="Pyrewood Village",npc="Pyrewood Tailor"},
    [983]={name="Red Linen Sash",sourceType="quest_reward",instructions="Reward from the quest “Red Linen Goods”. In Elwynn Forest.",zone="Elwynn Forest",questName="Red Linen Goods",lore="The Defias gang in Northshire wears burlap masks, but the Defias in Elwynn wear linen which I can use to make fine linen goods."},
    [1376]={name="Frayed Cloak",sourceType="world_drop",instructions="World drop — drops from 62 creature types around level 1-5. Also found on the auction house."},
    [1421]={name="Worn Hide Cloak",sourceType="world_drop",instructions="World drop — drops from 236 creature types around level 1-10. Also found on the auction house."},
    [1429]={name="Patchwork Cloak",sourceType="world_drop",instructions="World drop — drops from 236 creature types around level 1-10. Also found on the auction house."},
    [1430]={name="Patchwork Gloves",sourceType="world_drop",instructions="World drop — drops from 236 creature types around level 1-10. Also found on the auction house."},
    [1431]={name="Patchwork Pants",sourceType="world_drop",instructions="World drop — drops from 236 creature types around level 1-10. Also found on the auction house."},
    [1433]={name="Patchwork Armor",sourceType="world_drop",instructions="World drop — drops from 236 creature types around level 1-10. Also found on the auction house."},
    [1495]={name="Calico Shoes",sourceType="world_drop",instructions="World drop — drops from 242 creature types around level 9-15. Also found on the auction house."},
    [1497]={name="Calico Cloak",sourceType="world_drop",instructions="World drop — drops from 242 creature types around level 9-15. Also found on the auction house."},
    [1917]={name="Jeweled Dagger",sourceType="world_drop",instructions="Drops from Morgaine the Sly (rare spawn) in Goldshire.",zone="Goldshire",npc="Morgaine the Sly"},
    [2114]={name="Snowy Robe",sourceType="world_drop",instructions="Drops from Starving Winter Wolf in Brewnall Village.",zone="Brewnall Village",npc="Starving Winter Wolf"},
    [2117]={name="Thin Cloth Shoes",sourceType="vendor",instructions="Bought from Gamili Frosthide in Kharanos.",zone="Kharanos",npc="Gamili Frosthide"},
    [2119]={name="Thin Cloth Gloves",sourceType="vendor",instructions="Bought from Gamili Frosthide in Kharanos.",zone="Kharanos",npc="Gamili Frosthide"},
    [2120]={name="Thin Cloth Pants",sourceType="vendor",instructions="Bought from Gamili Frosthide in Kharanos.",zone="Kharanos",npc="Gamili Frosthide"},
    [2121]={name="Thin Cloth Armor",sourceType="vendor",instructions="Bought from Gamili Frosthide in Kharanos.",zone="Kharanos",npc="Gamili Frosthide"},
    [2310]={name="Embossed Leather Cloak",sourceType="profession",instructions="Crafted with Leatherworking (requires skill 65).",profession="Leatherworking"},
    [2326]={name="Ivy-weave Bracers",sourceType="quest_reward",instructions="Reward from the quest “The Perfect Stout” — pick it over the other choices. In Dun Morogh.",zone="Dun Morogh",questName="The Perfect Stout",lore="I'm on a quest, a quest to make the perfect stout. I know I can do it -- brewing's in my blood. I just need to find the right recipe... The Frostmane trolls grow a plant, shimmerweed, high up in the hills to the east."},
    [2367]={name="Woven Boots",sourceType="vendor",instructions="Bought from Lauren Newcomb in Undercity.",zone="Undercity",npc="Lauren Newcomb"},
    [2369]={name="Woven Gloves",sourceType="vendor",instructions="Bought from Lauren Newcomb in Undercity.",zone="Undercity",npc="Lauren Newcomb"},
    [2568]={name="Brown Linen Vest",sourceType="profession",instructions="Crafted with Tailoring (requires skill 1).",profession="Tailoring"},
    [2569]={name="Linen Boots",sourceType="profession",instructions="Crafted with Tailoring (requires skill 1).",profession="Tailoring"},
    [2570]={name="Linen Cloak",sourceType="profession",instructions="Crafted with Tailoring (requires skill 1).",profession="Tailoring"},
    [2572]={name="Red Linen Robe",sourceType="profession",instructions="Crafted with Tailoring (requires skill 1).",profession="Tailoring"},
    [2580]={name="Reinforced Linen Cape",sourceType="profession",instructions="Crafted with Tailoring (requires skill 1).",profession="Tailoring"},
    [2612]={name="Plain Robe",sourceType="vendor",instructions="Bought from Tor'phan in Orgrimmar.",zone="Orgrimmar",npc="Tor'phan"},
    [2905]={name="Goat Fur Cloak",sourceType="quest_reward",instructions="Reward from the quest “The Perfect Stout” — pick it over the other choices. In Dun Morogh.",zone="Dun Morogh",questName="The Perfect Stout",lore="I'm on a quest, a quest to make the perfect stout. I know I can do it -- brewing's in my blood. I just need to find the right recipe... The Frostmane trolls grow a plant, shimmerweed, high up in the hills to the east."},
    [2957]={name="Journeyman's Vest",sourceType="world_drop",instructions="World drop — drops from 401 creature types around level 6-14. Also found on the auction house."},
    [2958]={name="Journeyman's Pants",sourceType="world_drop",instructions="World drop — drops from 339 creature types around level 6-14. Also found on the auction house."},
    [2959]={name="Journeyman's Boots",sourceType="world_drop",instructions="World drop — drops from 314 creature types around level 5-14. Also found on the auction house."},
    [2960]={name="Journeyman's Gloves",sourceType="world_drop",instructions="World drop — drops from 314 creature types around level 5-14. Also found on the auction house."},
    [2971]={name="Spellbinder Boots",sourceType="world_drop",instructions="World drop — drops from 355 creature types around level 9-15. Also found on the auction house."},
    [2972]={name="Spellbinder Gloves",sourceType="world_drop",instructions="World drop — drops from 355 creature types around level 9-15. Also found on the auction house."},
    [3008]={name="Wendigo Fur Cloak",sourceType="world_drop",instructions="Drops from Edan the Howler (rare spawn) in Kharanos.",zone="Kharanos",npc="Edan the Howler"},
    [3224]={name="Silver-lined Bracers",sourceType="world_drop",instructions="Drops from Timber (rare spawn) in Brewnall Village.",zone="Brewnall Village",npc="Timber"},
    [3270]={name="Flax Vest",sourceType="quest_reward",instructions="Reward from the quest “Night Web's Hollow” — pick it over the other choices. In Deathknell.",zone="Deathknell",questName="Night Web's Hollow",lore="One of our greatest struggles is obtaining the natural resources we need to survive. Gold was scarce even in the height of the Alliance's power."},
    [3274]={name="Flax Boots",sourceType="quest_reward",instructions="Reward from the quest “Rattling the Rattlecages” — pick it over the other choices. In Deathknell.",zone="Deathknell",questName="Rattling the Rattlecages",lore="You've shown your potential to the Forsaken under normal circumstances - now let's see you under pressure. The Rattlecage skeletons, more mindless minions of the Lich King, are a tougher foe than the zombies you have faced thus far."},
    [3275]={name="Flax Gloves",sourceType="quest_reward",instructions="Reward from the quest “The Mindless Ones” — pick it over the other choices. In Deathknell.",zone="Deathknell",questName="The Mindless Ones",lore="We Forsaken are at war with the Lich King's army of the Scourge: necromantically raised armies of the undead, foul beasts of the north, and tormented spectres."},
    [3289]={name="Ancestral Boots",sourceType="world_drop",instructions="World drop — drops from 416 creature types around level 5-14. Also found on the auction house."},
    [3290]={name="Ancestral Gloves",sourceType="world_drop",instructions="World drop — drops from 435 creature types around level 6-14. Also found on the auction house."},
    [3291]={name="Ancestral Woollies",sourceType="world_drop",instructions="World drop — drops from 380 creature types around level 8-14. Also found on the auction house."},
    [3322]={name="Wispy Cloak",sourceType="world_drop",instructions="Drops from Lost Soul (rare spawn) in Brill.",zone="Brill",npc="Lost Soul"},
    [3323]={name="Ghostly Bracers",sourceType="world_drop",instructions="Drops from Tormented Spirit (rare spawn) in Eastern Kingdoms.",zone="Eastern Kingdoms",npc="Tormented Spirit"},
    [3328]={name="Spider Web Robe",sourceType="world_drop",instructions="Drops from Vicious Night Web Spider in The Bulwark.",zone="The Bulwark",npc="Vicious Night Web Spider"},
    [3331]={name="Melrache's Cape",sourceType="world_drop",instructions="Drops from Captain Melrache in Scarlet Monastery.",zone="Scarlet Monastery",npc="Captain Melrache"},
    [3363]={name="Frayed Belt",sourceType="world_drop",instructions="World drop — drops from 62 creature types around level 1-5. Also found on the auction house."},
    [3365]={name="Frayed Bracers",sourceType="world_drop",instructions="World drop — drops from 62 creature types around level 1-5. Also found on the auction house."},
    [3370]={name="Patchwork Belt",sourceType="world_drop",instructions="World drop — drops from 236 creature types around level 1-10. Also found on the auction house."},
    [3373]={name="Patchwork Bracers",sourceType="world_drop",instructions="World drop — drops from 236 creature types around level 1-10. Also found on the auction house."},
    [3374]={name="Calico Belt",sourceType="world_drop",instructions="World drop — drops from 242 creature types around level 9-15. Also found on the auction house."},
    [3375]={name="Calico Bracers",sourceType="world_drop",instructions="World drop — drops from 242 creature types around level 9-15. Also found on the auction house."},
    [3442]={name="Apprentice Sash",sourceType="quest_reward",instructions="Reward from the quest “A New Plague”. In Tirisfal Glades.",zone="Tirisfal Glades",questName="A New Plague",lore="While you were out gathering, I uncovered some old text in one of my tomes that indicates that an ancient plague wiped out thousands of innocent victims."},
    [3446]={name="Darkwood Staff",sourceType="quest_reward",instructions="Reward from the quest “The Family Crypt” — pick it over the other choices. In Tirisfal Glades.",zone="Tirisfal Glades",questName="The Family Crypt",lore="The Agamand Mills area has become a foothold for the Scourge. Their strongest point is the Agamand Family Crypt where their local military leader, a skeleton named Captain Dargol, has headquartered."},
    [3595]={name="Tattered Cloth Belt",sourceType="vendor",instructions="Bought from Lauren Newcomb in Undercity.",zone="Undercity",npc="Lauren Newcomb"},
    [3596]={name="Tattered Cloth Bracers",sourceType="vendor",instructions="Bought from Lauren Newcomb in Undercity.",zone="Undercity",npc="Lauren Newcomb"},
    [3599]={name="Thin Cloth Belt",sourceType="vendor",instructions="Bought from Gamili Frosthide in Kharanos.",zone="Kharanos",npc="Gamili Frosthide"},
    [3600]={name="Thin Cloth Bracers",sourceType="vendor",instructions="Bought from Gamili Frosthide in Kharanos.",zone="Kharanos",npc="Gamili Frosthide"},
    [3602]={name="Knitted Belt",sourceType="world_drop",instructions="Drops from Pyrewood Tailor in Pyrewood Village.",zone="Pyrewood Village",npc="Pyrewood Tailor"},
    [3603]={name="Knitted Bracers",sourceType="world_drop",instructions="Drops from Pyrewood Tailor in Pyrewood Village.",zone="Pyrewood Village",npc="Pyrewood Tailor"},
    [3606]={name="Woven Belt",sourceType="vendor",instructions="Bought from Lauren Newcomb in Undercity.",zone="Undercity",npc="Lauren Newcomb"},
    [3607]={name="Woven Bracers",sourceType="vendor",instructions="Bought from Lauren Newcomb in Undercity.",zone="Undercity",npc="Lauren Newcomb"},
    [3641]={name="Journeyman's Bracers",sourceType="world_drop",instructions="World drop — drops from 241 creature types around level 5-10. Also found on the auction house."},
    [3643]={name="Spellbinder Bracers",sourceType="world_drop",instructions="World drop — drops from 355 creature types around level 9-15. Also found on the auction house."},
    [3644]={name="Barbaric Cloth Bracers",sourceType="world_drop",instructions="World drop — drops from 435 creature types around level 6-14. Also found on the auction house."},
    [4261]={name="Solliden's Trousers",sourceType="world_drop",instructions="Drops from Farmer Solliden (rare spawn) in Deathknell.",zone="Deathknell",npc="Farmer Solliden"},
    [4307]={name="Heavy Linen Gloves",sourceType="profession",instructions="Crafted with Tailoring (requires skill 1).",profession="Tailoring"},
    [4308]={name="Green Linen Bracers",sourceType="profession",instructions="Crafted with Tailoring (requires skill 1).",profession="Tailoring"},
    [4309]={name="Handstitched Linen Britches",sourceType="profession",instructions="Crafted with Tailoring (requires skill 1).",profession="Tailoring"},
    [4658]={name="Warrior's Cloak",sourceType="world_drop",instructions="World drop — drops from 241 creature types around level 5-10. Also found on the auction house."},
    [4662]={name="Journeyman's Cloak",sourceType="world_drop",instructions="World drop — drops from 241 creature types around level 5-10. Also found on the auction house."},
    [4663]={name="Journeyman's Belt",sourceType="world_drop",instructions="World drop — drops from 314 creature types around level 5-14. Also found on the auction house."},
    [4665]={name="Burnt Cloak",sourceType="world_drop",instructions="World drop — drops from 241 creature types around level 5-10. Also found on the auction house."},
    [4668]={name="Battle Chain Cloak",sourceType="world_drop",instructions="World drop — drops from 314 creature types around level 5-14. Also found on the auction house."},
    [4671]={name="Ancestral Cloak",sourceType="world_drop",instructions="World drop — drops from 314 creature types around level 5-14. Also found on the auction house."},
    [4672]={name="Ancestral Belt",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 5-14. Also found on the auction house."},
    [4674]={name="Tribal Cloak",sourceType="world_drop",instructions="World drop — drops from 314 creature types around level 5-14. Also found on the auction house."},
    [4677]={name="Veteran Cloak",sourceType="world_drop",instructions="World drop — drops from 435 creature types around level 6-14. Also found on the auction house."},
    [4680]={name="Brackwater Cloak",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 8-14. Also found on the auction house."},
    [4683]={name="Spellbinder Cloak",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 8-14. Also found on the auction house."},
    [4684]={name="Spellbinder Belt",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 8-14. Also found on the auction house."},
    [4687]={name="Barbaric Cloth Belt",sourceType="world_drop",instructions="World drop — drops from 355 creature types around level 9-15. Also found on the auction house."},
    [4772]={name="Warm Cloak",sourceType="world_drop",instructions="Drops from Sister Hatelash (rare spawn) in Thunder Bluff.",zone="Thunder Bluff",npc="Sister Hatelash"},
    [4854]={name="Demon Scarred Cloak",sourceType="world_drop",instructions="Drops from Ghost Howl (rare spawn) in Thunder Bluff.",zone="Thunder Bluff",npc="Ghost Howl"},
    [4915]={name="Soft Wool Boots",sourceType="quest_reward",instructions="Reward from the quest “Cutting Teeth” — pick it over the other choices. In Valley of Trials.",zone="Valley of Trials",questName="Cutting Teeth",lore="The first order of business will be to put a little strength in your backbone. I could send you out to the Barrens to hunt kodo, but well, in all honesty, you're more useful to us alive than dead."},
    [4916]={name="Soft Wool Vest",sourceType="quest_reward",instructions="Reward from the quest “Sarkoth” — pick it over the other choices. In Valley of Trials.",zone="Valley of Trials",questName="Sarkoth",lore="Seeing the deed you have done for me steels my heart. I cannot fall so easily! I must endure! But it remains that I cannot make the trek back to the Den unassisted."},
    [4919]={name="Soft Wool Belt",sourceType="quest_reward",instructions="Reward from the quest “Sting of the Scorpid” — pick it over the other choices. In Valley of Trials.",zone="Valley of Trials",questName="Sting of the Scorpid",lore="Powerful warrior and awkward novice alike have fallen to the venomous sting of the scorpid. You will find large numbers of scorpids northwest of here."},
    [4936]={name="Dirt-trodden Boots",sourceType="quest_reward",instructions="Reward from the quest “From The Wreckage....” — pick it over the other choices. In Durotar.",zone="Durotar",questName="From The Wreckage....",lore="One of my most observant scouts brings back word that the wreckage of Proudmoore's fleet still remains off the coast of Durotar, just east of Tiragarde Keep."},
    [5069]={name="Fire Wand",sourceType="world_drop",instructions="World drop — drops from 466 creature types around level 6-14. Also found on the auction house."},
    [5071]={name="Shadow Wand",sourceType="world_drop",instructions="World drop — drops from 359 creature types around level 9-15. Also found on the auction house."},
    [5458]={name="Dirtwood Belt",sourceType="quest_reward",instructions="Reward from the quest “Oakenscowl” — pick it over the other choices. In Teldrassil.",zone="Teldrassil",questName="Oakenscowl",lore="In a cave along the southern bank of the lake, a timberling named Oakenscowl is spreading corruption to all the creatures that make Lake Al'Ameth their home."},
    [5591]={name="Rain-spotted Cape",sourceType="quest_reward",instructions="Reward from the quest “The Enchanted Glade” — pick it over the other choices. In Teldrassil.",zone="Teldrassil",questName="The Enchanted Glade",lore="I was dispatched with a small group of Sentinels here to protect the Oracle Tree from the harpies that have made nests all around the glade."},
    [5604]={name="Elven Wand",sourceType="quest_reward",instructions="Reward from the quest “Bashal'Aran” — pick it over the other choices. In Darkshore.",zone="Darkshore",questName="Bashal'Aran",lore="It was the craft of one of the most powerful of the Highborne that created the seal that formed my prison. In Ameth'Aran, the ruins to the south that are twin to these, persists even today an ancient flame, blue in color."},
    [5606]={name="Gardening Gloves",sourceType="quest_reward",instructions="Reward from the quest “Timberling Sprouts” — pick it over the other choices. In Teldrassil.",zone="Teldrassil",questName="Timberling Sprouts",lore="Small timberlings are sprouting around the waters of Lake Al'Ameth. I'm afraid these sprouts are beyond help -- we should try to clear them from the land before they grow large enough to cause trouble."},
    [5767]={name="Violet Robes",sourceType="world_drop",instructions="Drops from Frostmane Seer in Kharanos.",zone="Kharanos",npc="Frostmane Seer"},
    [6060]={name="Flax Bracers",sourceType="quest_reward",instructions="Reward from the quest “The Damned” — pick it over the other choices. In Deathknell.",zone="Deathknell",questName="The Damned",lore="My duties include tending to our wounded warriors, tailoring armor and clothes, and assisting Shadow Priest Sarvis with whatever else he might need."},
    [6148]={name="Web-covered Boots",sourceType="world_drop",instructions="Drops from Mother Fang (rare spawn) in Northshire Valley.",zone="Northshire Valley",npc="Mother Fang"},
    [6173]={name="Snow Boots",sourceType="quest_reward",instructions="Reward from the quest “A New Threat” — pick it over the other choices. In Coldridge Valley.",zone="Coldridge Valley",questName="A New Threat",lore="I hope you're here to lend us a hand. After the last trogg attack, we could use all the help we can get. I hear the buggers have been popping up all across the lands, and it seems Coldridge Valley is no exception."},
    [6202]={name="Fingerless Gloves",sourceType="world_drop",instructions="Drops from Thuros Lightfingers (rare spawn) in Elwynn Forest.",zone="Elwynn Forest",npc="Thuros Lightfingers"},
    [6215]={name="Balanced Fighting Stick",sourceType="quest_reward",instructions="Reward from the quest “Wanted:  \"Hogger\"” — pick it over the other choices. In Elwynn Forest.",zone="Elwynn Forest",questName="Wanted:  \"Hogger\"",lore="Wanted: Hogger A huge gnoll, Hogger, is prowling the woods in southwestern Elwynn. He has overpowered all attempts at his capture. The Stormwind Army has placed a generous bounty on the Gnoll."},
    [6238]={name="Brown Linen Robe",sourceType="profession",instructions="Crafted with Tailoring (requires skill 1).",profession="Tailoring"},
    [6239]={name="Red Linen Vest",sourceType="profession",instructions="Crafted with Tailoring (requires skill 1).",profession="Tailoring"},
    [6241]={name="White Linen Robe",sourceType="profession",instructions="Crafted with Tailoring (requires skill 1).",profession="Tailoring"},
    [6266]={name="Disciple's Vest",sourceType="world_drop",instructions="World drop — drops from 380 creature types around level 8-14. Also found on the auction house."},
    [6511]={name="Journeyman's Robe",sourceType="world_drop",instructions="World drop — drops from 401 creature types around level 6-14. Also found on the auction house."},
    [6512]={name="Disciple's Robe",sourceType="world_drop",instructions="World drop — drops from 380 creature types around level 8-14. Also found on the auction house."},
    [6514]={name="Disciple's Cloak",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 5-14. Also found on the auction house."},
    [6515]={name="Disciple's Gloves",sourceType="world_drop",instructions="World drop — drops from 416 creature types around level 5-14. Also found on the auction house."},
    [6713]={name="Ripped Pants",sourceType="quest_reward",instructions="Reward from the quest “Burning Blade Medallion” — pick it over the other choices. In Valley of Trials.",zone="Valley of Trials",questName="Burning Blade Medallion",lore="Through my divinations, I see that an item of power hides deep within the Burning Blade Coven, guarded by beasts and black magic. It is called the Burning Blade Medallion, and your next task is to find it and remove it from the coven."},
    [7026]={name="Linen Belt",sourceType="profession",instructions="Crafted with Tailoring (requires skill 1).",profession="Tailoring"},
    [7095]={name="Bog Boots",sourceType="world_drop",instructions="Drops from Timberling Mire Beast in Teldrassil.",zone="Teldrassil",npc="Timberling Mire Beast"},
    [7351]={name="Disciple's Boots",sourceType="world_drop",instructions="World drop — drops from 416 creature types around level 5-14. Also found on the auction house."},
    [9603]={name="Gritroot Staff",sourceType="quest_reward",instructions="Reward from the quest “The Relics of Wakening” — pick it over the other choices. In Teldrassil.",zone="Teldrassil",questName="The Relics of Wakening",lore="Gnarlpine invaders were seen ravaging the Ban'ethil Barrow Den to the west. The slumbering druids will be trapped in the Emerald Dream for eternity, unaware of their fate, unless we help."},
    [9742]={name="Simple Cord",sourceType="world_drop",instructions="World drop — drops from 435 creature types around level 6-14. Also found on the auction house."},
    [9743]={name="Simple Shoes",sourceType="world_drop",instructions="World drop — drops from 435 creature types around level 6-14. Also found on the auction house."},
    [9745]={name="Simple Cape",sourceType="world_drop",instructions="World drop — drops from 416 creature types around level 5-14. Also found on the auction house."},
    [9746]={name="Simple Gloves",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 8-14. Also found on the auction house."},
    [9754]={name="Gypsy Cloak",sourceType="world_drop",instructions="World drop — drops from 416 creature types around level 5-14. Also found on the auction house."},
    [10035]={name="Tuxedo Pants",sourceType="profession",instructions="Crafted with Tailoring (requires skill 1).",profession="Tailoring"},
    [10045]={name="Simple Linen Pants",sourceType="profession",instructions="Crafted with Tailoring (requires skill 1).",profession="Tailoring"},
    [10046]={name="Simple Linen Boots",sourceType="profession",instructions="Crafted with Tailoring (requires skill 1).",profession="Tailoring"},
    [10549]={name="Rancher's Trousers",sourceType="quest_reward",instructions="Reward from the quest “Protecting the Herd” — pick it over the other choices. In Dun Morogh.",zone="Dun Morogh",questName="Protecting the Herd",lore="We heard the cries in the middle of the night. Then this morning, sure enough, the herd was missing two rams. That dastardly beast known as Vagash has been preying on our livelihood."},
    [10550]={name="Wooly Mittens",sourceType="quest_reward",instructions="Reward from the quest “Tundra MacGrann's Stolen Stash” — pick it over the other choices. In Dun Morogh.",zone="Dun Morogh",questName="Tundra MacGrann's Stolen Stash",lore="I had a month's worth of dried meats salted and locked away for the cold season. Kept it locked so the bears wouldn't get it! But while I was off hunting deer, that beast, Old Icebeard, made off with the meat locker."},
    [10553]={name="Foreman Vest",sourceType="world_drop",instructions="Drops from Gibblewilt (rare spawn) in Brewnall Village.",zone="Brewnall Village",npc="Gibblewilt"},
    [10554]={name="Foreman Pants",sourceType="world_drop",instructions="Drops from Gibblewilt (rare spawn) in Brewnall Village.",zone="Brewnall Village",npc="Gibblewilt"},
    [11187]={name="Stemleaf Bracers",sourceType="quest_reward",instructions="Reward from the quest “The Balance of Nature” — pick it over the other choices. In Shadowglen.",zone="Shadowglen",questName="The Balance of Nature",lore="Greetings. I am Conservator Ilthalaine. My purpose in Shadowglen is to ensure that the balance of nature is maintained."},
    [11189]={name="Woodland Robes",sourceType="quest_reward",instructions="Reward from the quest “Webwood Egg” — pick it over the other choices. In Shadowglen.",zone="Shadowglen",questName="Webwood Egg",lore="Now that I have the spiders' venom, I'd like some live specimens to study. Unfortunately, capturing a living, giant spider is more than I can ask of you, young."},
    [11190]={name="Viny Gloves",sourceType="quest_reward",instructions="Reward from the quest “The Woodland Protector” — pick it over the other choices. In Shadowglen.",zone="Shadowglen",questName="The Woodland Protector",lore="Something evil is brewing in the forests of Teldrassil. Look long the hills to where the peaceful furbolgs used to dwell. They have deserted their homes and are amassing under the name of the Gnarlpine tribe."},
    [11287]={name="Lesser Magic Wand",sourceType="profession",instructions="Crafted with Enchanting (requires skill 1).",profession="Enchanting"},
    [11848]={name="Flax Belt",sourceType="quest_reward",instructions="Reward from the quest “Scavenging Deathknell” — pick it over the other choices. In Deathknell.",zone="Deathknell",questName="Scavenging Deathknell",lore="You there! If you're looking for something to make yourself useful, then listen up! We need fresh out-of-the-ground recruits to head into Deathknell and search for any sort of useful equipment."},
    [14086]={name="Beaded Sandals",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 5-14. Also found on the auction house."},
    [14087]={name="Beaded Cuffs",sourceType="world_drop",instructions="World drop — drops from 241 creature types around level 5-10. Also found on the auction house."},
    [14089]={name="Beaded Gloves",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 5-14. Also found on the auction house."},
    [14093]={name="Beaded Cord",sourceType="world_drop",instructions="World drop — drops from 314 creature types around level 5-14. Also found on the auction house."},
    [14095]={name="Native Bands",sourceType="world_drop",instructions="World drop — drops from 416 creature types around level 5-14. Also found on the auction house."},
    [14098]={name="Native Cloak",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 5-14. Also found on the auction house."},
    [14099]={name="Native Sash",sourceType="world_drop",instructions="World drop — drops from 435 creature types around level 6-14. Also found on the auction house."},
    [14102]={name="Native Handwraps",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 8-14. Also found on the auction house."},
    [14110]={name="Native Sandals",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 8-14. Also found on the auction house."},
    [14115]={name="Aboriginal Bands",sourceType="world_drop",instructions="World drop — drops from 355 creature types around level 9-15. Also found on the auction house."},
    [15925]={name="Journeyman's Stave",sourceType="world_drop",instructions="World drop — drops from 339 creature types around level 6-14. Also found on the auction house."},
    [15944]={name="Ancestral Orb",sourceType="world_drop",instructions="World drop — drops from 466 creature types around level 6-14. Also found on the auction house."},
    [18957]={name="Brushwood Blade",sourceType="quest_reward",instructions="Reward from the quest “Druid of the Claw” — pick it over the other choices. In Teldrassil.",zone="Teldrassil",questName="Druid of the Claw",lore="After examining this charm, I see now what must be done. Please take it, and do as I ask. You are to explore the deepest areas of the Ban'ethil Barrow Den."},
    [20987]={name="Light Cloth Gloves",sourceType="vendor",instructions="Bought from Jainthess Thelryn in The Sunspire.",zone="The Sunspire",npc="Jainthess Thelryn"},
    [20988]={name="Light Cloth Bracers",sourceType="vendor",instructions="Bought from Jainthess Thelryn in The Sunspire.",zone="The Sunspire",npc="Jainthess Thelryn"},
    [20989]={name="Light Cloth Belt",sourceType="vendor",instructions="Bought from Jainthess Thelryn in The Sunspire.",zone="The Sunspire",npc="Jainthess Thelryn"},
    [20990]={name="Light Cloth Armor",sourceType="vendor",instructions="Bought from Jainthess Thelryn in The Sunspire.",zone="The Sunspire",npc="Jainthess Thelryn"},
    [22784]={name="Sunwell Orb",sourceType="quest_reward",instructions="Reward from the quest “The Twin Ziggurats” — pick it over the other choices. In Ghostlands.",zone="Ghostlands",questName="The Twin Ziggurats",lore="These were imbued with the magical energies of the Sunwell and attuned to have warding powers against the Scourge."},
    [22971]={name="Hoodoo Wand",sourceType="quest_reward",instructions="Reward from the quest “Zul'Marosh” — pick it over the other choices. In Eversong Woods.",zone="Eversong Woods",questName="Zul'Marosh",lore="Come closer, mon. Don't be 'fraid, Ven'jashi not gonna hurt you. Us Darkspears be mortal enemies of the Amani just like you. Their boss Zul'Marosh is evil troll."},
    [23323]={name="Crown of the Fire Festival",sourceType="quest_reward",instructions="Reward from the quest “A Thief's Reward”.",questName="A Thief's Reward",lore="This flame, stolen from the heart of Stormwind itself, floods you with warmth. This raw power is foreign to you, but the (NAME) might know more..."},
    [23324]={name="Mantle of the Fire Festival",sourceType="quest_reward",instructions="Reward from the quest “Wild Fires in the Eastern Kingdoms”.",questName="Wild Fires in the Eastern Kingdoms",lore="Our celebration of the flame is spread throughout the land. Not a single place remains untouched by the heat of this holiday, and the strongest fires burn a brilliant blue."},
    [23402]={name="Arcanist's Dagger",sourceType="quest_reward",instructions="Reward from the quest “Windrunner Village” — pick it over the other choices. In Ghostlands.",zone="Ghostlands",questName="Windrunner Village",lore="the final battle against the Ghostlands villages is upon you. Windrunner Village to the southwest has been overrun by a large force of the more powerful Scourge shocktroopers; shades and gargoyles."},
    [24109]={name="Thick Ravager Belt",sourceType="quest_reward",instructions="Reward from the quest “Beasts of the Apocalypse!” — pick it over the other choices. In Azuremyst Isle.",zone="Azuremyst Isle",questName="Beasts of the Apocalypse!",lore="My brother and I were hunting in the woods to the east when we were ambushed by strange, insect-like beasts. Such aberrations have never before been seen in Azuremyst!"},
    [24112]={name="Kurkenstoks",sourceType="quest_reward",instructions="Reward from the quest “The Kurken's Hide” — pick it over the other choices. In Azuremyst Isle.",zone="Azuremyst Isle",questName="The Kurken's Hide",lore="Take the Kurken's hide to Moordo, on the other side of the village. He will fashion the hide into an item of your choice."},
    [24113]={name="Cowlen's Bracers of Kinship",sourceType="quest_reward",instructions="Reward from the quest “A Cry For Help”. In Azuremyst Isle.",zone="Azuremyst Isle",questName="A Cry For Help",lore="My family was attacked by the murlocs and owlkin of this island several weeks ago. I managed to escape but I think that both my mother and father have been slain."},
    [27403]={name="Stillpine Stinger",sourceType="quest_reward",instructions="Reward from the quest “The Prophecy of Akida” — pick it over the other choices. In Azuremyst Isle.",zone="Azuremyst Isle",questName="The Prophecy of Akida",lore="The images on this totem depict a war between the Stillpine and the Bristlelimb furbolg tribes."},
    [28144]={name="Troll Handler Gloves",sourceType="quest_reward",instructions="Reward from the quest “Report to Captain Helios” — pick it over the other choices. In Ghostlands.",zone="Ghostlands",questName="Report to Captain Helios",lore="I need one last favor of you. Just in case Ranger Salissa didn't make it back to Farstrider Enclave on the south edge of the lake, I need you to go there and get help."},
    [28146]={name="Courier's Wraps",sourceType="quest_reward",instructions="Reward from the quest “Delivery to Tranquillien” — pick it over the other choices. In Ghostlands.",zone="Ghostlands",questName="Delivery to Tranquillien",lore="I... I'm too weak to continue. I carry a dire warning from Regent Lord Theron, in the form of a letter. You'll have to deliver it for me. Take it to Arcanist Vandril in Tranquillien."},
    [28151]={name="Arcanist's Wand",sourceType="quest_reward",instructions="Reward from the quest “Windrunner Village” — pick it over the other choices. In Ghostlands.",zone="Ghostlands",questName="Windrunner Village",lore="the final battle against the Ghostlands villages is upon you. Windrunner Village to the southwest has been overrun by a large force of the more powerful Scourge shocktroopers; shades and gargoyles."},
}

GQ.Data.warlockEarly1to9 = {
    {2570,"Back",1,2,1,0.04,faction="Alliance"},
    {1376,"Back",1,2,2,0.03,faction="Alliance"},
    {1429,"Back",1,2,3,0.03,faction="Alliance"},
    {4658,"Back",3,3,1,0.04,faction="Alliance"},
    {4662,"Back",3,3,2,0.04,faction="Alliance"},
    {4665,"Back",3,3,3,0.04,faction="Alliance"},
    {3008,"Back",4,4,1,0.05,faction="Alliance"},
    {4668,"Back",4,4,2,0.05,faction="Alliance"},
    {4671,"Back",4,4,3,0.05,faction="Alliance"},
    {1421,"Back",5,5,1,0.05,faction="Alliance"},
    {2905,"Back",5,5,2,0.05,faction="Alliance"},
    {6514,"Back",5,5,3,0.05,faction="Alliance"},
    {5591,"Back",6,6,1,0.06,faction="Alliance"},
    {9745,"Back",6,6,2,0.06,faction="Alliance"},
    {9754,"Back",6,6,3,0.06,faction="Alliance"},
    {2580,"Back",7,7,1,0.07,faction="Alliance"},
    {3331,"Back",7,7,2,0.07,faction="Alliance"},
    {4677,"Back",7,7,3,0.07,faction="Alliance"},
    {2310,"Back",8,8,1,0.07,faction="Alliance"},
    {4680,"Back",8,8,2,0.07,faction="Alliance"},
    {4683,"Back",8,8,3,0.07,faction="Alliance"},
    {1497,"Back",9,9,1,0.07,faction="Alliance"},
    {2310,"Back",9,9,2,0.07,faction="Alliance"},
    {4680,"Back",9,9,3,0.07,faction="Alliance"},
    {2121,"Chest",1,1,1,0.06,faction="Alliance"},
    {11189,"Chest",1,1,2,0.06,faction="Alliance"},
    {20990,"Chest",1,1,3,0.06,faction="Alliance"},
    {1433,"Chest",2,2,1,0.08,faction="Alliance"},
    {2121,"Chest",2,2,2,0.06,faction="Alliance"},
    {11189,"Chest",2,2,3,0.06,faction="Alliance"},
    {2114,"Chest",3,3,1,0.09,faction="Alliance"},
    {2568,"Chest",3,3,2,0.09,faction="Alliance"},
    {1433,"Chest",3,3,3,0.08,faction="Alliance"},
    {3328,"Chest",4,4,1,0.1,faction="Alliance"},
    {5767,"Chest",4,4,2,0.1,faction="Alliance"},
    {2114,"Chest",4,4,3,0.09,faction="Alliance"},
    {2572,"Chest",5,5,1,0.56,faction="Alliance"},
    {6241,"Chest",5,5,2,0.56,faction="Alliance"},
    {6238,"Chest",5,5,3,0.46,faction="Alliance"},
    {10553,"Chest",6,6,1,1.33,faction="Alliance"},
    {6511,"Chest",6,6,2,1.03,faction="Alliance"},
    {2957,"Chest",6,6,3,0.83,faction="Alliance"},
    {10553,"Chest",7,7,1,1.33,faction="Alliance"},
    {6511,"Chest",7,7,2,1.03,faction="Alliance"},
    {6239,"Chest",7,7,3,0.84,faction="Alliance"},
    {6266,"Chest",8,9,1,1.37,faction="Alliance",suffix="of Shadow Wrath",suffixChance=2.6,suffixId=1840,suffixRange="+4-6 spShadow"},
    {6512,"Chest",8,9,2,1.37,faction="Alliance",suffix="of Shadow Wrath",suffixChance=2.6,suffixId=1840,suffixRange="+4-6 spShadow"},
    {10553,"Chest",8,9,3,1.33,faction="Alliance"},
    {80,"Feet",1,3,1,0.04,faction="Alliance"},
    {2117,"Feet",1,3,2,0.04,faction="Alliance"},
    {6173,"Feet",1,3,3,0.04,faction="Alliance"},
    {2959,"Feet",4,4,1,0.07,faction="Alliance"},
    {7095,"Feet",4,4,2,0.07,faction="Alliance"},
    {10046,"Feet",4,4,3,0.07,faction="Alliance"},
    {792,"Feet",5,5,1,0.08,faction="Alliance"},
    {6148,"Feet",5,5,2,0.08,faction="Alliance"},
    {14086,"Feet",5,5,3,0.08,faction="Alliance"},
    {3289,"Feet",6,6,1,0.08,faction="Alliance"},
    {7351,"Feet",6,6,2,0.08,faction="Alliance"},
    {792,"Feet",6,6,3,0.08,faction="Alliance"},
    {24112,"Feet",7,7,1,0.28,faction="Alliance"},
    {9743,"Feet",7,7,2,0.09,faction="Alliance"},
    {3289,"Feet",7,7,3,0.08,faction="Alliance"},
    {24112,"Feet",8,8,1,0.28,faction="Alliance"},
    {2569,"Feet",8,8,2,0.1,faction="Alliance"},
    {14110,"Feet",8,8,3,0.1,faction="Alliance"},
    {24112,"Feet",9,9,1,0.28,faction="Alliance"},
    {2971,"Feet",9,9,2,0.1,faction="Alliance"},
    {2569,"Feet",9,9,3,0.1,faction="Alliance"},
    {719,"Hands",1,1,1,0.04,faction="Alliance"},
    {2119,"Hands",1,1,2,0.04,faction="Alliance"},
    {11190,"Hands",1,1,3,0.04,faction="Alliance"},
    {1430,"Hands",2,3,1,0.05,faction="Alliance"},
    {719,"Hands",2,3,2,0.04,faction="Alliance"},
    {2119,"Hands",2,3,3,0.04,faction="Alliance"},
    {2960,"Hands",4,4,1,0.06,faction="Alliance"},
    {5606,"Hands",4,4,2,0.06,faction="Alliance"},
    {1430,"Hands",4,4,3,0.05,faction="Alliance"},
    {793,"Hands",5,5,1,0.07,faction="Alliance"},
    {4307,"Hands",5,5,2,0.07,faction="Alliance"},
    {14089,"Hands",5,5,3,0.07,faction="Alliance"},
    {6202,"Hands",6,6,1,0.07,faction="Alliance"},
    {6515,"Hands",6,6,2,0.07,faction="Alliance"},
    {793,"Hands",6,6,3,0.07,faction="Alliance"},
    {3290,"Hands",7,7,1,0.08,faction="Alliance"},
    {10550,"Hands",7,7,2,0.08,faction="Alliance"},
    {6202,"Hands",7,7,3,0.07,faction="Alliance"},
    {9746,"Hands",8,8,1,0.09,faction="Alliance"},
    {14102,"Hands",8,8,2,0.09,faction="Alliance"},
    {3290,"Hands",8,8,3,0.08,faction="Alliance"},
    {2972,"Hands",9,9,1,0.1,faction="Alliance"},
    {9746,"Hands",9,9,2,0.09,faction="Alliance"},
    {14102,"Hands",9,9,3,0.09,faction="Alliance"},
    {23323,"Head",1,9,1,0.01,faction="Alliance"},
    {10035,"Legs",1,1,1,0.23,faction="Alliance"},
    {79,"Legs",1,1,2,0.05,faction="Alliance"},
    {2120,"Legs",1,1,3,0.05,faction="Alliance"},
    {10035,"Legs",2,2,1,0.23,faction="Alliance"},
    {10045,"Legs",2,2,2,0.07,faction="Alliance"},
    {79,"Legs",2,2,3,0.05,faction="Alliance"},
    {10035,"Legs",3,4,1,0.23,faction="Alliance"},
    {1431,"Legs",3,4,2,0.07,faction="Alliance"},
    {10045,"Legs",3,4,3,0.07,faction="Alliance"},
    {2958,"Legs",5,5,1,0.45,faction="Alliance"},
    {10035,"Legs",5,5,2,0.23,faction="Alliance"},
    {794,"Legs",5,5,3,0.1,faction="Alliance"},
    {10554,"Legs",6,6,1,0.91,faction="Alliance"},
    {2958,"Legs",6,6,2,0.45,faction="Alliance"},
    {10035,"Legs",6,6,3,0.23,faction="Alliance"},
    {10554,"Legs",7,7,1,0.91,faction="Alliance"},
    {10549,"Legs",7,7,2,0.67,faction="Alliance"},
    {2958,"Legs",7,7,3,0.45,faction="Alliance"},
    {3291,"Legs",8,8,1,1.18,faction="Alliance"},
    {10554,"Legs",8,8,2,0.91,faction="Alliance"},
    {10549,"Legs",8,8,3,0.67,faction="Alliance"},
    {4309,"Legs",9,9,1,1.74,faction="Alliance"},
    {3291,"Legs",9,9,2,1.18,faction="Alliance"},
    {10554,"Legs",9,9,3,0.91,faction="Alliance"},
    {1917,"MainHand",5,7,1,0.2,faction="Alliance",route="onehand"},
    {9603,"MainHand",5,7,2,0.2,faction="Alliance",route="onehand"},
    {18957,"MainHand",5,7,3,0.2,faction="Alliance",route="onehand"},
    {6215,"MainHand",8,9,1,0.4,faction="Alliance",route="onehand"},
    {1917,"MainHand",8,9,2,0.2,faction="Alliance",route="onehand"},
    {9603,"MainHand",8,9,3,0.2,faction="Alliance",route="onehand"},
    {11287,"Ranged",5,6,1,5.67,faction="Alliance"},
    {11287,"Ranged",7,7,1,5.67,faction="Alliance"},
    {5069,"Ranged",7,7,2,4.33,faction="Alliance"},
    {11287,"Ranged",8,8,1,5.67,faction="Alliance"},
    {27403,"Ranged",8,8,2,4.74,faction="Alliance"},
    {5604,"Ranged",8,8,3,4.69,faction="Alliance"},
    {11287,"Ranged",9,9,1,5.67,faction="Alliance"},
    {5071,"Ranged",9,9,2,5.18,faction="Alliance"},
    {27403,"Ranged",9,9,3,4.74,faction="Alliance"},
    {15925,"SecondaryHand",5,6,1,0.2,faction="Alliance",route="onehand"},
    {15944,"SecondaryHand",7,9,1,0.45,faction="Alliance",route="onehand"},
    {15925,"SecondaryHand",7,9,2,0.2,faction="Alliance",route="onehand"},
    {23324,"Shoulder",1,9,1,0.01,faction="Alliance"},
    {3599,"Waist",1,2,1,0.04,faction="Alliance"},
    {20989,"Waist",1,2,2,0.04,faction="Alliance"},
    {3363,"Waist",1,2,3,0.02,faction="Alliance"},
    {3370,"Waist",3,3,1,0.05,faction="Alliance"},
    {3599,"Waist",3,3,2,0.04,faction="Alliance"},
    {20989,"Waist",3,3,3,0.04,faction="Alliance"},
    {983,"Waist",4,4,1,0.05,faction="Alliance"},
    {4663,"Waist",4,4,2,0.05,faction="Alliance"},
    {7026,"Waist",4,4,3,0.05,faction="Alliance"},
    {3602,"Waist",5,6,1,0.06,faction="Alliance"},
    {4672,"Waist",5,6,2,0.06,faction="Alliance"},
    {5458,"Waist",5,6,3,0.06,faction="Alliance"},
    {24109,"Waist",7,7,1,0.52,faction="Alliance"},
    {9742,"Waist",7,7,2,0.07,faction="Alliance"},
    {14099,"Waist",7,7,3,0.07,faction="Alliance"},
    {24109,"Waist",8,8,1,0.52,faction="Alliance"},
    {4684,"Waist",8,8,2,0.08,faction="Alliance"},
    {9742,"Waist",8,8,3,0.07,faction="Alliance"},
    {24109,"Waist",9,9,1,0.52,faction="Alliance"},
    {4687,"Waist",9,9,2,0.08,faction="Alliance"},
    {3374,"Waist",9,9,3,0.08,faction="Alliance"},
    {3365,"Wrist",1,2,1,0.02,faction="Alliance"},
    {3600,"Wrist",1,2,2,0.02,faction="Alliance"},
    {11187,"Wrist",1,2,3,0.02,faction="Alliance"},
    {3323,"Wrist",3,3,1,0.04,faction="Alliance"},
    {3641,"Wrist",3,3,2,0.04,faction="Alliance"},
    {14087,"Wrist",3,3,3,0.04,faction="Alliance"},
    {3323,"Wrist",4,4,1,0.04,faction="Alliance"},
    {3373,"Wrist",4,4,2,0.04,faction="Alliance"},
    {3641,"Wrist",4,4,3,0.04,faction="Alliance"},
    {2326,"Wrist",5,5,1,0.05,faction="Alliance"},
    {3224,"Wrist",5,5,2,0.05,faction="Alliance"},
    {3603,"Wrist",5,5,3,0.05,faction="Alliance"},
    {24113,"Wrist",6,6,1,0.25,faction="Alliance"},
    {14095,"Wrist",6,6,2,0.05,faction="Alliance"},
    {2326,"Wrist",6,6,3,0.05,faction="Alliance"},
    {24113,"Wrist",7,8,1,0.25,faction="Alliance"},
    {3375,"Wrist",7,8,2,0.05,faction="Alliance"},
    {3644,"Wrist",7,8,3,0.05,faction="Alliance"},
    {24113,"Wrist",9,9,1,0.25,faction="Alliance"},
    {710,"Wrist",9,9,2,0.07,faction="Alliance"},
    {3643,"Wrist",9,9,3,0.07,faction="Alliance"},
    {2570,"Back",1,2,1,0.04,faction="Horde"},
    {3322,"Back",1,2,2,0.04,faction="Horde"},
    {1376,"Back",1,2,3,0.03,faction="Horde"},
    {4658,"Back",3,3,1,0.04,faction="Horde"},
    {4662,"Back",3,3,2,0.04,faction="Horde"},
    {4665,"Back",3,3,3,0.04,faction="Horde"},
    {4668,"Back",4,4,1,0.05,faction="Horde"},
    {4671,"Back",4,4,2,0.05,faction="Horde"},
    {4674,"Back",4,4,3,0.05,faction="Horde"},
    {1421,"Back",5,5,1,0.05,faction="Horde"},
    {6514,"Back",5,5,2,0.05,faction="Horde"},
    {14098,"Back",5,5,3,0.05,faction="Horde"},
    {4772,"Back",6,6,1,0.06,faction="Horde"},
    {4854,"Back",6,6,2,0.06,faction="Horde"},
    {9745,"Back",6,6,3,0.06,faction="Horde"},
    {2580,"Back",7,7,1,0.07,faction="Horde"},
    {3331,"Back",7,7,2,0.07,faction="Horde"},
    {4677,"Back",7,7,3,0.07,faction="Horde"},
    {2310,"Back",8,8,1,0.07,faction="Horde"},
    {4680,"Back",8,8,2,0.07,faction="Horde"},
    {4683,"Back",8,8,3,0.07,faction="Horde"},
    {1497,"Back",9,9,1,0.07,faction="Horde"},
    {2310,"Back",9,9,2,0.07,faction="Horde"},
    {4680,"Back",9,9,3,0.07,faction="Horde"},
    {193,"Chest",1,1,1,0.06,faction="Horde"},
    {4916,"Chest",1,1,2,0.06,faction="Horde"},
    {20990,"Chest",1,1,3,0.06,faction="Horde"},
    {1433,"Chest",2,2,1,0.08,faction="Horde"},
    {193,"Chest",2,2,2,0.06,faction="Horde"},
    {3270,"Chest",2,2,3,0.06,faction="Horde"},
    {2114,"Chest",3,3,1,0.09,faction="Horde"},
    {2568,"Chest",3,3,2,0.09,faction="Horde"},
    {2612,"Chest",3,3,3,0.09,faction="Horde"},
    {3328,"Chest",4,4,1,0.1,faction="Horde"},
    {2114,"Chest",4,4,2,0.09,faction="Horde"},
    {2568,"Chest",4,4,3,0.09,faction="Horde"},
    {2572,"Chest",5,5,1,0.56,faction="Horde"},
    {6241,"Chest",5,5,2,0.56,faction="Horde"},
    {6238,"Chest",5,5,3,0.46,faction="Horde"},
    {10553,"Chest",6,6,1,1.33,faction="Horde"},
    {6511,"Chest",6,6,2,1.03,faction="Horde"},
    {2957,"Chest",6,6,3,0.83,faction="Horde"},
    {10553,"Chest",7,7,1,1.33,faction="Horde"},
    {6511,"Chest",7,7,2,1.03,faction="Horde"},
    {6239,"Chest",7,7,3,0.84,faction="Horde"},
    {6266,"Chest",8,9,1,1.37,faction="Horde",suffix="of Shadow Wrath",suffixChance=2.6,suffixId=1840,suffixRange="+4-6 spShadow"},
    {6512,"Chest",8,9,2,1.37,faction="Horde",suffix="of Shadow Wrath",suffixChance=2.6,suffixId=1840,suffixRange="+4-6 spShadow"},
    {10553,"Chest",8,9,3,1.33,faction="Horde"},
    {195,"Feet",1,2,1,0.04,faction="Horde"},
    {3274,"Feet",1,2,2,0.04,faction="Horde"},
    {4915,"Feet",1,2,3,0.04,faction="Horde"},
    {4936,"Feet",3,3,1,0.06,faction="Horde"},
    {195,"Feet",3,3,2,0.04,faction="Horde"},
    {3274,"Feet",3,3,3,0.04,faction="Horde"},
    {2959,"Feet",4,4,1,0.07,faction="Horde"},
    {10046,"Feet",4,4,2,0.07,faction="Horde"},
    {4936,"Feet",4,4,3,0.06,faction="Horde"},
    {792,"Feet",5,5,1,0.08,faction="Horde"},
    {2367,"Feet",5,5,2,0.08,faction="Horde"},
    {14086,"Feet",5,5,3,0.08,faction="Horde"},
    {3289,"Feet",6,6,1,0.08,faction="Horde"},
    {7351,"Feet",6,6,2,0.08,faction="Horde"},
    {792,"Feet",6,6,3,0.08,faction="Horde"},
    {9743,"Feet",7,7,1,0.09,faction="Horde"},
    {3289,"Feet",7,7,2,0.08,faction="Horde"},
    {7351,"Feet",7,7,3,0.08,faction="Horde"},
    {2569,"Feet",8,8,1,0.1,faction="Horde"},
    {14110,"Feet",8,8,2,0.1,faction="Horde"},
    {1495,"Feet",8,8,3,0.09,faction="Horde"},
    {2971,"Feet",9,9,1,0.1,faction="Horde"},
    {2569,"Feet",9,9,2,0.1,faction="Horde"},
    {14110,"Feet",9,9,3,0.1,faction="Horde"},
    {711,"Hands",1,1,1,0.04,faction="Horde"},
    {3275,"Hands",1,1,2,0.04,faction="Horde"},
    {20987,"Hands",1,1,3,0.04,faction="Horde"},
    {1430,"Hands",2,3,1,0.05,faction="Horde"},
    {711,"Hands",2,3,2,0.04,faction="Horde"},
    {3275,"Hands",2,3,3,0.04,faction="Horde"},
    {2960,"Hands",4,4,1,0.06,faction="Horde"},
    {1430,"Hands",4,4,2,0.05,faction="Horde"},
    {711,"Hands",4,4,3,0.04,faction="Horde"},
    {793,"Hands",5,5,1,0.07,faction="Horde"},
    {2369,"Hands",5,5,2,0.07,faction="Horde"},
    {4307,"Hands",5,5,3,0.07,faction="Horde"},
    {6515,"Hands",6,6,1,0.07,faction="Horde"},
    {793,"Hands",6,6,2,0.07,faction="Horde"},
    {2369,"Hands",6,6,3,0.07,faction="Horde"},
    {3290,"Hands",7,7,1,0.08,faction="Horde"},
    {6515,"Hands",7,7,2,0.07,faction="Horde"},
    {793,"Hands",7,7,3,0.07,faction="Horde"},
    {9746,"Hands",8,8,1,0.09,faction="Horde"},
    {14102,"Hands",8,8,2,0.09,faction="Horde"},
    {3290,"Hands",8,8,3,0.08,faction="Horde"},
    {28144,"Hands",9,9,1,0.88,faction="Horde"},
    {2972,"Hands",9,9,2,0.1,faction="Horde"},
    {9746,"Hands",9,9,3,0.09,faction="Horde"},
    {23323,"Head",1,9,1,0.01,faction="Horde"},
    {10035,"Legs",1,1,1,0.23,faction="Horde"},
    {194,"Legs",1,1,2,0.05,faction="Horde"},
    {6713,"Legs",1,1,3,0.05,faction="Horde"},
    {10035,"Legs",2,2,1,0.23,faction="Horde"},
    {10045,"Legs",2,2,2,0.07,faction="Horde"},
    {194,"Legs",2,2,3,0.05,faction="Horde"},
    {10035,"Legs",3,4,1,0.23,faction="Horde"},
    {4261,"Legs",3,4,2,0.08,faction="Horde"},
    {1431,"Legs",3,4,3,0.07,faction="Horde"},
    {2958,"Legs",5,5,1,0.45,faction="Horde"},
    {10035,"Legs",5,5,2,0.23,faction="Horde"},
    {794,"Legs",5,5,3,0.1,faction="Horde"},
    {10554,"Legs",6,7,1,0.91,faction="Horde"},
    {2958,"Legs",6,7,2,0.45,faction="Horde"},
    {10035,"Legs",6,7,3,0.23,faction="Horde"},
    {3291,"Legs",8,8,1,1.18,faction="Horde"},
    {10554,"Legs",8,8,2,0.91,faction="Horde"},
    {2958,"Legs",8,8,3,0.45,faction="Horde"},
    {4309,"Legs",9,9,1,1.74,faction="Horde"},
    {3291,"Legs",9,9,2,1.18,faction="Horde"},
    {10554,"Legs",9,9,3,0.91,faction="Horde"},
    {1917,"MainHand",5,7,1,0.2,faction="Horde",route="onehand"},
    {3446,"MainHand",8,8,1,0.6,faction="Horde",route="onehand"},
    {1917,"MainHand",8,8,2,0.2,faction="Horde",route="onehand"},
    {3446,"MainHand",9,9,1,0.6,faction="Horde",route="onehand"},
    {23402,"MainHand",9,9,2,0.45,faction="Horde",route="onehand"},
    {1917,"MainHand",9,9,3,0.2,faction="Horde",route="onehand"},
    {11287,"Ranged",5,6,1,5.67,faction="Horde"},
    {11287,"Ranged",7,7,1,5.67,faction="Horde"},
    {5069,"Ranged",7,7,2,4.33,faction="Horde"},
    {11287,"Ranged",8,8,1,5.67,faction="Horde"},
    {5069,"Ranged",8,8,2,4.33,faction="Horde"},
    {22971,"Ranged",8,8,3,4.07,faction="Horde"},
    {11287,"Ranged",9,9,1,5.67,faction="Horde"},
    {28151,"Ranged",9,9,2,5.61,faction="Horde"},
    {5071,"Ranged",9,9,3,5.18,faction="Horde"},
    {22784,"SecondaryHand",1,4,1,1.35,faction="Horde"},
    {22784,"SecondaryHand",5,6,1,1.35,faction="Horde",route="onehand"},
    {15925,"SecondaryHand",5,6,2,0.2,faction="Horde",route="onehand"},
    {22784,"SecondaryHand",7,9,1,1.35,faction="Horde",route="onehand"},
    {15944,"SecondaryHand",7,9,2,0.45,faction="Horde",route="onehand"},
    {15925,"SecondaryHand",7,9,3,0.2,faction="Horde",route="onehand"},
    {23324,"Shoulder",1,9,1,0.01,faction="Horde"},
    {3595,"Waist",1,1,1,0.04,faction="Horde"},
    {4919,"Waist",1,1,2,0.04,faction="Horde"},
    {20989,"Waist",1,1,3,0.04,faction="Horde"},
    {3595,"Waist",2,2,1,0.04,faction="Horde"},
    {4919,"Waist",2,2,2,0.04,faction="Horde"},
    {11848,"Waist",2,2,3,0.04,faction="Horde"},
    {3370,"Waist",3,3,1,0.05,faction="Horde"},
    {3595,"Waist",3,3,2,0.04,faction="Horde"},
    {4919,"Waist",3,3,3,0.04,faction="Horde"},
    {4663,"Waist",4,4,1,0.05,faction="Horde"},
    {7026,"Waist",4,4,2,0.05,faction="Horde"},
    {14093,"Waist",4,4,3,0.05,faction="Horde"},
    {3602,"Waist",5,6,1,0.06,faction="Horde"},
    {3606,"Waist",5,6,2,0.06,faction="Horde"},
    {4672,"Waist",5,6,3,0.06,faction="Horde"},
    {3442,"Waist",7,7,1,0.07,faction="Horde"},
    {9742,"Waist",7,7,2,0.07,faction="Horde"},
    {14099,"Waist",7,7,3,0.07,faction="Horde"},
    {4684,"Waist",8,8,1,0.08,faction="Horde"},
    {3442,"Waist",8,8,2,0.07,faction="Horde"},
    {9742,"Waist",8,8,3,0.07,faction="Horde"},
    {4687,"Waist",9,9,1,0.08,faction="Horde"},
    {3374,"Waist",9,9,2,0.08,faction="Horde"},
    {4684,"Waist",9,9,3,0.08,faction="Horde"},
    {3365,"Wrist",1,1,1,0.02,faction="Horde"},
    {3596,"Wrist",1,1,2,0.02,faction="Horde"},
    {20988,"Wrist",1,1,3,0.02,faction="Horde"},
    {3365,"Wrist",2,2,1,0.02,faction="Horde"},
    {3596,"Wrist",2,2,2,0.02,faction="Horde"},
    {6060,"Wrist",2,2,3,0.02,faction="Horde"},
    {3323,"Wrist",3,3,1,0.04,faction="Horde"},
    {3641,"Wrist",3,3,2,0.04,faction="Horde"},
    {14087,"Wrist",3,3,3,0.04,faction="Horde"},
    {3323,"Wrist",4,4,1,0.04,faction="Horde"},
    {3373,"Wrist",4,4,2,0.04,faction="Horde"},
    {3641,"Wrist",4,4,3,0.04,faction="Horde"},
    {3224,"Wrist",5,5,1,0.05,faction="Horde"},
    {3603,"Wrist",5,5,2,0.05,faction="Horde"},
    {3607,"Wrist",5,5,3,0.05,faction="Horde"},
    {14095,"Wrist",6,6,1,0.05,faction="Horde"},
    {3224,"Wrist",6,6,2,0.05,faction="Horde"},
    {3603,"Wrist",6,6,3,0.05,faction="Horde"},
    {3375,"Wrist",7,8,1,0.05,faction="Horde"},
    {3644,"Wrist",7,8,2,0.05,faction="Horde"},
    {4308,"Wrist",7,8,3,0.05,faction="Horde"},
    {28146,"Wrist",9,9,1,0.5,faction="Horde"},
    {3643,"Wrist",9,9,2,0.07,faction="Horde"},
    {14115,"Wrist",9,9,3,0.07,faction="Horde"},
}
