local _, GQ = ...
GQ.Data = GQ.Data or {}

-- GENERATED -- Warrior, HORDE only, levels 1-9. Nothing else is in this file:
-- no Alliance rows and no level 10 or above, so it can sit next to the
-- hand-made Alliance 1-9 data without either overwriting the other.
--
-- The race filter is the class's own playable races for that faction, not the whole
-- faction: a Horde warrior can be Orc, Undead, Tauren or Troll but never a Blood Elf,
-- so Blood Elf starting quests are gated out. Quests are gated on quest_template.RequiredRaces, and
-- faction-exclusive zones are gated by name -- a vendor standing in Darnassus is
-- not race-restricted, the city is.
--
-- No spec column. Warriors have no talents before level 10, so one list serves all
-- three specs across this range.
--
-- row = { itemId, slot, minLevel, maxLevel, rank, score }
--   optional: suffix, suffixChance  (random-enchantment items -- score assumes the
--   best roll, and suffixChance is the odds of getting any roll of that suffix)

GQ.Data.warriorHorde1to9Facts = {
    [1200]={name="Large Wooden Shield",sourceType="vendor",instructions="Bought from Winthren in Silvermoon City.",zone="Silvermoon City",npc="Winthren"},
    [1376]={name="Frayed Cloak",sourceType="world_drop",instructions="World drop — drops from 62 creature types around level 1-5. Also found on the auction house."},
    [1421]={name="Worn Hide Cloak",sourceType="world_drop",instructions="World drop — drops from 236 creature types around level 1-10. Also found on the auction house."},
    [1438]={name="Warrior's Shield",sourceType="world_drop",instructions="World drop — drops from 314 creature types around level 5-14. Also found on the auction house."},
    [1497]={name="Calico Cloak",sourceType="world_drop",instructions="World drop — drops from 242 creature types around level 9-15. Also found on the auction house."},
    [1730]={name="Worn Mail Belt",sourceType="world_drop",instructions="World drop — drops from 242 creature types around level 9-15. Also found on the auction house."},
    [1731]={name="Worn Mail Boots",sourceType="world_drop",instructions="World drop — drops from 242 creature types around level 9-15. Also found on the auction house."},
    [1732]={name="Worn Mail Bracers",sourceType="world_drop",instructions="World drop — drops from 242 creature types around level 9-15. Also found on the auction house."},
    [1734]={name="Worn Mail Gloves",sourceType="world_drop",instructions="World drop — drops from 242 creature types around level 9-15. Also found on the auction house."},
    [2067]={name="Frostbit Staff",sourceType="world_drop",instructions="Drops from Rockjaw Bonesnapper in Eastern Kingdoms.",zone="Eastern Kingdoms",npc="Rockjaw Bonesnapper"},
    [2212]={name="Cracked Buckler",sourceType="world_drop",instructions="World drop — drops from 236 creature types around level 1-10. Also found on the auction house."},
    [2213]={name="Worn Large Shield",sourceType="world_drop",instructions="World drop — drops from 236 creature types around level 1-10. Also found on the auction house."},
    [2215]={name="Wooden Shield",sourceType="world_drop",instructions="World drop — drops from 242 creature types around level 9-15. Also found on the auction house."},
    [2254]={name="Icepane Warhammer",sourceType="world_drop",instructions="Drops from Hammerspine (rare spawn) in Eastern Kingdoms.",zone="Eastern Kingdoms",npc="Hammerspine"},
    [2310]={name="Embossed Leather Cloak",sourceType="profession",instructions="Crafted with Leatherworking (requires skill 65).",profession="Leatherworking"},
    [2376]={name="Worn Heater Shield",sourceType="vendor",instructions="Bought from Sana in Orgrimmar.",zone="Orgrimmar",npc="Sana"},
    [2386]={name="Rusted Chain Vest",sourceType="vendor",instructions="Bought from Timothy Weldon in Undercity.",zone="Undercity",npc="Timothy Weldon"},
    [2387]={name="Rusted Chain Belt",sourceType="vendor",instructions="Bought from Timothy Weldon in Undercity.",zone="Undercity",npc="Timothy Weldon"},
    [2388]={name="Rusted Chain Leggings",sourceType="vendor",instructions="Bought from Timothy Weldon in Undercity.",zone="Undercity",npc="Timothy Weldon"},
    [2389]={name="Rusted Chain Boots",sourceType="vendor",instructions="Bought from Timothy Weldon in Undercity.",zone="Undercity",npc="Timothy Weldon"},
    [2390]={name="Rusted Chain Bracers",sourceType="vendor",instructions="Bought from Timothy Weldon in Undercity.",zone="Undercity",npc="Timothy Weldon"},
    [2391]={name="Rusted Chain Gloves",sourceType="vendor",instructions="Bought from Timothy Weldon in Undercity.",zone="Undercity",npc="Timothy Weldon"},
    [2399]={name="Light Chain Belt",sourceType="vendor",instructions="Bought from Abe Winters in Brill.",zone="Brill",npc="Abe Winters"},
    [2400]={name="Light Chain Leggings",sourceType="vendor",instructions="Bought from Abe Winters in Brill.",zone="Brill",npc="Abe Winters"},
    [2401]={name="Light Chain Boots",sourceType="vendor",instructions="Bought from Abe Winters in Brill.",zone="Brill",npc="Abe Winters"},
    [2402]={name="Light Chain Bracers",sourceType="vendor",instructions="Bought from Abe Winters in Brill.",zone="Brill",npc="Abe Winters"},
    [2403]={name="Light Chain Gloves",sourceType="vendor",instructions="Bought from Abe Winters in Brill.",zone="Brill",npc="Abe Winters"},
    [2489]={name="Two-handed Sword",sourceType="world_drop",instructions="Drops from Hillsbrad Apprentice Blacksmith in Eastern Kingdoms.",zone="Eastern Kingdoms",npc="Hillsbrad Apprentice Blacksmith"},
    [2491]={name="Large Axe",sourceType="world_drop",instructions="Drops from Hillsbrad Apprentice Blacksmith in Eastern Kingdoms.",zone="Eastern Kingdoms",npc="Hillsbrad Apprentice Blacksmith"},
    [2493]={name="Wooden Mallet",sourceType="world_drop",instructions="Drops from Hillsbrad Apprentice Blacksmith in Eastern Kingdoms.",zone="Eastern Kingdoms",npc="Hillsbrad Apprentice Blacksmith"},
    [2505]={name="Polished Shortbow",sourceType="vendor",instructions="Bought from Beega in Blood Watch.",zone="Blood Watch",npc="Beega"},
    [2506]={name="Hornwood Recurve Bow",sourceType="vendor",instructions="Bought from Beega in Blood Watch.",zone="Blood Watch",npc="Beega"},
    [2509]={name="Ornate Blunderbuss",sourceType="vendor",instructions="Bought from Jyn Stonehoof in Thunder Bluff.",zone="Thunder Bluff",npc="Jyn Stonehoof"},
    [2511]={name="Hunter's Boomstick",sourceType="vendor",instructions="Bought from Jyn Stonehoof in Thunder Bluff.",zone="Thunder Bluff",npc="Jyn Stonehoof"},
    [2546]={name="Royal Frostmane Girdle",sourceType="world_drop",instructions="Drops from Great Father Arctikus (rare spawn) in Brewnall Village.",zone="Brewnall Village",npc="Great Father Arctikus"},
    [2570]={name="Linen Cloak",sourceType="profession",instructions="Crafted with Tailoring (requires skill 1).",profession="Tailoring"},
    [2580]={name="Reinforced Linen Cape",sourceType="profession",instructions="Crafted with Tailoring (requires skill 1).",profession="Tailoring"},
    [2635]={name="Loose Chain Belt",sourceType="world_drop",instructions="World drop — drops from 236 creature types around level 1-10. Also found on the auction house."},
    [2642]={name="Loose Chain Boots",sourceType="world_drop",instructions="World drop — drops from 236 creature types around level 1-10. Also found on the auction house."},
    [2643]={name="Loose Chain Bracers",sourceType="world_drop",instructions="World drop — drops from 236 creature types around level 1-10. Also found on the auction house."},
    [2645]={name="Loose Chain Gloves",sourceType="world_drop",instructions="World drop — drops from 236 creature types around level 1-10. Also found on the auction house."},
    [2646]={name="Loose Chain Pants",sourceType="world_drop",instructions="World drop — drops from 236 creature types around level 1-10. Also found on the auction house."},
    [2648]={name="Loose Chain Vest",sourceType="world_drop",instructions="World drop — drops from 236 creature types around level 1-10. Also found on the auction house."},
    [2650]={name="Flimsy Chain Boots",sourceType="world_drop",instructions="World drop — drops from 62 creature types around level 1-5. Also found on the auction house."},
    [2651]={name="Flimsy Chain Bracers",sourceType="world_drop",instructions="World drop — drops from 62 creature types around level 1-5. Also found on the auction house."},
    [2851]={name="Copper Chain Belt",sourceType="profession",instructions="Crafted with Blacksmithing (requires skill 55).",profession="Blacksmithing"},
    [2852]={name="Copper Chain Pants",sourceType="profession",instructions="Crafted with Blacksmithing (requires skill 40).",profession="Blacksmithing"},
    [2853]={name="Copper Bracers",sourceType="profession",instructions="Crafted with Blacksmithing (requires skill 1).",profession="Blacksmithing"},
    [2965]={name="Warrior's Tunic",sourceType="world_drop",instructions="World drop — drops from 401 creature types around level 6-14. Also found on the auction house."},
    [2966]={name="Warrior's Pants",sourceType="world_drop",instructions="World drop — drops from 339 creature types around level 6-14. Also found on the auction house."},
    [2967]={name="Warrior's Boots",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 5-14. Also found on the auction house."},
    [2968]={name="Warrior's Gloves",sourceType="world_drop",instructions="World drop — drops from 314 creature types around level 5-14. Also found on the auction house."},
    [2979]={name="Veteran Boots",sourceType="world_drop",instructions="World drop — drops from 355 creature types around level 9-15. Also found on the auction house."},
    [3079]={name="Skorn's Rifle",sourceType="quest_reward",instructions="Reward from the quest “The Demon Scarred Cloak” — pick it over the other choices. In Mulgore.",zone="Mulgore",questName="The Demon Scarred Cloak",lore="The ragged hide of Ghost Howl still bears a terrible wound, gained from the wolf's battles against the Burning Legion. Perhaps someone in Bloodhoof Village should know of Ghost Howl's demise...."},
    [3189]={name="Wood Chopper",sourceType="world_drop",instructions="World drop — drops from 241 creature types around level 5-10. Also found on the auction house."},
    [3190]={name="Beatstick",sourceType="world_drop",instructions="World drop — drops from 241 creature types around level 5-10. Also found on the auction house."},
    [3192]={name="Short Bastard Sword",sourceType="world_drop",instructions="World drop — drops from 466 creature types around level 6-14. Also found on the auction house."},
    [3213]={name="Veteran Bracers",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 8-14. Also found on the auction house."},
    [3214]={name="Warrior's Bracers",sourceType="world_drop",instructions="World drop — drops from 314 creature types around level 5-14. Also found on the auction house."},
    [3273]={name="Rugged Mail Vest",sourceType="quest_reward",instructions="Reward from the quest “Night Web's Hollow” — pick it over the other choices. In Deathknell.",zone="Deathknell",questName="Night Web's Hollow",lore="One of our greatest struggles is obtaining the natural resources we need to survive. Gold was scarce even in the height of the Alliance's power."},
    [3279]={name="Battle Chain Boots",sourceType="world_drop",instructions="World drop — drops from 435 creature types around level 6-14. Also found on the auction house."},
    [3280]={name="Battle Chain Bracers",sourceType="world_drop",instructions="World drop — drops from 314 creature types around level 5-14. Also found on the auction house."},
    [3281]={name="Battle Chain Gloves",sourceType="world_drop",instructions="World drop — drops from 416 creature types around level 5-14. Also found on the auction house."},
    [3282]={name="Battle Chain Pants",sourceType="world_drop",instructions="World drop — drops from 466 creature types around level 6-14. Also found on the auction house."},
    [3283]={name="Battle Chain Tunic",sourceType="world_drop",instructions="World drop — drops from 380 creature types around level 8-14. Also found on the auction house."},
    [3303]={name="Brackwater Bracers",sourceType="world_drop",instructions="World drop — drops from 435 creature types around level 6-14. Also found on the auction house."},
    [3304]={name="Brackwater Gauntlets",sourceType="world_drop",instructions="World drop — drops from 355 creature types around level 9-15. Also found on the auction house."},
    [3322]={name="Wispy Cloak",sourceType="world_drop",instructions="Drops from Lost Soul (rare spawn) in Brill.",zone="Brill",npc="Lost Soul"},
    [3325]={name="Vile Fin Battle Axe",sourceType="world_drop",instructions="Drops from Vile Fin Muckdweller in Eastern Kingdoms.",zone="Eastern Kingdoms",npc="Vile Fin Muckdweller"},
    [3327]={name="Vile Fin Oracle Staff",sourceType="world_drop",instructions="Drops from Vile Fin Minor Oracle in Eastern Kingdoms.",zone="Eastern Kingdoms",npc="Vile Fin Minor Oracle"},
    [3330]={name="Dargol's Hauberk",sourceType="world_drop",instructions="Drops from Captain Dargol in Eastern Kingdoms.",zone="Eastern Kingdoms",npc="Captain Dargol"},
    [3331]={name="Melrache's Cape",sourceType="world_drop",instructions="Drops from Captain Melrache in Scarlet Monastery.",zone="Scarlet Monastery",npc="Captain Melrache"},
    [3332]={name="Perrine's Boots",sourceType="world_drop",instructions="Drops from Captain Perrine in Undercity.",zone="Undercity",npc="Captain Perrine"},
    [3334]={name="Farmer's Shovel",sourceType="world_drop",instructions="Drops from Farmer Solliden (rare spawn) in Deathknell.",zone="Deathknell",npc="Farmer Solliden"},
    [3440]={name="Bonecracker",sourceType="quest_reward",instructions="Reward from the quest “The Family Crypt” — pick it over the other choices. In Tirisfal Glades.",zone="Tirisfal Glades",questName="The Family Crypt",lore="The Agamand Mills area has become a foothold for the Scourge. Their strongest point is the Agamand Family Crypt where their local military leader, a skeleton named Captain Dargol, has headquartered."},
    [3446]={name="Darkwood Staff",sourceType="quest_reward",instructions="Reward from the quest “The Family Crypt” — pick it over the other choices. In Tirisfal Glades.",zone="Tirisfal Glades",questName="The Family Crypt",lore="The Agamand Mills area has become a foothold for the Scourge. Their strongest point is the Agamand Family Crypt where their local military leader, a skeleton named Captain Dargol, has headquartered."},
    [3469]={name="Copper Chain Boots",sourceType="profession",instructions="Crafted with Blacksmithing (requires skill 1).",profession="Blacksmithing"},
    [3471]={name="Copper Chain Vest",sourceType="profession",instructions="Crafted with Blacksmithing (requires skill 1).",profession="Blacksmithing"},
    [3472]={name="Runed Copper Gauntlets",sourceType="profession",instructions="Crafted with Blacksmithing (requires skill 1).",profession="Blacksmithing"},
    [3473]={name="Runed Copper Pants",sourceType="profession",instructions="Crafted with Blacksmithing (requires skill 1).",profession="Blacksmithing"},
    [3488]={name="Copper Battle Axe",sourceType="profession",instructions="Crafted with Blacksmithing (requires skill 1).",profession="Blacksmithing"},
    [3649]={name="Tribal Buckler",sourceType="world_drop",instructions="World drop — drops from 416 creature types around level 5-14. Also found on the auction house."},
    [3650]={name="Battle Shield",sourceType="world_drop",instructions="World drop — drops from 314 creature types around level 5-14. Also found on the auction house."},
    [3652]={name="Hunting Buckler",sourceType="world_drop",instructions="World drop — drops from 359 creature types around level 9-15. Also found on the auction house."},
    [3654]={name="Brackwater Shield",sourceType="world_drop",instructions="World drop — drops from 359 creature types around level 9-15. Also found on the auction house."},
    [4263]={name="Standard Issue Shield",sourceType="world_drop",instructions="Drops from Scarlet Bodyguard in Scarlet Monastery.",zone="Scarlet Monastery",npc="Scarlet Bodyguard"},
    [4362]={name="Rough Boomstick",sourceType="profession",instructions="Crafted with Engineering (requires skill 1).",profession="Engineering"},
    [4562]={name="Severing Axe",sourceType="world_drop",instructions="World drop — drops from 339 creature types around level 6-14. Also found on the auction house."},
    [4577]={name="Compact Shotgun",sourceType="world_drop",instructions="World drop — drops from 380 creature types around level 8-14. Also found on the auction house."},
    [4658]={name="Warrior's Cloak",sourceType="world_drop",instructions="World drop — drops from 241 creature types around level 5-10. Also found on the auction house."},
    [4659]={name="Warrior's Girdle",sourceType="world_drop",instructions="World drop — drops from 241 creature types around level 5-10. Also found on the auction house."},
    [4662]={name="Journeyman's Cloak",sourceType="world_drop",instructions="World drop — drops from 241 creature types around level 5-10. Also found on the auction house."},
    [4665]={name="Burnt Cloak",sourceType="world_drop",instructions="World drop — drops from 241 creature types around level 5-10. Also found on the auction house."},
    [4668]={name="Battle Chain Cloak",sourceType="world_drop",instructions="World drop — drops from 314 creature types around level 5-14. Also found on the auction house."},
    [4669]={name="Battle Chain Girdle",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 5-14. Also found on the auction house."},
    [4671]={name="Ancestral Cloak",sourceType="world_drop",instructions="World drop — drops from 314 creature types around level 5-14. Also found on the auction house."},
    [4674]={name="Tribal Cloak",sourceType="world_drop",instructions="World drop — drops from 314 creature types around level 5-14. Also found on the auction house."},
    [4677]={name="Veteran Cloak",sourceType="world_drop",instructions="World drop — drops from 435 creature types around level 6-14. Also found on the auction house."},
    [4678]={name="Veteran Girdle",sourceType="world_drop",instructions="World drop — drops from 355 creature types around level 9-15. Also found on the auction house."},
    [4680]={name="Brackwater Cloak",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 8-14. Also found on the auction house."},
    [4681]={name="Brackwater Girdle",sourceType="world_drop",instructions="World drop — drops from 355 creature types around level 9-15. Also found on the auction house."},
    [4683]={name="Spellbinder Cloak",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 8-14. Also found on the auction house."},
    [4772]={name="Warm Cloak",sourceType="world_drop",instructions="Drops from Sister Hatelash (rare spawn) in Thunder Bluff.",zone="Thunder Bluff",npc="Sister Hatelash"},
    [4854]={name="Demon Scarred Cloak",sourceType="world_drop",instructions="Drops from Ghost Howl (rare spawn) in Thunder Bluff.",zone="Thunder Bluff",npc="Ghost Howl"},
    [4910]={name="Painted Chain Gloves",sourceType="quest_reward",instructions="Reward from the quest “The Hunt Begins” — pick it over the other choices. In Red Cloud Mesa.",zone="Red Cloud Mesa",questName="The Hunt Begins",lore="You have a promising air about you, and will prove yourself to the tribe. Perhaps someday soon you will be welcomed into the great city of Thunder Bluff."},
    [4911]={name="Thick Bark Buckler",sourceType="quest_reward",instructions="Reward from the quest “Attack on Camp Narache”. In Red Cloud Mesa.",zone="Red Cloud Mesa",questName="Attack on Camp Narache",lore="After carefully evaluating the map, you realize that what you discovered are the plans made by the Bristleback warchief for an extended siege on Camp Narache."},
    [4913]={name="Painted Chain Belt",sourceType="quest_reward",instructions="Reward from the quest “The Hunt Continues” — pick it over the other choices. In Red Cloud Mesa.",zone="Red Cloud Mesa",questName="The Hunt Continues",lore="A tauren skilled in the ways of the hunt knows that his prey is not for mere trophy. The beasts of the plains provide us with a means of survival."},
    [4917]={name="Battleworn Chain Leggings",sourceType="quest_reward",instructions="Reward from the quest “Sarkoth” — pick it over the other choices. In Valley of Trials.",zone="Valley of Trials",questName="Sarkoth",lore="Seeing the deed you have done for me steels my heart. I cannot fall so easily! I must endure! But it remains that I cannot make the trek back to the Den unassisted."},
    [4922]={name="Jagged Chain Vest",sourceType="quest_reward",instructions="Reward from the quest “Burning Blade Medallion” — pick it over the other choices. In Valley of Trials.",zone="Valley of Trials",questName="Burning Blade Medallion",lore="Through my divinations, I see that an item of power hides deep within the Burning Blade Coven, guarded by beasts and black magic. It is called the Burning Blade Medallion, and your next task is to find it and remove it from the coven."},
    [4935]={name="Wide Metal Girdle",sourceType="quest_reward",instructions="Reward from the quest “From The Wreckage....” — pick it over the other choices. In Durotar.",zone="Durotar",questName="From The Wreckage....",lore="One of my most observant scouts brings back word that the wreckage of Proudmoore's fleet still remains off the coast of Durotar, just east of Tiragarde Keep."},
    [4939]={name="Steady Bastard Sword",sourceType="quest_reward",instructions="Reward from the quest “Skull Rock” — pick it over the other choices. In Durotar.",zone="Durotar",questName="Skull Rock",lore=". The Burning Blade has infested the cave east of Orgrimmar known as Skull Rock. Inside that cave they perform vile rituals, and burn their own flesh with Searing Collars."},
    [4946]={name="Lightweight Boots",sourceType="quest_reward",instructions="Reward from the quest “Zalazane” — pick it over the other choices. In Durotar.",zone="Durotar",questName="Zalazane",lore="The witchdoctor Zalazane dwells on the Echo Isles to the east. They are the isles we once called home. From there he sends his trolls to the mainland, to hex our people and drag more of them under his sway."},
    [4964]={name="Goblin Smasher",sourceType="quest_reward",instructions="Reward from the quest “Supervisor Fizsprocket” — pick it over the other choices. In Mulgore.",zone="Mulgore",questName="Supervisor Fizsprocket",lore="According to the documents you salvaged from the caravan, the Venture Co. created many plans to attempt to drive us from our lands here, so that they could have free reign to plunder our lands."},
    [4969]={name="Fortified Bindings",sourceType="quest_reward",instructions="Reward from the quest “Dwarven Digging” — pick it over the other choices. In Mulgore.",zone="Mulgore",questName="Dwarven Digging",lore="There are dwarves preparing a dig site to the northwest. They think secrets lie in the earth, and that is true, but hollowing and defiling the land is no way to earn its teachings."},
    [5345]={name="Stonewood Hammer",sourceType="quest_reward",instructions="Reward from the quest “Centaur Bracers” — pick it over the other choices. In The Barrens.",zone="The Barrens",questName="Centaur Bracers",lore="The Kolkar are a threat to the Horde's claims in the Barrens; we must reduce the numbers of their troops. And so, I have a bounty task for you."},
    [5346]={name="Orcish Battle Bow",sourceType="quest_reward",instructions="Reward from the quest “Centaur Bracers” — pick it over the other choices. In The Barrens.",zone="The Barrens",questName="Centaur Bracers",lore="The Kolkar are a threat to the Horde's claims in the Barrens; we must reduce the numbers of their troops. And so, I have a bounty task for you."},
    [5776]={name="Elder's Cane",sourceType="quest_reward",instructions="Reward from the quest “Rite of Strength” — pick it over the other choices. In Red Cloud Mesa.",zone="Red Cloud Mesa",questName="Rite of Strength",lore="The Rites of the Earthmother are the steps a young tauren needs to take to gain respect in Thunder Bluff. First you must pass the Rite of Strength."},
    [5777]={name="Brave's Axe",sourceType="quest_reward",instructions="Reward from the quest “Rite of Strength” — pick it over the other choices. In Red Cloud Mesa.",zone="Red Cloud Mesa",questName="Rite of Strength",lore="The Rites of the Earthmother are the steps a young tauren needs to take to gain respect in Thunder Bluff. First you must pass the Rite of Strength."},
    [5778]={name="Primitive Walking Stick",sourceType="quest_reward",instructions="Reward from the quest “Vile Familiars” — pick it over the other choices.",questName="Vile Familiars",lore="I trust the Valley of Trials will teach you much, young. I was sent to the Valley to guide you, but I have discovered a growing taint here..."},
    [5941]={name="Brass Scale Pants",sourceType="quest_reward",instructions="Reward from the quest “Wanted: Maggot Eye” — pick it over the other choices. In Tirisfal Glades.",zone="Tirisfal Glades",questName="Wanted: Maggot Eye",lore="Wanted: Maggot Eye! A foul beast, even by Gnoll standards, Maggot Eye has been sentenced to death for his crimes against The Forsaken. This despicable villain has been stealing corpses for use by the Lich King's army."},
    [6063]={name="Cold Steel Gauntlets",sourceType="quest_reward",instructions="Reward from the quest “Graverobbers” — pick it over the other choices. In Tirisfal Glades.",zone="Tirisfal Glades",questName="Graverobbers",lore="The Mass Graves, southwest of Garren's Haunt to the north, were made to accommodate the...impressive...number of deaths Tirisfal suffered when the Plague first came."},
    [6337]={name="Infantry Leggings",sourceType="world_drop",instructions="World drop — drops from 466 creature types around level 6-14. Also found on the auction house."},
    [6506]={name="Infantry Boots",sourceType="world_drop",instructions="World drop — drops from 416 creature types around level 5-14. Also found on the auction house."},
    [6507]={name="Infantry Bracers",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 5-14. Also found on the auction house."},
    [6509]={name="Infantry Belt",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 5-14. Also found on the auction house."},
    [6510]={name="Infantry Gauntlets",sourceType="world_drop",instructions="World drop — drops from 416 creature types around level 5-14. Also found on the auction house."},
    [6514]={name="Disciple's Cloak",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 5-14. Also found on the auction house."},
    [7108]={name="Infantry Shield",sourceType="world_drop",instructions="World drop — drops from 401 creature types around level 6-14. Also found on the auction house."},
    [7109]={name="Pioneer Buckler",sourceType="world_drop",instructions="World drop — drops from 314 creature types around level 5-14. Also found on the auction house."},
    [8177]={name="Practice Sword",sourceType="world_drop",instructions="World drop — drops from 168 creature types around level 5-9. Also found on the auction house."},
    [8178]={name="Training Sword",sourceType="world_drop",instructions="World drop — drops from 339 creature types around level 6-14. Also found on the auction house."},
    [8179]={name="Cadet's Bow",sourceType="world_drop",instructions="World drop — drops from 314 creature types around level 5-14. Also found on the auction house."},
    [8180]={name="Hunting Bow",sourceType="world_drop",instructions="World drop — drops from 401 creature types around level 6-14. Also found on the auction house."},
    [8181]={name="Hunting Rifle",sourceType="world_drop",instructions="World drop — drops from 314 creature types around level 5-14. Also found on the auction house."},
    [8182]={name="Pellet Rifle",sourceType="world_drop",instructions="World drop — drops from 168 creature types around level 5-9. Also found on the auction house."},
    [9745]={name="Simple Cape",sourceType="world_drop",instructions="World drop — drops from 416 creature types around level 5-14. Also found on the auction house."},
    [9753]={name="Gypsy Buckler",sourceType="world_drop",instructions="World drop — drops from 466 creature types around level 6-14. Also found on the auction house."},
    [9758]={name="Cadet Belt",sourceType="world_drop",instructions="World drop — drops from 435 creature types around level 6-14. Also found on the auction house."},
    [9759]={name="Cadet Boots",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 8-14. Also found on the auction house."},
    [9760]={name="Cadet Bracers",sourceType="world_drop",instructions="World drop — drops from 435 creature types around level 6-14. Also found on the auction house."},
    [9762]={name="Cadet Gauntlets",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 8-14. Also found on the auction house."},
    [9763]={name="Cadet Leggings",sourceType="world_drop",instructions="World drop — drops from 359 creature types around level 9-15. Also found on the auction house."},
    [9764]={name="Cadet Shield",sourceType="world_drop",instructions="World drop — drops from 380 creature types around level 8-14. Also found on the auction house."},
    [10421]={name="Rough Copper Vest",sourceType="profession",instructions="Crafted with Blacksmithing (requires skill 1).",profession="Blacksmithing"},
    [11849]={name="Rustmetal Bracers",sourceType="quest_reward",instructions="Reward from the quest “Scavenging Deathknell” — pick it over the other choices. In Deathknell.",zone="Deathknell",questName="Scavenging Deathknell",lore="You there! If you're looking for something to make yourself useful, then listen up! We need fresh out-of-the-ground recruits to head into Deathknell and search for any sort of useful equipment."},
    [11852]={name="Roamer's Leggings",sourceType="quest_reward",instructions="Reward from the quest “Rattling the Rattlecages” — pick it over the other choices. In Deathknell.",zone="Deathknell",questName="Rattling the Rattlecages",lore="You've shown your potential to the Forsaken under normal circumstances - now let's see you under pressure. The Rattlecage skeletons, more mindless minions of the Lich King, are a tougher foe than the zombies you have faced thus far."},
    [14098]={name="Native Cloak",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 5-14. Also found on the auction house."},
    [15298]={name="Grizzly Buckler",sourceType="world_drop",instructions="World drop — drops from 380 creature types around level 8-14. Also found on the auction house."},
    [15472]={name="Charger's Belt",sourceType="world_drop",instructions="World drop — drops from 314 creature types around level 5-14. Also found on the auction house."},
    [15474]={name="Charger's Bindings",sourceType="world_drop",instructions="World drop — drops from 241 creature types around level 5-10. Also found on the auction house."},
    [15476]={name="Charger's Handwraps",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 5-14. Also found on the auction house."},
    [15477]={name="Charger's Pants",sourceType="world_drop",instructions="World drop — drops from 401 creature types around level 6-14. Also found on the auction house."},
    [15478]={name="Charger's Shield",sourceType="world_drop",instructions="World drop — drops from 241 creature types around level 5-10. Also found on the auction house."},
    [15479]={name="Charger's Armor",sourceType="world_drop",instructions="World drop — drops from 401 creature types around level 6-14. Also found on the auction house."},
    [15480]={name="War Torn Girdle",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 8-14. Also found on the auction house."},
    [15481]={name="War Torn Greaves",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 8-14. Also found on the auction house."},
    [15482]={name="War Torn Bands",sourceType="world_drop",instructions="World drop — drops from 416 creature types around level 5-14. Also found on the auction house."},
    [15484]={name="War Torn Handgrips",sourceType="world_drop",instructions="World drop — drops from 435 creature types around level 6-14. Also found on the auction house."},
    [15486]={name="War Torn Shield",sourceType="world_drop",instructions="World drop — drops from 466 creature types around level 6-14. Also found on the auction house."},
    [15807]={name="Light Crossbow",sourceType="vendor",instructions="Bought from Marda Weller in Eastern Kingdoms.",zone="Eastern Kingdoms",npc="Marda Weller"},
    [15895]={name="Burnt Buckler",sourceType="world_drop",instructions="World drop — drops from 241 creature types around level 5-10. Also found on the auction house."},
    [17185]={name="Round Buckler",sourceType="vendor",instructions="Bought from Sana in Orgrimmar.",zone="Orgrimmar",npc="Sana"},
    [18612]={name="Bloody Chain Boots",sourceType="world_drop",instructions="Drops from Fury Shelda (rare spawn) in Kalimdor.",zone="Kalimdor",npc="Fury Shelda"},
    [20910]={name="Stiff Shortbow",sourceType="vendor",instructions="Bought from Raelis Dawnstar in The Sunspire.",zone="The Sunspire",npc="Raelis Dawnstar"},
    [20914]={name="Unadorned Chain Belt",sourceType="vendor",instructions="Bought from Faraden Thelryn in The Sunspire.",zone="The Sunspire",npc="Faraden Thelryn"},
    [20915]={name="Unadorned Chain Boots",sourceType="vendor",instructions="Bought from Faraden Thelryn in The Sunspire.",zone="The Sunspire",npc="Faraden Thelryn"},
    [20916]={name="Unadorned Chain Bracers",sourceType="vendor",instructions="Bought from Faraden Thelryn in The Sunspire.",zone="The Sunspire",npc="Faraden Thelryn"},
    [20917]={name="Unadorned Chain Gloves",sourceType="vendor",instructions="Bought from Faraden Thelryn in The Sunspire.",zone="The Sunspire",npc="Faraden Thelryn"},
    [20919]={name="Unadorned Chain Vest",sourceType="vendor",instructions="Bought from Faraden Thelryn in The Sunspire.",zone="The Sunspire",npc="Faraden Thelryn"},
    [22953]={name="Fur Lined Chain Shirt",sourceType="quest_reward",instructions="Reward from the quest “Pelt Collection” — pick it over the other choices. In Eversong Woods.",zone="Eversong Woods",questName="Pelt Collection",lore="The springpaw that inhabit this region are known for their high quality pelts. We've even seen night elf scum travel to these lands just to poach them."},
    [23323]={name="Crown of the Fire Festival",sourceType="quest_reward",instructions="Reward from the quest “A Thief's Reward”.",questName="A Thief's Reward",lore="This flame, stolen from the heart of Stormwind itself, floods you with warmth. This raw power is foreign to you, but the (NAME) might know more..."},
    [23324]={name="Mantle of the Fire Festival",sourceType="quest_reward",instructions="Reward from the quest “Wild Fires in the Eastern Kingdoms”.",questName="Wild Fires in the Eastern Kingdoms",lore="Our celebration of the flame is spread throughout the land. Not a single place remains untouched by the heat of this holiday, and the strongest fires burn a brilliant blue."},
    [23403]={name="Salvaged Mail Leggings",sourceType="quest_reward",instructions="Reward from the quest “Windrunner Village” — pick it over the other choices. In Ghostlands.",zone="Ghostlands",questName="Windrunner Village",lore="the final battle against the Ghostlands villages is upon you. Windrunner Village to the southwest has been overrun by a large force of the more powerful Scourge shocktroopers; shades and gargoyles."},
    [24341]={name="Fortified Oven Mitts",sourceType="quest_reward",instructions="Reward from the quest “Anok'suten” — pick it over the other choices. In Ghostlands.",zone="Ghostlands",questName="Anok'suten",lore="Come closer, I am... dying. I was sent here... to slay these nerubians, but Vandril didn't... know that they have a leader. You must find and..."},
    [28148]={name="Bronze Mail Bracers",sourceType="quest_reward",instructions="Reward from the quest “Delivery to Tranquillien” — pick it over the other choices. In Ghostlands.",zone="Ghostlands",questName="Delivery to Tranquillien",lore="I... I'm too weak to continue. I carry a dire warning from Regent Lord Theron, in the form of a letter. You'll have to deliver it for me. Take it to Arcanist Vandril in Tranquillien."},
}

GQ.Data.warriorHorde1to9 = {
    {2570,"Back",1,2,1,0.18},
    {3322,"Back",1,2,2,0.18},
    {1376,"Back",1,2,3,0.15},
    {4658,"Back",3,3,1,0.21},
    {4662,"Back",3,3,2,0.21},
    {4665,"Back",3,3,3,0.21},
    {4668,"Back",4,4,1,0.24},
    {4671,"Back",4,4,2,0.24},
    {4674,"Back",4,4,3,0.24},
    {1421,"Back",5,5,1,0.27},
    {6514,"Back",5,5,2,0.27},
    {14098,"Back",5,5,3,0.27},
    {4772,"Back",6,6,1,0.3},
    {4854,"Back",6,6,2,0.3},
    {9745,"Back",6,6,3,0.3},
    {2580,"Back",7,7,1,0.33},
    {3331,"Back",7,7,2,0.33},
    {4677,"Back",7,7,3,0.33},
    {2310,"Back",8,8,1,0.36},
    {4680,"Back",8,8,2,0.36},
    {4683,"Back",8,8,3,0.36},
    {1497,"Back",9,9,1,0.36},
    {2310,"Back",9,9,2,0.36},
    {4680,"Back",9,9,3,0.36},
    {2386,"Chest",1,1,1,1.81},
    {4922,"Chest",1,1,2,1.81},
    {20919,"Chest",1,1,3,1.81},
    {10421,"Chest",2,3,1,2.19},
    {2386,"Chest",2,3,2,1.81},
    {3273,"Chest",2,3,3,1.81},
    {10421,"Chest",4,4,1,2.19},
    {22953,"Chest",4,4,2,2.19},
    {2386,"Chest",4,4,3,1.81},
    {3471,"Chest",5,5,1,3.82},
    {2648,"Chest",5,5,2,2.62},
    {10421,"Chest",5,5,3,2.19},
    {2965,"Chest",6,7,1,4.9},
    {15479,"Chest",6,7,2,4.13,suffix="of Strength",suffixChance=8.4,suffixId=23,suffixRange="+2 Strength"},
    {3471,"Chest",6,7,3,3.82},
    {3283,"Chest",8,9,1,5.6},
    {3330,"Chest",8,9,2,5.6},
    {2965,"Chest",8,9,3,4.9},
    {2389,"Feet",1,2,1,1.24},
    {20915,"Feet",1,2,2,1.24},
    {2650,"Feet",1,2,3,0.92},
    {18612,"Feet",3,3,1,1.65},
    {2389,"Feet",3,3,2,1.24},
    {20915,"Feet",3,3,3,1.24},
    {3332,"Feet",4,4,1,1.75},
    {3469,"Feet",4,4,2,1.75},
    {2642,"Feet",4,4,3,1.67},
    {2401,"Feet",5,5,1,1.89},
    {2967,"Feet",5,5,2,1.89},
    {4946,"Feet",5,5,3,1.89},
    {6506,"Feet",6,6,1,2.02},
    {2401,"Feet",6,6,2,1.89},
    {2967,"Feet",6,6,3,1.89},
    {3279,"Feet",7,7,1,2.16},
    {6506,"Feet",7,7,2,2.02},
    {2401,"Feet",7,7,3,1.89},
    {9759,"Feet",8,8,1,2.27},
    {15481,"Feet",8,8,2,2.27},
    {1731,"Feet",8,8,3,2.16},
    {2979,"Feet",9,9,1,2.4},
    {9759,"Feet",9,9,2,2.27},
    {15481,"Feet",9,9,3,2.27},
    {2391,"Hands",1,1,1,1.13},
    {4910,"Hands",1,1,2,1.13},
    {20917,"Hands",1,1,3,1.13},
    {2645,"Hands",2,3,1,1.3},
    {2391,"Hands",2,3,2,1.13},
    {4910,"Hands",2,3,3,1.13},
    {2968,"Hands",4,4,1,1.59},
    {6063,"Hands",4,4,2,1.48},
    {2645,"Hands",4,4,3,1.3},
    {2403,"Hands",5,5,1,1.73},
    {15476,"Hands",5,5,2,1.73},
    {2968,"Hands",5,5,3,1.59},
    {3281,"Hands",6,6,1,1.84},
    {6510,"Hands",6,6,2,1.84},
    {1734,"Hands",6,6,3,1.75},
    {3472,"Hands",7,7,1,1.97},
    {15484,"Hands",7,7,2,1.97},
    {3281,"Hands",7,7,3,1.84},
    {9762,"Hands",8,8,1,2.08},
    {3472,"Hands",8,8,2,1.97},
    {15484,"Hands",8,8,3,1.97},
    {24341,"Hands",9,9,1,2.84},
    {3304,"Hands",9,9,2,2.19},
    {9762,"Hands",9,9,3,2.08},
    {23323,"Head",1,9,1,0.04},
    {2388,"Legs",1,2,1,1.57},
    {4917,"Legs",1,2,2,1.57},
    {11852,"Legs",1,2,3,1.57},
    {2646,"Legs",3,3,1,1.97},
    {2388,"Legs",3,3,2,1.57},
    {4917,"Legs",3,3,3,1.57},
    {2852,"Legs",4,4,1,2.24},
    {2646,"Legs",4,4,2,1.97},
    {2388,"Legs",4,4,3,1.57},
    {2966,"Legs",5,5,1,2.85},
    {2400,"Legs",5,5,2,2.43},
    {2852,"Legs",5,5,3,2.24},
    {15477,"Legs",6,6,1,3.72,suffix="of Strength",suffixChance=10.0,suffixId=23,suffixRange="+1-2 Strength"},
    {2966,"Legs",6,6,2,2.85},
    {5941,"Legs",6,6,3,2.59},
    {3282,"Legs",7,7,1,4.1},
    {6337,"Legs",7,7,2,3.88,suffix="of Strength",suffixChance=10.0,suffixId=23,suffixRange="+1-2 Strength"},
    {15477,"Legs",7,7,3,3.72,suffix="of Strength",suffixChance=10.0,suffixId=23,suffixRange="+1-2 Strength"},
    {3473,"Legs",8,8,1,5.48},
    {3282,"Legs",8,8,2,4.1},
    {6337,"Legs",8,8,3,3.88,suffix="of Strength",suffixChance=10.0,suffixId=23,suffixRange="+1-2 Strength"},
    {23403,"Legs",9,9,1,5.64},
    {3473,"Legs",9,9,2,5.48},
    {9763,"Legs",9,9,3,4.55,suffix="of Strength",suffixChance=11.4,suffixId=97,suffixRange="+3-4 Strength"},
    {5777,"MainHand",1,1,1,19.11,route="onehand"},
    {5778,"MainHand",1,1,2,18.06,route="onehand"},
    {5776,"MainHand",1,1,3,17.99,route="onehand"},
    {3334,"MainHand",2,2,1,26.46,route="twohand"},
    {8177,"MainHand",2,2,2,26.25,route="twohand"},
    {2489,"MainHand",2,2,3,25.34,route="twohand"},
    {3190,"MainHand",3,3,1,30.94,route="twohand"},
    {2491,"MainHand",3,3,2,30.03,route="twohand"},
    {3189,"MainHand",3,3,3,29.68,route="twohand"},
    {2493,"MainHand",4,4,1,35.0,route="twohand"},
    {3325,"MainHand",4,4,2,35.0,route="twohand"},
    {3327,"MainHand",4,4,3,35.0,route="twohand"},
    {8178,"MainHand",5,5,1,51.11,suffix="of Strength",suffixChance=6.2,suffixId=97,suffixRange="+3-4 Strength",route="twohand"},
    {4562,"MainHand",5,5,2,49.9,suffix="of Strength",suffixChance=6.0,suffixId=97,suffixRange="+3-4 Strength",route="twohand"},
    {2067,"MainHand",5,5,3,40.18,route="twohand"},
    {4939,"MainHand",6,6,1,53.83,route="twohand"},
    {8178,"MainHand",6,6,2,51.11,suffix="of Strength",suffixChance=6.2,suffixId=97,suffixRange="+3-4 Strength",route="twohand"},
    {4562,"MainHand",6,6,3,49.9,suffix="of Strength",suffixChance=6.0,suffixId=97,suffixRange="+3-4 Strength",route="twohand"},
    {2254,"MainHand",7,7,1,61.36,route="twohand"},
    {4964,"MainHand",7,7,2,59.61,route="twohand"},
    {3192,"MainHand",7,7,3,59.44,suffix="of Strength",suffixChance=6.2,suffixId=97,suffixRange="+3-4 Strength",route="twohand"},
    {3440,"MainHand",8,8,1,66.42,route="twohand"},
    {3446,"MainHand",8,8,2,64.47,route="twohand"},
    {3488,"MainHand",8,8,3,64.47,route="twohand"},
    {5345,"MainHand",9,9,1,67.76,route="twohand"},
    {3440,"MainHand",9,9,2,66.42,route="twohand"},
    {3446,"MainHand",9,9,3,64.47,route="twohand"},
    {8179,"Ranged",1,1,1,4.0},
    {2505,"Ranged",1,1,2,3.75},
    {20910,"Ranged",1,1,3,3.75},
    {8182,"Ranged",2,2,1,4.42},
    {8179,"Ranged",2,2,2,4.0},
    {2505,"Ranged",2,2,3,3.75},
    {15807,"Ranged",3,3,1,4.6},
    {2506,"Ranged",3,3,2,4.52},
    {8182,"Ranged",3,3,3,4.42},
    {2509,"Ranged",4,4,1,5.0},
    {8181,"Ranged",4,4,2,5.0},
    {15807,"Ranged",4,4,3,4.6},
    {4362,"Ranged",5,5,1,6.3},
    {2509,"Ranged",5,5,2,5.0},
    {8181,"Ranged",5,5,3,5.0},
    {8180,"Ranged",6,6,1,6.92},
    {4362,"Ranged",6,6,2,6.3},
    {2509,"Ranged",6,6,3,5.0},
    {3079,"Ranged",7,7,1,7.11},
    {8180,"Ranged",7,7,2,6.92},
    {4362,"Ranged",7,7,3,6.3},
    {4577,"Ranged",8,8,1,8.0},
    {3079,"Ranged",8,8,2,7.11},
    {8180,"Ranged",8,8,3,6.92},
    {5346,"Ranged",9,9,1,8.42},
    {4577,"Ranged",9,9,2,8.0},
    {2511,"Ranged",9,9,3,7.62},
    {2212,"SecondaryHand",1,1,1,1.83,route="onehand"},
    {1200,"SecondaryHand",1,1,2,1.65,route="onehand"},
    {4911,"SecondaryHand",1,1,3,1.65,route="onehand"},
    {2213,"SecondaryHand",2,2,1,2.37,route="twohand"},
    {2212,"SecondaryHand",2,2,2,1.83,route="twohand"},
    {1200,"SecondaryHand",2,2,3,1.65,route="twohand"},
    {15478,"SecondaryHand",3,3,1,3.36,route="twohand"},
    {15895,"SecondaryHand",3,3,2,3.36,route="twohand"},
    {17185,"SecondaryHand",3,3,3,3.36,route="twohand"},
    {1438,"SecondaryHand",4,4,1,4.05,route="twohand"},
    {3650,"SecondaryHand",4,4,2,4.05,route="twohand"},
    {7109,"SecondaryHand",4,4,3,4.05,route="twohand"},
    {2376,"SecondaryHand",5,5,1,4.83,route="twohand"},
    {4263,"SecondaryHand",5,5,2,4.83,route="twohand"},
    {1438,"SecondaryHand",5,5,3,4.05,route="twohand"},
    {7108,"SecondaryHand",6,6,1,7.0,suffix="of the Bear",suffixChance=17.6,suffixId=1179,suffixRange="+1 Stamina, +1 Strength",route="twohand"},
    {3649,"SecondaryHand",6,6,2,5.67,route="twohand"},
    {2215,"SecondaryHand",6,6,3,5.16,route="twohand"},
    {9753,"SecondaryHand",7,7,1,7.96,suffix="of the Bear",suffixChance=17.6,suffixId=1179,suffixRange="+1 Stamina, +1 Strength",route="twohand"},
    {15486,"SecondaryHand",7,7,2,7.96,suffix="of the Bear",suffixChance=17.6,suffixId=1179,suffixRange="+1 Stamina, +1 Strength",route="twohand"},
    {7108,"SecondaryHand",7,7,3,7.0,suffix="of the Bear",suffixChance=17.6,suffixId=1179,suffixRange="+1 Stamina, +1 Strength",route="twohand"},
    {9764,"SecondaryHand",8,8,1,8.84,suffix="of Blocking",suffixChance=3.5,suffixId=1648,suffixRange="+5 Block Rating, +1 Strength",route="twohand"},
    {15298,"SecondaryHand",8,8,2,8.41,suffix="of the Eagle",suffixChance=12.5,suffixId=839,suffixRange="+1 Intellect, +1 Stamina",route="twohand"},
    {9753,"SecondaryHand",8,8,3,7.96,suffix="of the Bear",suffixChance=17.6,suffixId=1179,suffixRange="+1 Stamina, +1 Strength",route="twohand"},
    {3654,"SecondaryHand",9,9,1,10.03,route="twohand"},
    {3652,"SecondaryHand",9,9,2,9.73,route="twohand"},
    {9764,"SecondaryHand",9,9,3,8.84,suffix="of Blocking",suffixChance=3.5,suffixId=1648,suffixRange="+5 Block Rating, +1 Strength",route="twohand"},
    {23324,"Shoulder",1,9,1,0.06},
    {2387,"Waist",1,2,1,1.03},
    {4913,"Waist",1,2,2,1.03},
    {20914,"Waist",1,2,3,1.03},
    {4659,"Waist",3,3,1,1.35},
    {4935,"Waist",3,3,2,1.35},
    {2635,"Waist",3,3,3,1.27},
    {15472,"Waist",4,4,1,1.43},
    {4659,"Waist",4,4,2,1.35},
    {4935,"Waist",4,4,3,1.35},
    {2399,"Waist",5,5,1,1.57},
    {4669,"Waist",5,5,2,1.57},
    {6509,"Waist",5,5,3,1.57},
    {2546,"Waist",6,6,1,1.65},
    {2851,"Waist",6,6,2,1.65},
    {2399,"Waist",6,6,3,1.57},
    {9758,"Waist",7,7,1,1.75},
    {1730,"Waist",7,7,2,1.67},
    {2546,"Waist",7,7,3,1.65},
    {15480,"Waist",8,8,1,1.86},
    {9758,"Waist",8,8,2,1.75},
    {1730,"Waist",8,8,3,1.67},
    {4678,"Waist",9,9,1,1.97},
    {4681,"Waist",9,9,2,1.97},
    {15480,"Waist",9,9,3,1.86},
    {2390,"Wrist",1,1,1,0.78},
    {20916,"Wrist",1,1,2,0.78},
    {2651,"Wrist",1,1,3,0.68},
    {2853,"Wrist",2,2,1,0.95},
    {2390,"Wrist",2,2,2,0.78},
    {11849,"Wrist",2,2,3,0.78},
    {15474,"Wrist",3,3,1,1.05},
    {2853,"Wrist",3,3,2,0.95},
    {2390,"Wrist",3,3,3,0.78},
    {3214,"Wrist",4,4,1,1.13},
    {3280,"Wrist",4,4,2,1.13},
    {15474,"Wrist",4,4,3,1.05},
    {2402,"Wrist",5,5,1,1.21},
    {6507,"Wrist",5,5,2,1.21},
    {2643,"Wrist",5,5,3,1.13},
    {15482,"Wrist",6,6,1,1.3},
    {2402,"Wrist",6,6,2,1.21},
    {4969,"Wrist",6,6,3,1.21},
    {3303,"Wrist",7,7,1,1.38},
    {9760,"Wrist",7,7,2,1.38},
    {15482,"Wrist",7,7,3,1.3},
    {3213,"Wrist",8,8,1,1.46},
    {3303,"Wrist",8,8,2,1.38},
    {9760,"Wrist",8,8,3,1.38},
    {28148,"Wrist",9,9,1,2.17},
    {1732,"Wrist",9,9,2,1.46},
    {3213,"Wrist",9,9,3,1.46},
}
