local _, GQ = ...
GQ.Data = GQ.Data or {}

-- GENERATED -- Hunter, ALLIANCE, HORDE, levels 1-9. Nothing else is in this file:
-- no Alliance rows and no level 10 or above, so it can sit next to the
-- hand-made Alliance 1-9 data without either overwriting the other.
--
-- The race filter is the class's own playable races for that faction, not the whole
-- faction: a Horde warrior can be Orc, Undead, Tauren or Troll but never a Blood Elf,
-- so Blood Elf starting quests are gated out. Quests are gated on quest_template.RequiredRaces, and
-- faction-exclusive zones are gated by name -- a vendor standing in Darnassus is
-- not race-restricted, the city is.
--
-- No spec column. Hunters have no talents before level 10, so one list serves all
-- three specs across this range.
--
-- row = { itemId, slot, minLevel, maxLevel, rank, score }
--   optional: suffix, suffixChance  (random-enchantment items -- score assumes the
--   best roll, and suffixChance is the odds of getting any roll of that suffix)

GQ.Data.hunterEarly1to9Facts = {
    [60]={name="Layered Tunic",sourceType="quest_reward",instructions="Reward from the quest “Bounty on Garrick Padfoot” — pick it over the other choices. In Northshire Valley.",zone="Northshire Valley",questName="Bounty on Garrick Padfoot",lore="Garrick Padfoot - a cutthroat who's plagued our farmers and merchants for weeks - was seen at a shack near the vineyards, which lies east of the Abbey and across the bridge."},
    [61]={name="Dwarven Leather Pants",sourceType="quest_reward",instructions="Reward from the quest “The Boar Hunter” — pick it over the other choices. In Coldridge Valley.",zone="Coldridge Valley",questName="The Boar Hunter",lore="Nothing like a day of boar hunting, eh? Though, here in Coldridge Valley, there are so many boars it almost takes the fun out of it. No need to get them charging."},
    [85]={name="Dirty Leather Vest",sourceType="vendor",instructions="Bought from Lauren Newcomb in Undercity.",zone="Undercity",npc="Lauren Newcomb"},
    [209]={name="Dirty Leather Pants",sourceType="vendor",instructions="Bought from Lauren Newcomb in Undercity.",zone="Undercity",npc="Lauren Newcomb"},
    [210]={name="Dirty Leather Boots",sourceType="vendor",instructions="Bought from Lauren Newcomb in Undercity.",zone="Undercity",npc="Lauren Newcomb"},
    [714]={name="Dirty Leather Gloves",sourceType="vendor",instructions="Bought from Lauren Newcomb in Undercity.",zone="Undercity",npc="Lauren Newcomb"},
    [763]={name="Ice-covered Bracers",sourceType="world_drop",instructions="Drops from Hammerspine (rare spawn) in Eastern Kingdoms.",zone="Eastern Kingdoms",npc="Hammerspine"},
    [767]={name="Long Bo Staff",sourceType="world_drop",instructions="World drop — drops from 241 creature types around level 5-10. Also found on the auction house."},
    [796]={name="Rough Leather Boots",sourceType="world_drop",instructions="Drops from Pyrewood Leatherworker in Pyrewood Village.",zone="Pyrewood Village",npc="Pyrewood Leatherworker"},
    [797]={name="Rough Leather Gloves",sourceType="world_drop",instructions="Drops from Pyrewood Leatherworker in Pyrewood Village.",zone="Pyrewood Village",npc="Pyrewood Leatherworker"},
    [798]={name="Rough Leather Pants",sourceType="world_drop",instructions="Drops from Pyrewood Leatherworker in Pyrewood Village.",zone="Pyrewood Village",npc="Pyrewood Leatherworker"},
    [799]={name="Rough Leather Vest",sourceType="world_drop",instructions="Drops from Pyrewood Leatherworker in Pyrewood Village.",zone="Pyrewood Village",npc="Pyrewood Leatherworker"},
    [821]={name="Riverpaw Leather Vest",sourceType="world_drop",instructions="Drops from Riverpaw Mongrel in Moonbrook.",zone="Moonbrook",npc="Riverpaw Mongrel"},
    [1010]={name="Gnarled Short Staff",sourceType="quest_reward",instructions="Reward from the quest “Return to Bellowfiz” — pick it over the other choices. In Dun Morogh.",zone="Dun Morogh",questName="Return to Bellowfiz",lore="Here's your cask of Evershine. And again, thank you for the hunting earlier."},
    [1173]={name="Weather-worn Boots",sourceType="quest_reward",instructions="Reward from the quest “Princess Must Die!” — pick it over the other choices. In Elwynn Forest.",zone="Elwynn Forest",questName="Princess Must Die!",lore="The Brackwells have a prize-winning pig, Princess. The sow is HUGE, and she got that way from sneaking over here and eating my veggies! So before she comes to our fields...Princess must die!"},
    [1213]={name="Gnoll Kindred Bracers",sourceType="world_drop",instructions="Drops from Redridge Thrasher in Redridge Mountains.",zone="Redridge Mountains",npc="Redridge Thrasher"},
    [1367]={name="Ragged Leather Boots",sourceType="world_drop",instructions="World drop — drops from 62 creature types around level 1-5. Also found on the auction house."},
    [1376]={name="Frayed Cloak",sourceType="world_drop",instructions="World drop — drops from 62 creature types around level 1-5. Also found on the auction house."},
    [1412]={name="Crude Bastard Sword",sourceType="world_drop",instructions="World drop — drops from 236 creature types around level 1-10. Also found on the auction house."},
    [1418]={name="Worn Leather Belt",sourceType="world_drop",instructions="World drop — drops from 236 creature types around level 1-10. Also found on the auction house."},
    [1419]={name="Worn Leather Boots",sourceType="world_drop",instructions="World drop — drops from 236 creature types around level 1-10. Also found on the auction house."},
    [1420]={name="Worn Leather Bracers",sourceType="world_drop",instructions="World drop — drops from 236 creature types around level 1-10. Also found on the auction house."},
    [1421]={name="Worn Hide Cloak",sourceType="world_drop",instructions="World drop — drops from 236 creature types around level 1-10. Also found on the auction house."},
    [1422]={name="Worn Leather Gloves",sourceType="world_drop",instructions="World drop — drops from 236 creature types around level 1-10. Also found on the auction house."},
    [1423]={name="Worn Leather Pants",sourceType="world_drop",instructions="World drop — drops from 236 creature types around level 1-10. Also found on the auction house."},
    [1425]={name="Worn Leather Vest",sourceType="world_drop",instructions="World drop — drops from 236 creature types around level 1-10. Also found on the auction house."},
    [1429]={name="Patchwork Cloak",sourceType="world_drop",instructions="World drop — drops from 236 creature types around level 1-10. Also found on the auction house."},
    [1497]={name="Calico Cloak",sourceType="world_drop",instructions="World drop — drops from 242 creature types around level 9-15. Also found on the auction house."},
    [1502]={name="Warped Leather Belt",sourceType="world_drop",instructions="World drop — drops from 242 creature types around level 9-15. Also found on the auction house."},
    [1504]={name="Warped Leather Bracers",sourceType="world_drop",instructions="World drop — drops from 242 creature types around level 9-15. Also found on the auction house."},
    [1835]={name="Dirty Leather Belt",sourceType="vendor",instructions="Bought from Lauren Newcomb in Undercity.",zone="Undercity",npc="Lauren Newcomb"},
    [1836]={name="Dirty Leather Bracers",sourceType="vendor",instructions="Bought from Lauren Newcomb in Undercity.",zone="Undercity",npc="Lauren Newcomb"},
    [1839]={name="Rough Leather Belt",sourceType="world_drop",instructions="Drops from Pyrewood Leatherworker in Pyrewood Village.",zone="Pyrewood Village",npc="Pyrewood Leatherworker"},
    [1840]={name="Rough Leather Bracers",sourceType="world_drop",instructions="Drops from Pyrewood Leatherworker in Pyrewood Village.",zone="Pyrewood Village",npc="Pyrewood Leatherworker"},
    [1965]={name="White Wolf Gloves",sourceType="world_drop",instructions="Drops from Timber (rare spawn) in Brewnall Village.",zone="Brewnall Village",npc="Timber"},
    [2067]={name="Frostbit Staff",sourceType="world_drop",instructions="Drops from Rockjaw Bonesnapper in Eastern Kingdoms.",zone="Eastern Kingdoms",npc="Rockjaw Bonesnapper"},
    [2112]={name="Lumberjack Jerkin",sourceType="world_drop",instructions="Drops from Scarred Crag Boar in Eastern Kingdoms.",zone="Eastern Kingdoms",npc="Scarred Crag Boar"},
    [2122]={name="Cracked Leather Belt",sourceType="vendor",instructions="Bought from Gamili Frosthide in Kharanos.",zone="Kharanos",npc="Gamili Frosthide"},
    [2123]={name="Cracked Leather Boots",sourceType="vendor",instructions="Bought from Gamili Frosthide in Kharanos.",zone="Kharanos",npc="Gamili Frosthide"},
    [2124]={name="Cracked Leather Bracers",sourceType="vendor",instructions="Bought from Gamili Frosthide in Kharanos.",zone="Kharanos",npc="Gamili Frosthide"},
    [2125]={name="Cracked Leather Gloves",sourceType="vendor",instructions="Bought from Gamili Frosthide in Kharanos.",zone="Kharanos",npc="Gamili Frosthide"},
    [2126]={name="Cracked Leather Pants",sourceType="vendor",instructions="Bought from Gamili Frosthide in Kharanos.",zone="Kharanos",npc="Gamili Frosthide"},
    [2127]={name="Cracked Leather Vest",sourceType="vendor",instructions="Bought from Gamili Frosthide in Kharanos.",zone="Kharanos",npc="Gamili Frosthide"},
    [2186]={name="Outfitter Belt",sourceType="quest_reward",instructions="Reward from the quest “Skirmish at Echo Ridge” — pick it over the other choices. In Northshire Valley.",zone="Northshire Valley",questName="Skirmish at Echo Ridge",lore="Your previous investigations are proof that the Echo Ridge Mine needs purging. Return to the mine and help clear it of kobolds. Waste no time."},
    [2300]={name="Embossed Leather Vest",sourceType="profession",instructions="Crafted with Leatherworking (requires skill 50).",profession="Leatherworking"},
    [2302]={name="Handstitched Leather Boots",sourceType="profession",instructions="Crafted with Leatherworking (requires skill 1).",profession="Leatherworking"},
    [2303]={name="Handstitched Leather Pants",sourceType="profession",instructions="Crafted with Leatherworking (requires skill 30).",profession="Leatherworking"},
    [2310]={name="Embossed Leather Cloak",sourceType="profession",instructions="Crafted with Leatherworking (requires skill 65).",profession="Leatherworking"},
    [2327]={name="Sturdy Leather Bracers",sourceType="world_drop",instructions="Drops from Rusty Harvest Golem in Westfall.",zone="Westfall",npc="Rusty Harvest Golem"},
    [2371]={name="Battered Leather Belt",sourceType="vendor",instructions="Bought from Lauren Newcomb in Undercity.",zone="Undercity",npc="Lauren Newcomb"},
    [2373]={name="Battered Leather Boots",sourceType="vendor",instructions="Bought from Lauren Newcomb in Undercity.",zone="Undercity",npc="Lauren Newcomb"},
    [2374]={name="Battered Leather Bracers",sourceType="vendor",instructions="Bought from Lauren Newcomb in Undercity.",zone="Undercity",npc="Lauren Newcomb"},
    [2375]={name="Battered Leather Gloves",sourceType="vendor",instructions="Bought from Lauren Newcomb in Undercity.",zone="Undercity",npc="Lauren Newcomb"},
    [2489]={name="Two-handed Sword",sourceType="world_drop",instructions="Drops from Hillsbrad Apprentice Blacksmith in Eastern Kingdoms.",zone="Eastern Kingdoms",npc="Hillsbrad Apprentice Blacksmith"},
    [2491]={name="Large Axe",sourceType="world_drop",instructions="Drops from Hillsbrad Apprentice Blacksmith in Eastern Kingdoms.",zone="Eastern Kingdoms",npc="Hillsbrad Apprentice Blacksmith"},
    [2505]={name="Polished Shortbow",sourceType="vendor",instructions="Bought from Beega in Blood Watch.",zone="Blood Watch",npc="Beega"},
    [2506]={name="Hornwood Recurve Bow",sourceType="vendor",instructions="Bought from Beega in Blood Watch.",zone="Blood Watch",npc="Beega"},
    [2509]={name="Ornate Blunderbuss",sourceType="vendor",instructions="Bought from Jyn Stonehoof in Thunder Bluff.",zone="Thunder Bluff",npc="Jyn Stonehoof"},
    [2511]={name="Hunter's Boomstick",sourceType="vendor",instructions="Bought from Jyn Stonehoof in Thunder Bluff.",zone="Thunder Bluff",npc="Jyn Stonehoof"},
    [2570]={name="Linen Cloak",sourceType="profession",instructions="Crafted with Tailoring (requires skill 1).",profession="Tailoring"},
    [2580]={name="Reinforced Linen Cape",sourceType="profession",instructions="Crafted with Tailoring (requires skill 1).",profession="Tailoring"},
    [2817]={name="Soft Leather Tunic",sourceType="quest_reward",instructions="Reward from the quest “Protecting the Herd” — pick it over the other choices. In Dun Morogh.",zone="Dun Morogh",questName="Protecting the Herd",lore="We heard the cries in the middle of the night. Then this morning, sure enough, the herd was missing two rams. That dastardly beast known as Vagash has been preying on our livelihood."},
    [2905]={name="Goat Fur Cloak",sourceType="quest_reward",instructions="Reward from the quest “The Perfect Stout” — pick it over the other choices. In Dun Morogh.",zone="Dun Morogh",questName="The Perfect Stout",lore="I'm on a quest, a quest to make the perfect stout. I know I can do it -- brewing's in my blood. I just need to find the right recipe... The Frostmane trolls grow a plant, shimmerweed, high up in the hills to the east."},
    [2962]={name="Burnt Leather Breeches",sourceType="world_drop",instructions="World drop — drops from 339 creature types around level 6-14. Also found on the auction house."},
    [2963]={name="Burnt Leather Boots",sourceType="world_drop",instructions="World drop — drops from 314 creature types around level 5-14. Also found on the auction house."},
    [2964]={name="Burnt Leather Gloves",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 5-14. Also found on the auction house."},
    [2975]={name="Hunting Boots",sourceType="world_drop",instructions="World drop — drops from 355 creature types around level 9-15. Also found on the auction house."},
    [3000]={name="Brood Mother Carapace",sourceType="world_drop",instructions="Drops from Mother Fang (rare spawn) in Northshire Valley.",zone="Northshire Valley",npc="Mother Fang"},
    [3008]={name="Wendigo Fur Cloak",sourceType="world_drop",instructions="Drops from Edan the Howler (rare spawn) in Kharanos.",zone="Kharanos",npc="Edan the Howler"},
    [3079]={name="Skorn's Rifle",sourceType="quest_reward",instructions="Reward from the quest “The Demon Scarred Cloak” — pick it over the other choices. In Mulgore.",zone="Mulgore",questName="The Demon Scarred Cloak",lore="The ragged hide of Ghost Howl still bears a terrible wound, gained from the wolf's battles against the Burning Legion. Perhaps someone in Bloodhoof Village should know of Ghost Howl's demise...."},
    [3189]={name="Wood Chopper",sourceType="world_drop",instructions="World drop — drops from 241 creature types around level 5-10. Also found on the auction house."},
    [3192]={name="Short Bastard Sword",sourceType="world_drop",instructions="World drop — drops from 466 creature types around level 6-14. Also found on the auction house."},
    [3200]={name="Burnt Leather Bracers",sourceType="world_drop",instructions="World drop — drops from 241 creature types around level 5-10. Also found on the auction house."},
    [3207]={name="Hunting Bracers",sourceType="world_drop",instructions="World drop — drops from 355 creature types around level 9-15. Also found on the auction house."},
    [3284]={name="Tribal Boots",sourceType="world_drop",instructions="World drop — drops from 435 creature types around level 6-14. Also found on the auction house."},
    [3285]={name="Tribal Bracers",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 5-14. Also found on the auction house."},
    [3286]={name="Tribal Gloves",sourceType="world_drop",instructions="World drop — drops from 435 creature types around level 6-14. Also found on the auction house."},
    [3287]={name="Tribal Pants",sourceType="world_drop",instructions="World drop — drops from 466 creature types around level 6-14. Also found on the auction house."},
    [3288]={name="Tribal Vest",sourceType="world_drop",instructions="World drop — drops from 380 creature types around level 8-14. Also found on the auction house."},
    [3312]={name="Ceremonial Leather Bracers",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 8-14. Also found on the auction house."},
    [3321]={name="Gray Fur Booties",sourceType="world_drop",instructions="Drops from Ravenous Darkhound in Scarlet Monastery.",zone="Scarlet Monastery",npc="Ravenous Darkhound"},
    [3322]={name="Wispy Cloak",sourceType="world_drop",instructions="Drops from Lost Soul (rare spawn) in Brill.",zone="Brill",npc="Lost Soul"},
    [3325]={name="Vile Fin Battle Axe",sourceType="world_drop",instructions="Drops from Vile Fin Muckdweller in Eastern Kingdoms.",zone="Eastern Kingdoms",npc="Vile Fin Muckdweller"},
    [3327]={name="Vile Fin Oracle Staff",sourceType="world_drop",instructions="Drops from Vile Fin Minor Oracle in Eastern Kingdoms.",zone="Eastern Kingdoms",npc="Vile Fin Minor Oracle"},
    [3331]={name="Melrache's Cape",sourceType="world_drop",instructions="Drops from Captain Melrache in Scarlet Monastery.",zone="Scarlet Monastery",npc="Captain Melrache"},
    [3446]={name="Darkwood Staff",sourceType="quest_reward",instructions="Reward from the quest “The Family Crypt” — pick it over the other choices. In Tirisfal Glades.",zone="Tirisfal Glades",questName="The Family Crypt",lore="The Agamand Mills area has become a foothold for the Scourge. Their strongest point is the Agamand Family Crypt where their local military leader, a skeleton named Captain Dargol, has headquartered."},
    [3488]={name="Copper Battle Axe",sourceType="profession",instructions="Crafted with Blacksmithing (requires skill 1).",profession="Blacksmithing"},
    [4237]={name="Handstitched Leather Belt",sourceType="profession",instructions="Crafted with Leatherworking (requires skill 1).",profession="Leatherworking"},
    [4239]={name="Embossed Leather Gloves",sourceType="profession",instructions="Crafted with Leatherworking (requires skill 1).",profession="Leatherworking"},
    [4362]={name="Rough Boomstick",sourceType="profession",instructions="Crafted with Engineering (requires skill 1).",profession="Engineering"},
    [4562]={name="Severing Axe",sourceType="world_drop",instructions="World drop — drops from 339 creature types around level 6-14. Also found on the auction house."},
    [4566]={name="Sturdy Quarterstaff",sourceType="world_drop",instructions="World drop — drops from 380 creature types around level 8-14. Also found on the auction house."},
    [4577]={name="Compact Shotgun",sourceType="world_drop",instructions="World drop — drops from 380 creature types around level 8-14. Also found on the auction house."},
    [4658]={name="Warrior's Cloak",sourceType="world_drop",instructions="World drop — drops from 241 creature types around level 5-10. Also found on the auction house."},
    [4662]={name="Journeyman's Cloak",sourceType="world_drop",instructions="World drop — drops from 241 creature types around level 5-10. Also found on the auction house."},
    [4665]={name="Burnt Cloak",sourceType="world_drop",instructions="World drop — drops from 241 creature types around level 5-10. Also found on the auction house."},
    [4666]={name="Burnt Leather Belt",sourceType="world_drop",instructions="World drop — drops from 314 creature types around level 5-14. Also found on the auction house."},
    [4668]={name="Battle Chain Cloak",sourceType="world_drop",instructions="World drop — drops from 314 creature types around level 5-14. Also found on the auction house."},
    [4671]={name="Ancestral Cloak",sourceType="world_drop",instructions="World drop — drops from 314 creature types around level 5-14. Also found on the auction house."},
    [4674]={name="Tribal Cloak",sourceType="world_drop",instructions="World drop — drops from 314 creature types around level 5-14. Also found on the auction house."},
    [4675]={name="Tribal Belt",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 5-14. Also found on the auction house."},
    [4677]={name="Veteran Cloak",sourceType="world_drop",instructions="World drop — drops from 435 creature types around level 6-14. Also found on the auction house."},
    [4680]={name="Brackwater Cloak",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 8-14. Also found on the auction house."},
    [4683]={name="Spellbinder Cloak",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 8-14. Also found on the auction house."},
    [4690]={name="Hunting Belt",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 8-14. Also found on the auction house."},
    [4693]={name="Ceremonial Leather Belt",sourceType="world_drop",instructions="World drop — drops from 355 creature types around level 9-15. Also found on the auction house."},
    [4772]={name="Warm Cloak",sourceType="world_drop",instructions="Drops from Sister Hatelash (rare spawn) in Thunder Bluff.",zone="Thunder Bluff",npc="Sister Hatelash"},
    [4854]={name="Demon Scarred Cloak",sourceType="world_drop",instructions="Drops from Ghost Howl (rare spawn) in Thunder Bluff.",zone="Thunder Bluff",npc="Ghost Howl"},
    [4861]={name="Sleek Feathered Tunic",sourceType="world_drop",instructions="Drops from Mazzranache (rare spawn) in Mulgore.",zone="Mulgore",npc="Mazzranache"},
    [4906]={name="Rainwalker Boots",sourceType="quest_reward",instructions="Reward from the quest “Rite of Vision” — pick it over the other choices. In Mulgore.",zone="Mulgore",questName="Rite of Vision",lore="I now present you with the Water of the Seers. When you are ready, consume the waters near the tribal fire. Once you have ingested the holy waters, it will take a few moments before the vision materializes before the fire."},
    [4907]={name="Woodland Tunic",sourceType="quest_reward",instructions="Reward from the quest “Webwood Egg” — pick it over the other choices. In Shadowglen.",zone="Shadowglen",questName="Webwood Egg",lore="Now that I have the spiders' venom, I'd like some live specimens to study. Unfortunately, capturing a living, giant spider is more than I can ask of you, young."},
    [4908]={name="Nomadic Bracers",sourceType="quest_reward",instructions="Reward from the quest “The Hunt Continues” — pick it over the other choices. In Red Cloud Mesa.",zone="Red Cloud Mesa",questName="The Hunt Continues",lore="A tauren skilled in the ways of the hunt knows that his prey is not for mere trophy. The beasts of the plains provide us with a means of survival."},
    [4914]={name="Battleworn Leather Gloves",sourceType="quest_reward",instructions="Reward from the quest “Cutting Teeth” — pick it over the other choices. In Valley of Trials.",zone="Valley of Trials",questName="Cutting Teeth",lore="The first order of business will be to put a little strength in your backbone. I could send you out to the Barrens to hunt kodo, but well, in all honesty, you're more useful to us alive than dead."},
    [4921]={name="Dust-covered Leggings",sourceType="quest_reward",instructions="Reward from the quest “Burning Blade Medallion” — pick it over the other choices. In Valley of Trials.",zone="Valley of Trials",questName="Burning Blade Medallion",lore="Through my divinations, I see that an item of power hides deep within the Burning Blade Coven, guarded by beasts and black magic. It is called the Burning Blade Medallion, and your next task is to find it and remove it from the coven."},
    [4928]={name="Sandrunner Wristguards",sourceType="quest_reward",instructions="Reward from the quest “From The Wreckage....” — pick it over the other choices. In Durotar.",zone="Durotar",questName="From The Wreckage....",lore="One of my most observant scouts brings back word that the wreckage of Proudmoore's fleet still remains off the coast of Durotar, just east of Tiragarde Keep."},
    [4939]={name="Steady Bastard Sword",sourceType="quest_reward",instructions="Reward from the quest “Skull Rock” — pick it over the other choices. In Durotar.",zone="Durotar",questName="Skull Rock",lore=". The Burning Blade has infested the cave east of Orgrimmar known as Skull Rock. Inside that cave they perform vile rituals, and burn their own flesh with Searing Collars."},
    [4942]={name="Tiger Hide Boots",sourceType="quest_reward",instructions="Reward from the quest “Dark Storms”. In Durotar.",zone="Durotar",questName="Dark Storms",lore="We cannot allow the Burning Blade a foothold in Durotar! We must destroy them before their evil festers!"},
    [4951]={name="Squealer's Belt",sourceType="world_drop",instructions="Drops from \"Squealer\" Thornmantle in Kalimdor.",zone="Kalimdor",npc="\"Squealer\" Thornmantle"},
    [4954]={name="Nomadic Belt",sourceType="quest_reward",instructions="Reward from the quest “The Hunt Begins” — pick it over the other choices. In Red Cloud Mesa.",zone="Red Cloud Mesa",questName="The Hunt Begins",lore="You have a promising air about you, and will prove yourself to the tribe. Perhaps someday soon you will be welcomed into the great city of Thunder Bluff."},
    [4962]={name="Double-layered Gloves",sourceType="quest_reward",instructions="Reward from the quest “Gathering Leather” — pick it over the other choices. In Thunder Bluff.",zone="Thunder Bluff",questName="Gathering Leather",lore="Greetings, young one. You have a gleam in your eye; I can tell you are eager to venture back to the plains for the hunt. May you bring honor to your clan!"},
    [5346]={name="Orcish Battle Bow",sourceType="quest_reward",instructions="Reward from the quest “Centaur Bracers” — pick it over the other choices. In The Barrens.",zone="The Barrens",questName="Centaur Bracers",lore="The Kolkar are a threat to the Horde's claims in the Barrens; we must reduce the numbers of their troops. And so, I have a bounty task for you."},
    [5394]={name="Archery Training Gloves",sourceType="quest_reward",instructions="Reward from the quest “The Balance of Nature” — pick it over the other choices. In Shadowglen.",zone="Shadowglen",questName="The Balance of Nature",lore="Greetings. I am Conservator Ilthalaine. My purpose in Shadowglen is to ensure that the balance of nature is maintained."},
    [5581]={name="Smooth Walking Staff",sourceType="quest_reward",instructions="Reward from the quest “The Stolen Journal” — pick it over the other choices. In Coldridge Valley.",zone="Coldridge Valley",questName="The Stolen Journal",lore="My journal! They took it away to the cave. The one that had it... It was a big brute with some odd markings on his skin and face. I didn't get a much better look than that."},
    [5591]={name="Rain-spotted Cape",sourceType="quest_reward",instructions="Reward from the quest “The Enchanted Glade” — pick it over the other choices. In Teldrassil.",zone="Teldrassil",questName="The Enchanted Glade",lore="I was dispatched with a small group of Sentinels here to protect the Oracle Tree from the harpies that have made nests all around the glade."},
    [5596]={name="Ashwood Bow",sourceType="quest_reward",instructions="Reward from the quest “Crown of the Earth” — pick it over the other choices. In Teldrassil.",zone="Teldrassil",questName="Crown of the Earth",lore="Without the blessings of Alexstrasza the Life-Binder and Nozdormu the Timeless, Teldrassil's growth has not been without flaw."},
    [5617]={name="Vagabond Leggings",sourceType="quest_reward",instructions="Reward from the quest “Bashal'Aran” — pick it over the other choices. In Darkshore.",zone="Darkshore",questName="Bashal'Aran",lore="It was the craft of one of the most powerful of the Highborne that created the seal that formed my prison. In Ameth'Aran, the ruins to the south that are twin to these, persists even today an ancient flame, blue in color."},
    [5776]={name="Elder's Cane",sourceType="quest_reward",instructions="Reward from the quest “Rite of Strength” — pick it over the other choices. In Red Cloud Mesa.",zone="Red Cloud Mesa",questName="Rite of Strength",lore="The Rites of the Earthmother are the steps a young tauren needs to take to gain respect in Thunder Bluff. First you must pass the Rite of Strength."},
    [5777]={name="Brave's Axe",sourceType="quest_reward",instructions="Reward from the quest “Rite of Strength” — pick it over the other choices. In Red Cloud Mesa.",zone="Red Cloud Mesa",questName="Rite of Strength",lore="The Rites of the Earthmother are the steps a young tauren needs to take to gain respect in Thunder Bluff. First you must pass the Rite of Strength."},
    [5778]={name="Primitive Walking Stick",sourceType="quest_reward",instructions="Reward from the quest “Vile Familiars” — pick it over the other choices.",questName="Vile Familiars",lore="I trust the Valley of Trials will teach you much, young. I was sent to the Valley to guide you, but I have discovered a growing taint here..."},
    [5936]={name="Animal Skin Belt",sourceType="quest_reward",instructions="Reward from the quest “Gathering Leather” — pick it over the other choices. In Thunder Bluff.",zone="Thunder Bluff",questName="Gathering Leather",lore="Greetings, young one. You have a gleam in your eye; I can tell you are eager to venture back to the plains for the hunt. May you bring honor to your clan!"},
    [5957]={name="Handstitched Leather Vest",sourceType="profession",instructions="Crafted with Leatherworking (requires skill 1).",profession="Leatherworking"},
    [6059]={name="Nomadic Vest",sourceType="quest_reward",instructions="Reward from the quest “The Battleboars”. In Red Cloud Mesa.",zone="Red Cloud Mesa",questName="The Battleboars",lore="The Battleboars of Brambleblade Ravine to the east are encroaching on our tribal hunting grounds. They are trained to be malicious by the Bristleback Quilboars with whom we are at war."},
    [6070]={name="Wolfskin Bracers",sourceType="quest_reward",instructions="Reward from the quest “Wolves Across the Border” — pick it over the other choices. In Northshire Valley.",zone="Northshire Valley",questName="Wolves Across the Border",lore="I hate those nasty timber wolves! But I sure like eating wolf steaks... Bring me tough wolf meat and I will exchange it for something you'll find useful."},
    [6085]={name="Footman Tunic",sourceType="quest_reward",instructions="Reward from the quest “Wanted:  \"Hogger\"” — pick it over the other choices. In Elwynn Forest.",zone="Elwynn Forest",questName="Wanted:  \"Hogger\"",lore="Wanted: Hogger A huge gnoll, Hogger, is prowling the woods in southwestern Elwynn. He has overpowered all attempts at his capture. The Stormwind Army has placed a generous bounty on the Gnoll."},
    [6201]={name="Lithe Boots",sourceType="world_drop",instructions="Drops from Morgaine the Sly (rare spawn) in Goldshire.",zone="Goldshire",npc="Morgaine the Sly"},
    [6215]={name="Balanced Fighting Stick",sourceType="quest_reward",instructions="Reward from the quest “Wanted:  \"Hogger\"” — pick it over the other choices. In Elwynn Forest.",zone="Elwynn Forest",questName="Wanted:  \"Hogger\"",lore="Wanted: Hogger A huge gnoll, Hogger, is prowling the woods in southwestern Elwynn. He has overpowered all attempts at his capture. The Stormwind Army has placed a generous bounty on the Gnoll."},
    [6268]={name="Pioneer Tunic",sourceType="world_drop",instructions="World drop — drops from 380 creature types around level 8-14. Also found on the auction house."},
    [6269]={name="Pioneer Trousers",sourceType="world_drop",instructions="World drop — drops from 466 creature types around level 6-14. Also found on the auction house."},
    [6511]={name="Journeyman's Robe",sourceType="world_drop",instructions="World drop — drops from 401 creature types around level 6-14. Also found on the auction house."},
    [6514]={name="Disciple's Cloak",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 5-14. Also found on the auction house."},
    [6518]={name="Pioneer Boots",sourceType="world_drop",instructions="World drop — drops from 416 creature types around level 5-14. Also found on the auction house."},
    [6521]={name="Pioneer Gloves",sourceType="world_drop",instructions="World drop — drops from 416 creature types around level 5-14. Also found on the auction house."},
    [7277]={name="Handstitched Leather Bracers",sourceType="profession",instructions="Crafted with Leatherworking (requires skill 1).",profession="Leatherworking"},
    [7280]={name="Rugged Leather Pants",sourceType="profession",instructions="Crafted with Leatherworking (requires skill 1).",profession="Leatherworking"},
    [8177]={name="Practice Sword",sourceType="world_drop",instructions="World drop — drops from 168 creature types around level 5-9. Also found on the auction house."},
    [8178]={name="Training Sword",sourceType="world_drop",instructions="World drop — drops from 339 creature types around level 6-14. Also found on the auction house."},
    [8179]={name="Cadet's Bow",sourceType="world_drop",instructions="World drop — drops from 314 creature types around level 5-14. Also found on the auction house."},
    [8180]={name="Hunting Bow",sourceType="world_drop",instructions="World drop — drops from 401 creature types around level 6-14. Also found on the auction house."},
    [8181]={name="Hunting Rifle",sourceType="world_drop",instructions="World drop — drops from 314 creature types around level 5-14. Also found on the auction house."},
    [8182]={name="Pellet Rifle",sourceType="world_drop",instructions="World drop — drops from 168 creature types around level 5-9. Also found on the auction house."},
    [9598]={name="Sleeping Robes",sourceType="quest_reward",instructions="Reward from the quest “Druid of the Claw” — pick it over the other choices. In Teldrassil.",zone="Teldrassil",questName="Druid of the Claw",lore="After examining this charm, I see now what must be done. Please take it, and do as I ask. You are to explore the deepest areas of the Ban'ethil Barrow Den."},
    [9601]={name="Cushioned Boots",sourceType="quest_reward",instructions="Reward from the quest “Sathrah's Sacrifice” — pick it over the other choices. In Darnassus.",zone="Darnassus",questName="Sathrah's Sacrifice",lore="Now you must finish the task to which you have been appointed. Take the spinnerets and offer Lady Sathrah's sacrifice to Elune; lay the great spider to rest."},
    [9603]={name="Gritroot Staff",sourceType="quest_reward",instructions="Reward from the quest “The Relics of Wakening” — pick it over the other choices. In Teldrassil.",zone="Teldrassil",questName="The Relics of Wakening",lore="Gnarlpine invaders were seen ravaging the Ban'ethil Barrow Den to the west. The slumbering druids will be trapped in the Emerald Dream for eternity, unaware of their fate, unless we help."},
    [9745]={name="Simple Cape",sourceType="world_drop",instructions="World drop — drops from 416 creature types around level 5-14. Also found on the auction house."},
    [9750]={name="Gypsy Sash",sourceType="world_drop",instructions="World drop — drops from 435 creature types around level 6-14. Also found on the auction house."},
    [9751]={name="Gypsy Sandals",sourceType="world_drop",instructions="World drop — drops from 435 creature types around level 6-14. Also found on the auction house."},
    [9752]={name="Gypsy Bands",sourceType="world_drop",instructions="World drop — drops from 435 creature types around level 6-14. Also found on the auction house."},
    [9754]={name="Gypsy Cloak",sourceType="world_drop",instructions="World drop — drops from 416 creature types around level 5-14. Also found on the auction house."},
    [9755]={name="Gypsy Gloves",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 8-14. Also found on the auction house."},
    [9756]={name="Gypsy Trousers",sourceType="world_drop",instructions="World drop — drops from 359 creature types around level 9-15. Also found on the auction house."},
    [10035]={name="Tuxedo Pants",sourceType="profession",instructions="Crafted with Tailoring (requires skill 1).",profession="Tailoring"},
    [14098]={name="Native Cloak",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 5-14. Also found on the auction house."},
    [15003]={name="Primal Belt",sourceType="world_drop",instructions="World drop — drops from 241 creature types around level 5-10. Also found on the auction house."},
    [15004]={name="Primal Boots",sourceType="world_drop",instructions="World drop — drops from 314 creature types around level 5-14. Also found on the auction house."},
    [15005]={name="Primal Bands",sourceType="world_drop",instructions="World drop — drops from 314 creature types around level 5-14. Also found on the auction house."},
    [15009]={name="Primal Leggings",sourceType="world_drop",instructions="World drop — drops from 401 creature types around level 6-14. Also found on the auction house."},
    [15297]={name="Grizzly Bracers",sourceType="world_drop",instructions="World drop — drops from 416 creature types around level 5-14. Also found on the auction house."},
    [15300]={name="Grizzly Gloves",sourceType="world_drop",instructions="World drop — drops from 355 creature types around level 9-15. Also found on the auction house."},
    [15301]={name="Grizzly Slippers",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 8-14. Also found on the auction house."},
    [15302]={name="Grizzly Belt",sourceType="world_drop",instructions="World drop — drops from 416 creature types around level 5-14. Also found on the auction house."},
    [15807]={name="Light Crossbow",sourceType="vendor",instructions="Bought from Marda Weller in Eastern Kingdoms.",zone="Eastern Kingdoms",npc="Marda Weller"},
    [15925]={name="Journeyman's Stave",sourceType="world_drop",instructions="World drop — drops from 339 creature types around level 6-14. Also found on the auction house."},
    [15944]={name="Ancestral Orb",sourceType="world_drop",instructions="World drop — drops from 466 creature types around level 6-14. Also found on the auction house."},
    [17922]={name="Lionfur Armor",sourceType="world_drop",instructions="Drops from The Rake (rare spawn) in Kalimdor.",zone="Kalimdor",npc="The Rake"},
    [18611]={name="Gnarlpine Leggings",sourceType="world_drop",instructions="Drops from Uruson (rare spawn) in Dolanaar.",zone="Dolanaar",npc="Uruson"},
    [20838]={name="Sunstrider Bow",sourceType="quest_reward",instructions="Reward from the quest “Felendren the Banished” — pick it over the other choices. In Sunstrider Isle.",zone="Sunstrider Isle",questName="Felendren the Banished",lore="A betrayer of our people resides atop Falthrien Academy to the southwest. Felendren is his name, and he was banished from blood elf lands for failing to heed the warnings of our teachers and elders."},
    [20839]={name="Sunstrider Staff",sourceType="quest_reward",instructions="Reward from the quest “Aggression” — pick it over the other choices. In Sunstrider Isle.",zone="Sunstrider Isle",questName="Aggression",lore="Before sending you to the Academy, I want you on another task that needs to be dealt with immediately. Once used to aid us in the gardening of Sunstrider Isle, the bestial tenders now have grown out of our control."},
    [20910]={name="Stiff Shortbow",sourceType="vendor",instructions="Bought from Raelis Dawnstar in The Sunspire.",zone="The Sunspire",npc="Raelis Dawnstar"},
    [20921]={name="Sun Cured Boots",sourceType="vendor",instructions="Bought from Jainthess Thelryn in The Sunspire.",zone="The Sunspire",npc="Jainthess Thelryn"},
    [20922]={name="Sun Cured Bracers",sourceType="vendor",instructions="Bought from Jainthess Thelryn in The Sunspire.",zone="The Sunspire",npc="Jainthess Thelryn"},
    [20925]={name="Sun Cured Vest",sourceType="vendor",instructions="Bought from Jainthess Thelryn in The Sunspire.",zone="The Sunspire",npc="Jainthess Thelryn"},
    [22784]={name="Sunwell Orb",sourceType="quest_reward",instructions="Reward from the quest “The Twin Ziggurats” — pick it over the other choices. In Ghostlands.",zone="Ghostlands",questName="The Twin Ziggurats",lore="These were imbued with the magical energies of the Sunwell and attuned to have warding powers against the Scourge."},
    [22951]={name="Springpaw Hide Leggings",sourceType="quest_reward",instructions="Reward from the quest “Pelt Collection” — pick it over the other choices. In Eversong Woods.",zone="Eversong Woods",questName="Pelt Collection",lore="The springpaw that inhabit this region are known for their high quality pelts."},
    [23323]={name="Crown of the Fire Festival",sourceType="quest_reward",instructions="Reward from the quest “A Thief's Reward”.",questName="A Thief's Reward",lore="This flame, stolen from the heart of Stormwind itself, floods you with warmth. This raw power is foreign to you, but the (NAME) might know more..."},
    [23324]={name="Mantle of the Fire Festival",sourceType="quest_reward",instructions="Reward from the quest “Wild Fires in the Eastern Kingdoms”.",questName="Wild Fires in the Eastern Kingdoms",lore="Our celebration of the flame is spread throughout the land. Not a single place remains untouched by the heat of this holiday, and the strongest fires burn a brilliant blue."},
    [23404]={name="Padded Running Shoes",sourceType="quest_reward",instructions="Reward from the quest “Windrunner Village” — pick it over the other choices. In Ghostlands.",zone="Ghostlands",questName="Windrunner Village",lore="the final battle against the Ghostlands villages is upon you. Windrunner Village to the southwest has been overrun by a large force of the more powerful Scourge shocktroopers; shades and gargoyles."},
    [23405]={name="Farstrider's Tunic",sourceType="quest_reward",instructions="Reward from the quest “Report to Captain Helios” — pick it over the other choices. In Ghostlands.",zone="Ghostlands",questName="Report to Captain Helios",lore="I need one last favor of you. Just in case Ranger Salissa didn't make it back to Farstrider Enclave on the south edge of the lake, I need you to go there and get help."},
    [24109]={name="Thick Ravager Belt",sourceType="quest_reward",instructions="Reward from the quest “Beasts of the Apocalypse!” — pick it over the other choices. In Azuremyst Isle.",zone="Azuremyst Isle",questName="Beasts of the Apocalypse!",lore="My brother and I were hunting in the woods to the east when we were ambushed by strange, insect-like beasts. Such aberrations have never before been seen in Azuremyst!"},
    [24111]={name="Kurken Hide Jerkin",sourceType="quest_reward",instructions="Reward from the quest “The Kurken's Hide” — pick it over the other choices. In Azuremyst Isle.",zone="Azuremyst Isle",questName="The Kurken's Hide",lore="Take the Kurken's hide to Moordo, on the other side of the village."},
    [24112]={name="Kurkenstoks",sourceType="quest_reward",instructions="Reward from the quest “The Kurken's Hide” — pick it over the other choices. In Azuremyst Isle.",zone="Azuremyst Isle",questName="The Kurken's Hide",lore="Take the Kurken's hide to Moordo, on the other side of the village. He will fashion the hide into an item of your choice."},
    [24113]={name="Cowlen's Bracers of Kinship",sourceType="quest_reward",instructions="Reward from the quest “A Cry For Help”. In Azuremyst Isle.",zone="Azuremyst Isle",questName="A Cry For Help",lore="My family was attacked by the murlocs and owlkin of this island several weeks ago. I managed to escape but I think that both my mother and father have been slain."},
    [24433]={name="Crossbow of the Albatross",sourceType="quest_reward",instructions="Reward from the quest “Show Gnomercy” — pick it over the other choices. In Azuremyst Isle.",zone="Azuremyst Isle",questName="Show Gnomercy",lore="Spark must be brought to justice! I need you to go down to the beach and find that deceitful gnome. Once you find him, get whatever information you can out of him!"},
    [24439]={name="Savage Leggings",sourceType="quest_reward",instructions="Reward from the quest “Gurf's Dignity” — pick it over the other choices. In Azuremyst Isle.",zone="Azuremyst Isle",questName="Gurf's Dignity",lore="You recover the piece of fur that Gurf had \"lost\" in his struggle with the murlocs. Return the fur to Gurf and let him know that the fearsome Murgurgula has been slain."},
    [24441]={name="Exodar Crossbow",sourceType="quest_reward",instructions="Reward from the quest “Blood Elf Spy” — pick it over the other choices. In Ammen Vale.",zone="Ammen Vale",questName="Blood Elf Spy",lore="I have a plan. We must kill their leader. Without their master, perhaps they will retreat to regroup. We just need to buy time until the repairs are completed."},
    [27401]={name="Arugoo's Crossbow of Destruction",sourceType="quest_reward",instructions="Reward from the quest “The Prophecy of Akida” — pick it over the other choices. In Azuremyst Isle.",zone="Azuremyst Isle",questName="The Prophecy of Akida",lore="The images on this totem depict a war between the Stillpine and the Bristlelimb furbolg tribes. The etchings show that the Bristlelimb have done unconscionable things to the furbolgs of Stillpine."},
    [28144]={name="Troll Handler Gloves",sourceType="quest_reward",instructions="Reward from the quest “Report to Captain Helios” — pick it over the other choices. In Ghostlands.",zone="Ghostlands",questName="Report to Captain Helios",lore="I need one last favor of you. Just in case Ranger Salissa didn't make it back to Farstrider Enclave on the south edge of the lake, I need you to go there and get help."},
    [28146]={name="Courier's Wraps",sourceType="quest_reward",instructions="Reward from the quest “Delivery to Tranquillien” — pick it over the other choices. In Ghostlands.",zone="Ghostlands",questName="Delivery to Tranquillien",lore="I... I'm too weak to continue. I carry a dire warning from Regent Lord Theron, in the form of a letter. You'll have to deliver it for me. Take it to Arcanist Vandril in Tranquillien."},
    [28147]={name="Tranquillien Scout's Bracers",sourceType="quest_reward",instructions="Reward from the quest “Delivery to Tranquillien” — pick it over the other choices. In Ghostlands.",zone="Ghostlands",questName="Delivery to Tranquillien",lore="You'll have to deliver it for me. Take it to Arcanist Vandril in Tranquillien."},
    [28149]={name="Tranquillien Breeches",sourceType="quest_reward",instructions="Reward from the quest “Anok'suten” — pick it over the other choices. In Ghostlands.",zone="Ghostlands",questName="Anok'suten",lore="Come closer, I am... dying. I was sent here... to slay these nerubians, but Vandril didn't... know that they have a leader. You must find and..."},
}

GQ.Data.hunterEarly1to9 = {
    {2570,"Back",1,2,1,0.03,faction="Alliance"},
    {1376,"Back",1,2,2,0.03,faction="Alliance"},
    {1429,"Back",1,2,3,0.03,faction="Alliance"},
    {4658,"Back",3,3,1,0.04,faction="Alliance"},
    {4662,"Back",3,3,2,0.04,faction="Alliance"},
    {4665,"Back",3,3,3,0.04,faction="Alliance"},
    {3008,"Back",4,4,1,0.04,faction="Alliance"},
    {4668,"Back",4,4,2,0.04,faction="Alliance"},
    {4671,"Back",4,4,3,0.04,faction="Alliance"},
    {1421,"Back",5,5,1,0.04,faction="Alliance"},
    {2905,"Back",5,5,2,0.04,faction="Alliance"},
    {6514,"Back",5,5,3,0.04,faction="Alliance"},
    {5591,"Back",6,6,1,0.05,faction="Alliance"},
    {9745,"Back",6,6,2,0.05,faction="Alliance"},
    {9754,"Back",6,6,3,0.05,faction="Alliance"},
    {2580,"Back",7,7,1,0.06,faction="Alliance"},
    {3331,"Back",7,7,2,0.06,faction="Alliance"},
    {4677,"Back",7,7,3,0.06,faction="Alliance"},
    {2310,"Back",8,8,1,0.06,faction="Alliance"},
    {4680,"Back",8,8,2,0.06,faction="Alliance"},
    {4683,"Back",8,8,3,0.06,faction="Alliance"},
    {1497,"Back",9,9,1,0.06,faction="Alliance"},
    {2310,"Back",9,9,2,0.06,faction="Alliance"},
    {4680,"Back",9,9,3,0.06,faction="Alliance"},
    {2127,"Chest",1,1,1,0.16,faction="Alliance"},
    {4907,"Chest",1,1,2,0.16,faction="Alliance"},
    {6059,"Chest",1,1,3,0.16,faction="Alliance"},
    {60,"Chest",2,2,1,0.16,faction="Alliance"},
    {2127,"Chest",2,2,2,0.16,faction="Alliance"},
    {4907,"Chest",2,2,3,0.16,faction="Alliance"},
    {5957,"Chest",3,3,1,0.22,faction="Alliance"},
    {60,"Chest",3,3,2,0.16,faction="Alliance"},
    {2127,"Chest",3,3,3,0.16,faction="Alliance"},
    {2112,"Chest",4,4,1,0.24,faction="Alliance"},
    {1425,"Chest",4,4,2,0.22,faction="Alliance"},
    {5957,"Chest",4,4,3,0.22,faction="Alliance"},
    {3000,"Chest",5,6,1,0.61,faction="Alliance"},
    {17922,"Chest",5,6,2,0.41,faction="Alliance"},
    {9598,"Chest",5,6,3,0.41,faction="Alliance"},
    {24111,"Chest",7,7,1,1.24,faction="Alliance"},
    {2300,"Chest",7,7,2,0.98,faction="Alliance"},
    {2817,"Chest",7,7,3,0.98,faction="Alliance"},
    {3288,"Chest",8,9,1,2.59,faction="Alliance"},
    {821,"Chest",8,9,2,1.96,faction="Alliance"},
    {6085,"Chest",8,9,3,1.96,faction="Alliance"},
    {2123,"Feet",1,2,1,0.11,faction="Alliance"},
    {20921,"Feet",1,2,2,0.11,faction="Alliance"},
    {1367,"Feet",1,2,3,0.08,faction="Alliance"},
    {2302,"Feet",3,3,1,0.15,faction="Alliance"},
    {1419,"Feet",3,3,2,0.14,faction="Alliance"},
    {2123,"Feet",3,3,3,0.11,faction="Alliance"},
    {2963,"Feet",4,4,1,0.16,faction="Alliance"},
    {3321,"Feet",4,4,2,0.16,faction="Alliance"},
    {15004,"Feet",4,4,3,0.16,faction="Alliance"},
    {796,"Feet",5,5,1,0.17,faction="Alliance"},
    {6201,"Feet",5,5,2,0.17,faction="Alliance"},
    {2963,"Feet",5,5,3,0.16,faction="Alliance"},
    {6518,"Feet",6,6,1,0.18,faction="Alliance"},
    {796,"Feet",6,6,2,0.17,faction="Alliance"},
    {1173,"Feet",6,6,3,0.17,faction="Alliance"},
    {24112,"Feet",7,7,1,0.38,faction="Alliance"},
    {3284,"Feet",7,7,2,0.19,faction="Alliance"},
    {9601,"Feet",7,7,3,0.19,faction="Alliance"},
    {24112,"Feet",8,8,1,0.38,faction="Alliance"},
    {15301,"Feet",8,8,2,0.2,faction="Alliance"},
    {3284,"Feet",8,8,3,0.19,faction="Alliance"},
    {24112,"Feet",9,9,1,0.38,faction="Alliance"},
    {2975,"Feet",9,9,2,0.22,faction="Alliance"},
    {15301,"Feet",9,9,3,0.2,faction="Alliance"},
    {1422,"Hands",1,4,1,0.11,faction="Alliance"},
    {2125,"Hands",1,4,2,0.1,faction="Alliance"},
    {5394,"Hands",1,4,3,0.1,faction="Alliance"},
    {797,"Hands",5,5,1,0.16,faction="Alliance"},
    {1965,"Hands",5,5,2,0.16,faction="Alliance"},
    {2964,"Hands",5,5,3,0.16,faction="Alliance"},
    {6521,"Hands",6,6,1,0.17,faction="Alliance"},
    {797,"Hands",6,6,2,0.16,faction="Alliance"},
    {1965,"Hands",6,6,3,0.16,faction="Alliance"},
    {3286,"Hands",7,7,1,0.18,faction="Alliance"},
    {6521,"Hands",7,7,2,0.17,faction="Alliance"},
    {797,"Hands",7,7,3,0.16,faction="Alliance"},
    {4239,"Hands",8,8,1,0.19,faction="Alliance"},
    {9755,"Hands",8,8,2,0.19,faction="Alliance"},
    {3286,"Hands",8,8,3,0.18,faction="Alliance"},
    {15300,"Hands",9,9,1,0.2,faction="Alliance"},
    {4239,"Hands",9,9,2,0.19,faction="Alliance"},
    {9755,"Hands",9,9,3,0.19,faction="Alliance"},
    {23323,"Head",1,9,1,0.01,faction="Alliance"},
    {10035,"Legs",1,1,1,0.18,faction="Alliance"},
    {61,"Legs",1,1,2,0.14,faction="Alliance"},
    {2126,"Legs",1,1,3,0.14,faction="Alliance"},
    {10035,"Legs",2,4,1,0.18,faction="Alliance"},
    {18611,"Legs",2,4,2,0.17,faction="Alliance"},
    {1423,"Legs",2,4,3,0.16,faction="Alliance"},
    {2962,"Legs",5,5,1,1.2,faction="Alliance"},
    {798,"Legs",5,5,2,0.22,faction="Alliance"},
    {2303,"Legs",5,5,3,0.22,faction="Alliance"},
    {2962,"Legs",6,6,1,1.2,faction="Alliance"},
    {15009,"Legs",6,6,2,0.92,faction="Alliance",suffix="of Agility",suffixChance=9.2,suffixId=17,suffixRange="+1-2 Agility"},
    {7280,"Legs",6,6,3,0.59,faction="Alliance"},
    {24439,"Legs",7,7,1,1.56,faction="Alliance"},
    {3287,"Legs",7,7,2,1.28,faction="Alliance"},
    {2962,"Legs",7,7,3,1.2,faction="Alliance"},
    {24439,"Legs",8,9,1,1.56,faction="Alliance"},
    {5617,"Legs",8,9,2,1.34,faction="Alliance"},
    {3287,"Legs",8,9,3,1.28,faction="Alliance"},
    {5581,"MainHand",1,1,1,16.38,faction="Alliance",route="twohand"},
    {5777,"MainHand",1,1,2,16.38,faction="Alliance",route="twohand"},
    {5776,"MainHand",1,1,3,15.42,faction="Alliance",route="twohand"},
    {8177,"MainHand",2,2,1,22.5,faction="Alliance",route="twohand"},
    {2489,"MainHand",2,2,2,21.72,faction="Alliance",route="twohand"},
    {1412,"MainHand",2,2,3,17.82,faction="Alliance",route="twohand"},
    {1010,"MainHand",3,3,1,25.74,faction="Alliance",route="twohand"},
    {2491,"MainHand",3,3,2,25.74,faction="Alliance",route="twohand"},
    {3189,"MainHand",3,3,3,25.44,faction="Alliance",route="twohand"},
    {3325,"MainHand",4,4,1,30.0,faction="Alliance",route="twohand"},
    {3327,"MainHand",4,4,2,30.0,faction="Alliance",route="twohand"},
    {1010,"MainHand",4,4,3,25.74,faction="Alliance",route="twohand"},
    {8178,"MainHand",5,6,1,43.84,faction="Alliance",suffix="of Agility",suffixChance=5.9,suffixId=93,suffixRange="+3-4 Agility",route="twohand"},
    {4562,"MainHand",5,6,2,43.03,faction="Alliance",suffix="of Agility",suffixChance=5.7,suffixId=93,suffixRange="+3-4 Agility",route="twohand"},
    {9603,"MainHand",5,6,3,41.87,faction="Alliance",route="twohand"},
    {3192,"MainHand",7,7,1,50.98,faction="Alliance",suffix="of Agility",suffixChance=5.9,suffixId=93,suffixRange="+3-4 Agility",route="twohand"},
    {8178,"MainHand",7,7,2,43.84,faction="Alliance",suffix="of Agility",suffixChance=5.9,suffixId=93,suffixRange="+3-4 Agility",route="twohand"},
    {4562,"MainHand",7,7,3,43.03,faction="Alliance",suffix="of Agility",suffixChance=5.7,suffixId=93,suffixRange="+3-4 Agility",route="twohand"},
    {6215,"MainHand",8,9,1,55.86,faction="Alliance",route="twohand"},
    {3488,"MainHand",8,9,2,55.41,faction="Alliance",route="twohand"},
    {4566,"MainHand",8,9,3,53.58,faction="Alliance",route="twohand"},
    {8179,"Ranged",1,1,1,48.0,faction="Alliance"},
    {2505,"Ranged",1,1,2,45.0,faction="Alliance"},
    {20910,"Ranged",1,1,3,45.0,faction="Alliance"},
    {8182,"Ranged",2,2,1,53.04,faction="Alliance"},
    {8179,"Ranged",2,2,2,48.0,faction="Alliance"},
    {24441,"Ranged",2,2,3,48.0,faction="Alliance"},
    {15807,"Ranged",3,3,1,55.2,faction="Alliance"},
    {2506,"Ranged",3,3,2,54.24,faction="Alliance"},
    {8182,"Ranged",3,3,3,53.04,faction="Alliance"},
    {8181,"Ranged",4,4,1,60.0,faction="Alliance"},
    {15807,"Ranged",4,4,2,55.2,faction="Alliance"},
    {2506,"Ranged",4,4,3,54.24,faction="Alliance"},
    {4362,"Ranged",5,5,1,75.6,faction="Alliance"},
    {24433,"Ranged",5,5,2,67.2,faction="Alliance"},
    {8181,"Ranged",5,5,3,60.0,faction="Alliance"},
    {8180,"Ranged",6,7,1,83.04,faction="Alliance"},
    {4362,"Ranged",6,7,2,75.6,faction="Alliance"},
    {5596,"Ranged",6,7,3,74.28,faction="Alliance"},
    {4577,"Ranged",8,9,1,96.0,faction="Alliance"},
    {27401,"Ranged",8,9,2,88.84,faction="Alliance"},
    {8180,"Ranged",8,9,3,83.04,faction="Alliance"},
    {15925,"SecondaryHand",5,6,1,0.35,faction="Alliance",route="twohand"},
    {15925,"SecondaryHand",7,9,1,0.35,faction="Alliance",route="twohand"},
    {15944,"SecondaryHand",7,9,2,0.15,faction="Alliance",route="twohand"},
    {23324,"Shoulder",1,9,1,0.01,faction="Alliance"},
    {4951,"Waist",1,1,1,0.11,faction="Alliance"},
    {2122,"Waist",1,1,2,0.09,faction="Alliance"},
    {2186,"Waist",1,1,3,0.09,faction="Alliance"},
    {4951,"Waist",2,2,1,0.11,faction="Alliance"},
    {1418,"Waist",2,2,2,0.11,faction="Alliance"},
    {2122,"Waist",2,2,3,0.09,faction="Alliance"},
    {15003,"Waist",3,3,1,0.12,faction="Alliance"},
    {4951,"Waist",3,3,2,0.11,faction="Alliance"},
    {1418,"Waist",3,3,3,0.11,faction="Alliance"},
    {4666,"Waist",4,4,1,0.13,faction="Alliance"},
    {15003,"Waist",4,4,2,0.12,faction="Alliance"},
    {4951,"Waist",4,4,3,0.11,faction="Alliance"},
    {1839,"Waist",5,5,1,0.14,faction="Alliance"},
    {4237,"Waist",5,5,2,0.14,faction="Alliance"},
    {4675,"Waist",5,5,3,0.14,faction="Alliance"},
    {15302,"Waist",6,6,1,0.15,faction="Alliance"},
    {1839,"Waist",6,6,2,0.14,faction="Alliance"},
    {4237,"Waist",6,6,3,0.14,faction="Alliance"},
    {24109,"Waist",7,7,1,0.19,faction="Alliance"},
    {9750,"Waist",7,7,2,0.16,faction="Alliance"},
    {15302,"Waist",7,7,3,0.15,faction="Alliance"},
    {24109,"Waist",8,8,1,0.19,faction="Alliance"},
    {4690,"Waist",8,8,2,0.17,faction="Alliance"},
    {9750,"Waist",8,8,3,0.16,faction="Alliance"},
    {24109,"Waist",9,9,1,0.19,faction="Alliance"},
    {4693,"Waist",9,9,2,0.18,faction="Alliance"},
    {1502,"Waist",9,9,3,0.17,faction="Alliance"},
    {2124,"Wrist",1,2,1,0.07,faction="Alliance"},
    {4908,"Wrist",1,2,2,0.07,faction="Alliance"},
    {6070,"Wrist",1,2,3,0.07,faction="Alliance"},
    {3200,"Wrist",3,3,1,0.1,faction="Alliance"},
    {2124,"Wrist",3,3,2,0.07,faction="Alliance"},
    {4908,"Wrist",3,3,3,0.07,faction="Alliance"},
    {7277,"Wrist",4,4,1,0.1,faction="Alliance"},
    {15005,"Wrist",4,4,2,0.1,faction="Alliance"},
    {1420,"Wrist",4,4,3,0.1,faction="Alliance"},
    {1840,"Wrist",5,5,1,0.11,faction="Alliance"},
    {2327,"Wrist",5,5,2,0.11,faction="Alliance"},
    {3285,"Wrist",5,5,3,0.11,faction="Alliance"},
    {24113,"Wrist",6,6,1,0.36,faction="Alliance"},
    {15297,"Wrist",6,6,2,0.12,faction="Alliance"},
    {1504,"Wrist",6,6,3,0.11,faction="Alliance"},
    {24113,"Wrist",7,7,1,0.36,faction="Alliance"},
    {763,"Wrist",7,7,2,0.13,faction="Alliance"},
    {9752,"Wrist",7,7,3,0.13,faction="Alliance"},
    {24113,"Wrist",8,8,1,0.36,faction="Alliance"},
    {3312,"Wrist",8,8,2,0.13,faction="Alliance"},
    {763,"Wrist",8,8,3,0.13,faction="Alliance"},
    {24113,"Wrist",9,9,1,0.36,faction="Alliance"},
    {1213,"Wrist",9,9,2,0.14,faction="Alliance"},
    {3207,"Wrist",9,9,3,0.14,faction="Alliance"},
    {2570,"Back",1,2,1,0.03,faction="Horde"},
    {3322,"Back",1,2,2,0.03,faction="Horde"},
    {1376,"Back",1,2,3,0.03,faction="Horde"},
    {4658,"Back",3,3,1,0.04,faction="Horde"},
    {4662,"Back",3,3,2,0.04,faction="Horde"},
    {4665,"Back",3,3,3,0.04,faction="Horde"},
    {4668,"Back",4,4,1,0.04,faction="Horde"},
    {4671,"Back",4,4,2,0.04,faction="Horde"},
    {4674,"Back",4,4,3,0.04,faction="Horde"},
    {1421,"Back",5,5,1,0.04,faction="Horde"},
    {6514,"Back",5,5,2,0.04,faction="Horde"},
    {14098,"Back",5,5,3,0.04,faction="Horde"},
    {4772,"Back",6,6,1,0.05,faction="Horde"},
    {4854,"Back",6,6,2,0.05,faction="Horde"},
    {9745,"Back",6,6,3,0.05,faction="Horde"},
    {2580,"Back",7,7,1,0.06,faction="Horde"},
    {3331,"Back",7,7,2,0.06,faction="Horde"},
    {4677,"Back",7,7,3,0.06,faction="Horde"},
    {2310,"Back",8,8,1,0.06,faction="Horde"},
    {4680,"Back",8,8,2,0.06,faction="Horde"},
    {4683,"Back",8,8,3,0.06,faction="Horde"},
    {1497,"Back",9,9,1,0.06,faction="Horde"},
    {2310,"Back",9,9,2,0.06,faction="Horde"},
    {4680,"Back",9,9,3,0.06,faction="Horde"},
    {85,"Chest",1,2,1,0.16,faction="Horde"},
    {6059,"Chest",1,2,2,0.16,faction="Horde"},
    {20925,"Chest",1,2,3,0.16,faction="Horde"},
    {5957,"Chest",3,3,1,0.22,faction="Horde"},
    {85,"Chest",3,3,2,0.16,faction="Horde"},
    {6059,"Chest",3,3,3,0.16,faction="Horde"},
    {2112,"Chest",4,4,1,0.24,faction="Horde"},
    {1425,"Chest",4,4,2,0.22,faction="Horde"},
    {5957,"Chest",4,4,3,0.22,faction="Horde"},
    {4861,"Chest",5,5,1,1.24,faction="Horde"},
    {17922,"Chest",5,5,2,0.41,faction="Horde"},
    {799,"Chest",5,5,3,0.25,faction="Horde"},
    {4861,"Chest",6,6,1,1.24,faction="Horde"},
    {17922,"Chest",6,6,2,0.41,faction="Horde"},
    {6511,"Chest",6,6,3,0.37,faction="Horde"},
    {4861,"Chest",7,7,1,1.24,faction="Horde"},
    {2300,"Chest",7,7,2,0.98,faction="Horde"},
    {17922,"Chest",7,7,3,0.41,faction="Horde"},
    {3288,"Chest",8,8,1,2.59,faction="Horde"},
    {821,"Chest",8,8,2,1.96,faction="Horde"},
    {6268,"Chest",8,8,3,1.53,faction="Horde",suffix="of Agility",suffixChance=10.9,suffixId=93,suffixRange="+3-4 Agility"},
    {3288,"Chest",9,9,1,2.59,faction="Horde"},
    {821,"Chest",9,9,2,1.96,faction="Horde"},
    {23405,"Chest",9,9,3,1.61,faction="Horde"},
    {210,"Feet",1,2,1,0.11,faction="Horde"},
    {20921,"Feet",1,2,2,0.11,faction="Horde"},
    {1367,"Feet",1,2,3,0.08,faction="Horde"},
    {2302,"Feet",3,3,1,0.15,faction="Horde"},
    {1419,"Feet",3,3,2,0.14,faction="Horde"},
    {4906,"Feet",3,3,3,0.14,faction="Horde"},
    {2963,"Feet",4,4,1,0.16,faction="Horde"},
    {3321,"Feet",4,4,2,0.16,faction="Horde"},
    {15004,"Feet",4,4,3,0.16,faction="Horde"},
    {796,"Feet",5,5,1,0.17,faction="Horde"},
    {2373,"Feet",5,5,2,0.17,faction="Horde"},
    {6201,"Feet",5,5,3,0.17,faction="Horde"},
    {6518,"Feet",6,6,1,0.18,faction="Horde"},
    {796,"Feet",6,6,2,0.17,faction="Horde"},
    {2373,"Feet",6,6,3,0.17,faction="Horde"},
    {3284,"Feet",7,7,1,0.19,faction="Horde"},
    {4942,"Feet",7,7,2,0.19,faction="Horde"},
    {9751,"Feet",7,7,3,0.19,faction="Horde"},
    {15301,"Feet",8,8,1,0.2,faction="Horde"},
    {3284,"Feet",8,8,2,0.19,faction="Horde"},
    {4942,"Feet",8,8,3,0.19,faction="Horde"},
    {23404,"Feet",9,9,1,2.17,faction="Horde"},
    {2975,"Feet",9,9,2,0.22,faction="Horde"},
    {15301,"Feet",9,9,3,0.2,faction="Horde"},
    {1422,"Hands",1,3,1,0.11,faction="Horde"},
    {714,"Hands",1,3,2,0.1,faction="Horde"},
    {4914,"Hands",1,3,3,0.1,faction="Horde"},
    {4962,"Hands",4,4,1,0.14,faction="Horde"},
    {1422,"Hands",4,4,2,0.11,faction="Horde"},
    {714,"Hands",4,4,3,0.1,faction="Horde"},
    {797,"Hands",5,5,1,0.16,faction="Horde"},
    {1965,"Hands",5,5,2,0.16,faction="Horde"},
    {2375,"Hands",5,5,3,0.16,faction="Horde"},
    {6521,"Hands",6,6,1,0.17,faction="Horde"},
    {797,"Hands",6,6,2,0.16,faction="Horde"},
    {1965,"Hands",6,6,3,0.16,faction="Horde"},
    {3286,"Hands",7,7,1,0.18,faction="Horde"},
    {6521,"Hands",7,7,2,0.17,faction="Horde"},
    {797,"Hands",7,7,3,0.16,faction="Horde"},
    {4239,"Hands",8,8,1,0.19,faction="Horde"},
    {9755,"Hands",8,8,2,0.19,faction="Horde"},
    {3286,"Hands",8,8,3,0.18,faction="Horde"},
    {28144,"Hands",9,9,1,0.22,faction="Horde"},
    {15300,"Hands",9,9,2,0.2,faction="Horde"},
    {4239,"Hands",9,9,3,0.19,faction="Horde"},
    {23323,"Head",1,9,1,0.01,faction="Horde"},
    {10035,"Legs",1,1,1,0.18,faction="Horde"},
    {209,"Legs",1,1,2,0.14,faction="Horde"},
    {4921,"Legs",1,1,3,0.14,faction="Horde"},
    {10035,"Legs",2,3,1,0.18,faction="Horde"},
    {18611,"Legs",2,3,2,0.17,faction="Horde"},
    {1423,"Legs",2,3,3,0.16,faction="Horde"},
    {10035,"Legs",4,4,1,0.18,faction="Horde"},
    {18611,"Legs",4,4,2,0.17,faction="Horde"},
    {22951,"Legs",4,4,3,0.17,faction="Horde"},
    {2962,"Legs",5,5,1,1.2,faction="Horde"},
    {798,"Legs",5,5,2,0.22,faction="Horde"},
    {2303,"Legs",5,5,3,0.22,faction="Horde"},
    {2962,"Legs",6,6,1,1.2,faction="Horde"},
    {15009,"Legs",6,6,2,0.92,faction="Horde",suffix="of Agility",suffixChance=9.2,suffixId=17,suffixRange="+1-2 Agility"},
    {7280,"Legs",6,6,3,0.59,faction="Horde"},
    {3287,"Legs",7,8,1,1.28,faction="Horde"},
    {2962,"Legs",7,8,2,1.2,faction="Horde"},
    {6269,"Legs",7,8,3,0.94,faction="Horde",suffix="of Agility",suffixChance=9.2,suffixId=17,suffixRange="+1-2 Agility"},
    {28149,"Legs",9,9,1,1.56,faction="Horde"},
    {3287,"Legs",9,9,2,1.28,faction="Horde"},
    {9756,"Legs",9,9,3,1.28,faction="Horde",suffix="of Agility",suffixChance=8.4,suffixId=93,suffixRange="+3-4 Agility"},
    {5777,"MainHand",1,1,1,16.38,faction="Horde",route="twohand"},
    {5778,"MainHand",1,1,2,15.48,faction="Horde",route="twohand"},
    {20839,"MainHand",1,1,3,15.48,faction="Horde",route="twohand"},
    {8177,"MainHand",2,2,1,22.5,faction="Horde",route="twohand"},
    {2489,"MainHand",2,2,2,21.72,faction="Horde",route="twohand"},
    {1412,"MainHand",2,2,3,17.82,faction="Horde",route="twohand"},
    {2491,"MainHand",3,3,1,25.74,faction="Horde",route="twohand"},
    {3189,"MainHand",3,3,2,25.44,faction="Horde",route="twohand"},
    {767,"MainHand",3,3,3,25.2,faction="Horde",route="twohand"},
    {3325,"MainHand",4,4,1,30.0,faction="Horde",route="twohand"},
    {3327,"MainHand",4,4,2,30.0,faction="Horde",route="twohand"},
    {2491,"MainHand",4,4,3,25.74,faction="Horde",route="twohand"},
    {8178,"MainHand",5,5,1,43.84,faction="Horde",suffix="of Agility",suffixChance=5.9,suffixId=93,suffixRange="+3-4 Agility",route="twohand"},
    {4562,"MainHand",5,5,2,43.03,faction="Horde",suffix="of Agility",suffixChance=5.7,suffixId=93,suffixRange="+3-4 Agility",route="twohand"},
    {2067,"MainHand",5,5,3,34.44,faction="Horde",route="twohand"},
    {4939,"MainHand",6,6,1,47.54,faction="Horde",route="twohand"},
    {8178,"MainHand",6,6,2,43.84,faction="Horde",suffix="of Agility",suffixChance=5.9,suffixId=93,suffixRange="+3-4 Agility",route="twohand"},
    {4562,"MainHand",6,6,3,43.03,faction="Horde",suffix="of Agility",suffixChance=5.7,suffixId=93,suffixRange="+3-4 Agility",route="twohand"},
    {3192,"MainHand",7,7,1,50.98,faction="Horde",suffix="of Agility",suffixChance=5.9,suffixId=93,suffixRange="+3-4 Agility",route="twohand"},
    {4939,"MainHand",7,7,2,47.54,faction="Horde",route="twohand"},
    {8178,"MainHand",7,7,3,43.84,faction="Horde",suffix="of Agility",suffixChance=5.9,suffixId=93,suffixRange="+3-4 Agility",route="twohand"},
    {3446,"MainHand",8,9,1,55.41,faction="Horde",route="twohand"},
    {3488,"MainHand",8,9,2,55.41,faction="Horde",route="twohand"},
    {4566,"MainHand",8,9,3,53.58,faction="Horde",route="twohand"},
    {8179,"Ranged",1,1,1,48.0,faction="Horde"},
    {20838,"Ranged",1,1,2,46.92,faction="Horde"},
    {2505,"Ranged",1,1,3,45.0,faction="Horde"},
    {8182,"Ranged",2,2,1,53.04,faction="Horde"},
    {8179,"Ranged",2,2,2,48.0,faction="Horde"},
    {20838,"Ranged",2,2,3,46.92,faction="Horde"},
    {15807,"Ranged",3,3,1,55.2,faction="Horde"},
    {2506,"Ranged",3,3,2,54.24,faction="Horde"},
    {8182,"Ranged",3,3,3,53.04,faction="Horde"},
    {2509,"Ranged",4,4,1,60.0,faction="Horde"},
    {8181,"Ranged",4,4,2,60.0,faction="Horde"},
    {15807,"Ranged",4,4,3,55.2,faction="Horde"},
    {4362,"Ranged",5,5,1,75.6,faction="Horde"},
    {2509,"Ranged",5,5,2,60.0,faction="Horde"},
    {8181,"Ranged",5,5,3,60.0,faction="Horde"},
    {8180,"Ranged",6,6,1,83.04,faction="Horde"},
    {4362,"Ranged",6,6,2,75.6,faction="Horde"},
    {2509,"Ranged",6,6,3,60.0,faction="Horde"},
    {3079,"Ranged",7,7,1,85.32,faction="Horde"},
    {8180,"Ranged",7,7,2,83.04,faction="Horde"},
    {4362,"Ranged",7,7,3,75.6,faction="Horde"},
    {4577,"Ranged",8,8,1,96.0,faction="Horde"},
    {3079,"Ranged",8,8,2,85.32,faction="Horde"},
    {8180,"Ranged",8,8,3,83.04,faction="Horde"},
    {5346,"Ranged",9,9,1,101.04,faction="Horde"},
    {4577,"Ranged",9,9,2,96.0,faction="Horde"},
    {2511,"Ranged",9,9,3,91.44,faction="Horde"},
    {22784,"SecondaryHand",1,4,1,0.45,faction="Horde",route="twohand"},
    {22784,"SecondaryHand",5,6,1,0.45,faction="Horde",route="twohand"},
    {15925,"SecondaryHand",5,6,2,0.35,faction="Horde",route="twohand"},
    {22784,"SecondaryHand",7,9,1,0.45,faction="Horde",route="twohand"},
    {15925,"SecondaryHand",7,9,2,0.35,faction="Horde",route="twohand"},
    {15944,"SecondaryHand",7,9,3,0.15,faction="Horde",route="twohand"},
    {23324,"Shoulder",1,9,1,0.01,faction="Horde"},
    {4951,"Waist",1,1,1,0.11,faction="Horde"},
    {1835,"Waist",1,1,2,0.09,faction="Horde"},
    {4954,"Waist",1,1,3,0.09,faction="Horde"},
    {4951,"Waist",2,2,1,0.11,faction="Horde"},
    {1418,"Waist",2,2,2,0.11,faction="Horde"},
    {1835,"Waist",2,2,3,0.09,faction="Horde"},
    {15003,"Waist",3,3,1,0.12,faction="Horde"},
    {4951,"Waist",3,3,2,0.11,faction="Horde"},
    {1418,"Waist",3,3,3,0.11,faction="Horde"},
    {4666,"Waist",4,4,1,0.13,faction="Horde"},
    {5936,"Waist",4,4,2,0.12,faction="Horde"},
    {15003,"Waist",4,4,3,0.12,faction="Horde"},
    {1839,"Waist",5,5,1,0.14,faction="Horde"},
    {2371,"Waist",5,5,2,0.14,faction="Horde"},
    {4237,"Waist",5,5,3,0.14,faction="Horde"},
    {15302,"Waist",6,6,1,0.15,faction="Horde"},
    {1839,"Waist",6,6,2,0.14,faction="Horde"},
    {2371,"Waist",6,6,3,0.14,faction="Horde"},
    {9750,"Waist",7,7,1,0.16,faction="Horde"},
    {15302,"Waist",7,7,2,0.15,faction="Horde"},
    {1839,"Waist",7,7,3,0.14,faction="Horde"},
    {4690,"Waist",8,8,1,0.17,faction="Horde"},
    {9750,"Waist",8,8,2,0.16,faction="Horde"},
    {15302,"Waist",8,8,3,0.15,faction="Horde"},
    {4693,"Waist",9,9,1,0.18,faction="Horde"},
    {1502,"Waist",9,9,2,0.17,faction="Horde"},
    {4690,"Waist",9,9,3,0.17,faction="Horde"},
    {1836,"Wrist",1,2,1,0.07,faction="Horde"},
    {4908,"Wrist",1,2,2,0.07,faction="Horde"},
    {20922,"Wrist",1,2,3,0.07,faction="Horde"},
    {3200,"Wrist",3,3,1,0.1,faction="Horde"},
    {4928,"Wrist",3,3,2,0.1,faction="Horde"},
    {1836,"Wrist",3,3,3,0.07,faction="Horde"},
    {7277,"Wrist",4,4,1,0.1,faction="Horde"},
    {15005,"Wrist",4,4,2,0.1,faction="Horde"},
    {1420,"Wrist",4,4,3,0.1,faction="Horde"},
    {1840,"Wrist",5,5,1,0.11,faction="Horde"},
    {2374,"Wrist",5,5,2,0.11,faction="Horde"},
    {3285,"Wrist",5,5,3,0.11,faction="Horde"},
    {15297,"Wrist",6,6,1,0.12,faction="Horde"},
    {1504,"Wrist",6,6,2,0.11,faction="Horde"},
    {1840,"Wrist",6,6,3,0.11,faction="Horde"},
    {763,"Wrist",7,7,1,0.13,faction="Horde"},
    {9752,"Wrist",7,7,2,0.13,faction="Horde"},
    {15297,"Wrist",7,7,3,0.12,faction="Horde"},
    {3312,"Wrist",8,8,1,0.13,faction="Horde"},
    {763,"Wrist",8,8,2,0.13,faction="Horde"},
    {9752,"Wrist",8,8,3,0.13,faction="Horde"},
    {28147,"Wrist",9,9,1,1.09,faction="Horde"},
    {28146,"Wrist",9,9,2,0.17,faction="Horde"},
    {3207,"Wrist",9,9,3,0.14,faction="Horde"},
}
