"""Emit GQ.Data.foreverAudit from hunt_tooltips.json + a JSON summary."""
from __future__ import annotations

import json
import re
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CACHE = ROOT / "pipeline" / "data" / "forever_wowhead"
HUNT = json.loads((CACHE / "hunt_ids.json").read_text(encoding="utf-8"))
TIPS = json.loads((CACHE / "hunt_tooltips.json").read_text(encoding="utf-8"))
ADDON = ROOT / "GearQuest" / "_generated" / "Data.ForeverAudit.generated.lua"
SUMMARY = CACHE / "forever_audit.summary.json"


def lua_str(s: str) -> str:
    s = str(s or "")
    for a, b in (
        ("\u201c", "'"),
        ("\u201d", "'"),
        ("\u2018", "'"),
        ("\u2019", "'"),
        ("\u2014", "-"),
        ("\u2013", "-"),
        ("\u2026", "..."),
        ("\u00a0", " "),
        ("\ufffd", "'"),
    ):
        s = s.replace(a, b)
    s = s.replace("\\", "\\\\").replace('"', '\\"').replace("\r", " ")
    s = re.sub(r"\n{3,}", "\n\n", s)
    s = s.replace("\n", "\\n")
    return '"' + s + '"'


def strip_leading_name(name: str, tip: str) -> str:
    if not tip:
        return ""
    if name and tip.lower().startswith(name.lower()):
        tip = tip[len(name) :].lstrip(" -:\n")
    return tip.strip()


def main():
    names = HUNT.get("names") or {}
    rows = []
    status_by_id = {}
    for sid, row in sorted(TIPS.items(), key=lambda kv: int(kv[0])):
        iid = int(sid)
        status = row.get("status") or "unknown"
        status_by_id[iid] = status
        name = row.get("name") or names.get(sid) or names.get(str(iid))
        tip = strip_leading_name(name or "", row.get("tip") or "")
        parts = [f'status="{status}"']
        if name:
            parts.append(f"name={lua_str(name)}")
        if row.get("quality") is not None:
            try:
                parts.append(f"quality={int(row['quality'])}")
            except (TypeError, ValueError):
                pass
        if tip:
            parts.append(f"tip={lua_str(tip)}")
        combat = bool(
            re.search(
                r"\+\d|Armor|Damage|Equip:|Use:|Chance on hit",
                tip or "",
                re.I,
            )
        )
        if status == "ok" and not combat:
            parts.append("undatamined=true")
        if status != "ok" and row.get("reason"):
            parts.append(f"reason={lua_str(row['reason'])}")
        rows.append(f"    [{iid}]={{{','.join(parts)}}},")

    ADDON.write_text(
        """local _, GQ = ...
GQ.Data = GQ.Data or {}

-- GENERATED by pipeline/scripts/probe_forever_hunt_tooltips.py
-- Wowhead Forever tooltip audit of every hunt item id (1-60, all classes).
-- status=ok|missing|unknown. missing rows are dropped from the hunt list.

GQ.Data.foreverAudit = {
"""
        + "\n".join(rows)
        + """
}
""",
        encoding="utf-8",
        newline="\n",
    )

    by_class = {}
    picks = HUNT.get("picks") or []
    class_spec = defaultdict(lambda: Counter())
    missing_examples = defaultdict(list)
    unknown_examples = defaultdict(list)
    empty_tip = []
    seen_pick = set()
    for p in picks:
        iid = int(p["id"])
        cls = p["class"]
        spec = p["spec"]
        key = (cls, spec, iid)
        if key in seen_pick:
            continue
        seen_pick.add(key)
        st = status_by_id.get(iid, "unknown")
        class_spec[(cls, spec)][st] += 1
        name = names.get(str(iid)) or (TIPS.get(str(iid)) or {}).get("name") or str(iid)
        if st == "missing" and len(missing_examples[cls]) < 8:
            missing_examples[cls].append({"id": iid, "name": name, "slot": p["slot"], "lo": p["lo"], "hi": p["hi"]})
        if st == "unknown" and len(unknown_examples[cls]) < 8:
            unknown_examples[cls].append({"id": iid, "name": name, "reason": (TIPS.get(str(iid)) or {}).get("reason")})

    for iid, st in status_by_id.items():
        row = TIPS.get(str(iid)) or {}
        if st == "ok" and not row.get("tip"):
            empty_tip.append(iid)

    counts = Counter(status_by_id.values())
    per_class_spec = []
    for (cls, spec), ctr in sorted(class_spec.items()):
        per_class_spec.append(
            {
                "class": cls,
                "spec": spec,
                "ok": ctr.get("ok", 0),
                "missing": ctr.get("missing", 0),
                "unknown": ctr.get("unknown", 0),
                "total": sum(ctr.values()),
            }
        )

    summary = {
        "uniqueIds": len(status_by_id),
        "counts": dict(counts),
        "okWithoutTip": len(empty_tip),
        "perClassSpec": per_class_spec,
        "missingExamples": missing_examples,
        "unknownExamples": unknown_examples,
        "source": "Wowhead Forever nether tooltip /forever/tooltip/item/{id}",
    }
    SUMMARY.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    print("wrote", ADDON, "rows", len(rows))
    print("summary", counts, "ok-without-tip", len(empty_tip))


if __name__ == "__main__":
    main()
