"""Emit GQ.Data.foreverAudit from hunt_tooltips.json + a JSON summary."""
from __future__ import annotations

import json
import re
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CACHE = ROOT / "pipeline" / "data" / "forever_wowhead"
HUNT = json.loads((CACHE / "hunt_ids.json").read_text(encoding="utf-8"))
TIPS = json.loads((CACHE / "hunt_tooltips.json").read_text(encoding="utf-8"))
_PINS = ROOT / "pipeline" / "data" / "client_item_overrides.json"
PINS = json.loads(_PINS.read_text(encoding="utf-8")) if _PINS.exists() else {}
ITEMS = json.loads((ROOT / "pipeline" / "data" / "items.json").read_text(encoding="utf-8"))
SOURCES = json.loads((ROOT / "pipeline" / "data" / "sources.json").read_text(encoding="utf-8"))
ADDON = ROOT / "GearQuest" / "_generated" / "Data.ForeverAudit.generated.lua"
SUMMARY = CACHE / "forever_audit.summary.json"
# Nether still prints 11.39 DPS. The shipped tip is the client 17.5.
WAND = 11288


def lua_str(s: str) -> str:
    s = str(s or "")
    for a, b in (
        ("\u201c", "'"),
        ("\u201d", "'"),
        ("\u2018", "'"),
        ("\u2019", "'"),
        ("\u2014", "-"),
        ("\u2013", "-"),
        ("\u2026", "..."),
        ("\u00a0", " "),
        ("\ufffd", "'"),
    ):
        s = s.replace(a, b)
    s = s.replace("\\", "\\\\").replace('"', '\\"').replace("\r", " ")
    s = re.sub(r"\n{3,}", "\n\n", s)
    s = s.replace("\n", "\\n")
    return '"' + s + '"'


def existing_rows() -> dict[int, str]:
    if not ADDON.exists():
        return {}
    rows = {}
    for line in ADDON.read_text(encoding="utf-8").splitlines():
        match = re.match(r"    \[(\d+)\]=\{.*\},?$", line)
        if match:
            rows[int(match.group(1))] = line if line.endswith(",") else line + ","
    return rows


def keep_rebuilt_tip(iid: int) -> bool:
    """Random-suffix greens keep the rebuilt jackpot tip.

    A fixed green, including a world drop or a rare, takes the Wowhead Forever
    tip. Keeping every quality-2 drop left classic weapon damage on the hover
    (Heavy Shortbow 17-33 instead of Forever 10-20).
    """
    if iid == WAND:
        return True
    item = ITEMS.get(str(iid)) or {}
    return bool(item.get("randomEnchant"))


def strip_leading_name(name: str, tip: str) -> str:
    if not tip:
        return ""
    if name and tip.lower().startswith(name.lower()):
        tip = tip[len(name) :].lstrip(" -:\n")
    return tip.strip()


def main():
    names = HUNT.get("names") or {}
    prior = existing_rows()
    kept = 0
    rows = []
    status_by_id = {}
    for sid, row in sorted(TIPS.items(), key=lambda kv: int(kv[0])):
        iid = int(sid)
        if iid in prior and keep_rebuilt_tip(iid):
            line = prior[iid]
            if row.get("quality") is not None:
                try:
                    q = int(row["quality"])
                except (TypeError, ValueError):
                    q = None
                if q is not None and "quality=" in line:
                    line = re.sub(r"quality=\d+", f"quality={q}", line, count=1)
            rows.append(line)
            status_by_id[iid] = row.get("status") or "ok"
            kept += 1
            continue
        status = row.get("status") or "unknown"
        status_by_id[iid] = status
        name = row.get("name") or names.get(sid) or names.get(str(iid))
        pin = PINS.get(sid) or PINS.get(str(iid)) or {}
        if pin.get("tip"):
            # Client tooltip wins for these ids. The cached nether tip does not.
            tip = pin["tip"]
        else:
            tip = strip_leading_name(name or "", row.get("tip") or "")
        parts = [f'status="{status}"']
        if name:
            parts.append(f"name={lua_str(name)}")
        if row.get("quality") is not None:
            try:
                parts.append(f"quality={int(row['quality'])}")
            except (TypeError, ValueError):
                pass
        if tip:
            parts.append(f"tip={lua_str(tip)}")
        combat = bool(
            re.search(
                r"\+\d|Armor|Damage|Equip:|Use:|Chance on hit",
                tip or "",
                re.I,
            )
        )
        if status == "ok" and not combat:
            parts.append("undatamined=true")
        if status != "ok" and row.get("reason"):
            parts.append(f"reason={lua_str(row['reason'])}")
        rows.append(f"    [{iid}]={{{','.join(parts)}}},")

    ADDON.write_text(
        """local _, GQ = ...
GQ.Data = GQ.Data or {}

-- GENERATED by pipeline/scripts/probe_forever_hunt_tooltips.py
-- Wowhead Forever tooltip audit of every hunt item id (1-60, all classes).
-- status=ok|missing|unknown. missing rows are dropped from the hunt list.

GQ.Data.foreverAudit = {
"""
        + "\n".join(rows)
        + """
}
""",
        encoding="utf-8",
        newline="\n",
    )

    by_class = {}
    picks = HUNT.get("picks") or []
    class_spec = defaultdict(lambda: Counter())
    missing_examples = defaultdict(list)
    unknown_examples = defaultdict(list)
    empty_tip = []
    seen_pick = set()
    for p in picks:
        iid = int(p["id"])
        cls = p["class"]
        spec = p["spec"]
        key = (cls, spec, iid)
        if key in seen_pick:
            continue
        seen_pick.add(key)
        st = status_by_id.get(iid, "unknown")
        class_spec[(cls, spec)][st] += 1
        name = names.get(str(iid)) or (TIPS.get(str(iid)) or {}).get("name") or str(iid)
        if st == "missing" and len(missing_examples[cls]) < 8:
            missing_examples[cls].append({"id": iid, "name": name, "slot": p["slot"], "lo": p["lo"], "hi": p["hi"]})
        if st == "unknown" and len(unknown_examples[cls]) < 8:
            unknown_examples[cls].append({"id": iid, "name": name, "reason": (TIPS.get(str(iid)) or {}).get("reason")})

    for iid, st in status_by_id.items():
        row = TIPS.get(str(iid)) or {}
        if st == "ok" and not row.get("tip"):
            empty_tip.append(iid)

    counts = Counter(status_by_id.values())
    per_class_spec = []
    for (cls, spec), ctr in sorted(class_spec.items()):
        per_class_spec.append(
            {
                "class": cls,
                "spec": spec,
                "ok": ctr.get("ok", 0),
                "missing": ctr.get("missing", 0),
                "unknown": ctr.get("unknown", 0),
                "total": sum(ctr.values()),
            }
        )

    summary = {
        "uniqueIds": len(status_by_id),
        "counts": dict(counts),
        "okWithoutTip": len(empty_tip),
        "perClassSpec": per_class_spec,
        "missingExamples": missing_examples,
        "unknownExamples": unknown_examples,
        "source": "Wowhead Forever nether tooltip /forever/tooltip/item/{id}",
    }
    SUMMARY.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    print("wrote", ADDON, "rows", len(rows), "kept rebuilt", kept)
    print("summary", counts, "ok-without-tip", len(empty_tip))


if __name__ == "__main__":
    main()
