"""Fill CraftSkills.generated.lua from ForeverDB recipe shards.

https://foreverdb.net/data/crafting/{itemId % 64}.json
Each row is made: [[profession, spellId, skill, name, count], ...]
"""
import json
import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
GEN = ROOT / "GearQuest" / "_generated"
CACHE = ROOT / "pipeline" / "data" / "forever_wowhead" / "craft_skills.json"
OUT = GEN / "CraftSkills.generated.lua"
UA = "wow-classic-data-research/1.0"

ITEM_RE = re.compile(
    r'\[(\d+)\]=\{[^\n]*sourceType="profession"[^\n]*profession="([^"]+)"'
)

SLUGS = {
    "alchemy": "Alchemy",
    "blacksmithing": "Blacksmithing",
    "cooking": "Cooking",
    "enchanting": "Enchanting",
    "engineering": "Engineering",
    "firstaid": "First Aid",
    "first-aid": "First Aid",
    "fishing": "Fishing",
    "herbalism": "Herbalism",
    "leatherworking": "Leatherworking",
    "mining": "Mining",
    "skinning": "Skinning",
    "tailoring": "Tailoring",
}


def fetch_json(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=40) as resp:
        return json.load(resp)


def load_hunts():
    items = {}
    for path in GEN.glob("Data.*.generated.lua"):
        text = path.read_text(encoding="latin-1")
        for match in ITEM_RE.finditer(text):
            items.setdefault(int(match.group(1)), match.group(2))
    return items


def pick(made, profession):
    rows = []
    for entry in made or []:
        if len(entry) < 3:
            continue
        slug, spell_id, skill = entry[0], entry[1], entry[2]
        if not isinstance(skill, int) or skill <= 0:
            continue
        name = SLUGS.get(slug, profession)
        rows.append((name, int(skill), int(spell_id), slug))
    if not rows:
        return None
    wanted = (profession or "").lower().replace(" ", "")
    matched = [row for row in rows if row[3].replace("-", "") == wanted or row[0].lower() == (profession or "").lower()]
    pool = matched or rows
    pool.sort(key=lambda row: row[1])
    name, skill, spell_id, _slug = pool[0]
    return {"profession": profession or name, "skill": skill, "spellId": spell_id}


def main():
    hunts = load_hunts()
    shards = {}
    for shard in range(64):
        data = fetch_json(f"https://foreverdb.net/data/crafting/{shard}.json")
        shards[shard] = data
        print(f"shard {shard} {len(data)}", flush=True)

    rows = {}
    missing = []
    for item_id, profession in hunts.items():
        row = pick((shards[item_id % 64].get(str(item_id)) or {}).get("made"), profession)
        if row:
            rows[item_id] = row
        else:
            missing.append(item_id)

    CACHE.write_text(json.dumps({str(k): v for k, v in rows.items()}), encoding="utf-8")
    lines = [
        "-- AUTO-GENERATED by pipeline/scripts/fetch_craft_skills.py — do not edit.",
        "-- Source: ForeverDB crafting shards (recipe skill from the Forever client).",
        "",
        "local _, GQ = ...",
        "GQ.CraftSkills = GQ.CraftSkills or {}",
        "",
    ]
    for item_id in sorted(rows):
        row = rows[item_id]
        prof = row["profession"].replace("\\", "\\\\").replace('"', '\\"')
        lines.append(
            'GQ.CraftSkills[%d] = { profession = "%s", skill = %d, spellId = %d }'
            % (item_id, prof, row["skill"], row["spellId"])
        )
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} ({len(rows)} items, {len(missing)} missing)", flush=True)
    if missing:
        print("missing", " ".join(str(n) for n in missing[:40]), flush=True)


if __name__ == "__main__":
    main()
